/* Sound effects on the FM TOWNS RF5C68 wave-table PCM chip.
 *
 * The chip is the reason this port can have SFX at all.  Music is CD-DA,
 * which occupies the drive; software mixing would cost CPU this machine does
 * not have (the duel already runs well under 60 Hz on a 386SX).  The RF5C68
 * plays from its own 64 KiB wave RAM with no CPU involvement once a sample is
 * loaded and keyed on, and it is a completely separate output path from the
 * CD audio line -- so effects and music genuinely coexist.
 *
 * Design, given the chip's shape (8 channels, one 8 KiB wave-RAM slot each,
 * 7935 usable bytes per slot -- see common/sound.h):
 *
 *   - Samples live in the payload (generated by tools/fmtowns/gen_sfx_pcm.py),
 *     not on the CD.  Reading them off disc would stop the CD-DA music every
 *     time something beeped.
 *
 *   - Effects are voiced round-robin over SFX_VOICES channels, so a new
 *     effect never cuts off the one before it unless everything is busy.
 *
 *   - Each channel remembers which effect is currently loaded in its slot.
 *     Replaying the same effect on the same channel re-keys it without
 *     re-uploading the wave data, which matters because uploading goes byte
 *     by byte through the chip's 4 KiB wave-RAM window.
 *
 * The game core reaches this through sounds.c's waifu_sound_play(), which
 * calls waifu_fmtowns_sfx_play() on this target the same way it calls
 * waifu_pcfx_sfx_play() / waifu_cd32x_audio_play_sfx() on theirs.
 */
#include "fmtowns_sfx.h"
#include "sound.h"
#include "fmtowns_sfx_pcm.h"

/* Leave the top two channels free: nothing else uses them today, but the
 * chip's channels are also how any future looping ambience or a PCM music
 * fallback would play, and reserving them costs nothing at 6 simultaneous
 * effects. */
#define SFX_VOICES 6

static int g_channel_effect[SFX_VOICES];  /* effect id loaded in each slot, -1 = none */
static int g_next_voice;
static int g_ready;

/* Set by waifu_fmtowns_sfx_play() (game-core thread of control) and consumed
 * by fmtowns_sfx_update() once a frame.  Triggering straight from the call
 * would upload wave data in the middle of whatever the core was drawing;
 * queueing keeps all the chip I/O in one predictable place in the frame, and
 * collapses a burst of identical requests into one. */
static int g_pending[FMTOWNS_SFX_COUNT];

void fmtowns_sfx_init(void)
{
    int i;

    fmt_sound_init();
    for (i = 0; i < SFX_VOICES; ++i) {
        g_channel_effect[i] = -1;
    }
    for (i = 0; i < FMTOWNS_SFX_COUNT; ++i) {
        g_pending[i] = 0;
    }
    g_next_voice = 0;
    g_ready = 1;
}

void waifu_fmtowns_sfx_play(int effect)
{
    if (!g_ready || effect < 0 || effect >= FMTOWNS_SFX_COUNT) {
        return;
    }
    if (g_fmtowns_sfx_samples[effect].length == 0) {
        return;   /* no sample for this effect (see the generator) */
    }
    g_pending[effect] = 1;
}

static void trigger(int effect)
{
    const FmtownsSfxSample *s = &g_fmtowns_sfx_samples[effect];
    int voice = -1;
    int i;

    /* Prefer the channel that already holds this effect: re-keying it skips
     * the whole wave-RAM upload. */
    for (i = 0; i < SFX_VOICES; ++i) {
        if (g_channel_effect[i] == effect) {
            voice = i;
            break;
        }
    }
    if (voice < 0) {
        voice = g_next_voice;
        g_next_voice = (g_next_voice + 1) % SFX_VOICES;
    }

    fmt_sound_set_sample_rate((uint8_t)voice, s->rate);
    if (fmt_sound_play((uint8_t)voice, g_fmtowns_sfx_pcm + s->offset, s->length) == 0) {
        g_channel_effect[voice] = effect;
    } else {
        g_channel_effect[voice] = -1;
    }
}

void fmtowns_sfx_update(void)
{
    int i;

    for (i = 0; i < FMTOWNS_SFX_COUNT; ++i) {
        if (g_pending[i]) {
            g_pending[i] = 0;
            trigger(i);
        }
    }
}
