#ifndef _CDDA_TRACKS_H_
#define _CDDA_TRACKS_H_

#define CDDA_TRACK_BATTLE 3
#define CDDA_TRACK_BOSS 4
#define CDDA_TRACK_FAIL 5
#define CDDA_TRACK_FINALBOSS 6
#define CDDA_TRACK_OVERWORLD 7
#define CDDA_TRACK_TITLESCREEN_MOONLITCIPHER 8
#define CDDA_TRACK_VICTORY 9
#define CDDA_TRACK_YOULOST 10

#endif /* _CDDA_TRACKS_H_ */
