#ifndef _CDDA_TRACKS_H_
#define _CDDA_TRACKS_H_

#define CDDA_TRACK_BATTLE 2
#define CDDA_TRACK_BOSS 3
#define CDDA_TRACK_FAIL 4
#define CDDA_TRACK_FINALBOSS 5
#define CDDA_TRACK_OVERWORLD 6
#define CDDA_TRACK_TITLESCREEN_MOONLITCIPHER 7
#define CDDA_TRACK_VICTORY 8
#define CDDA_TRACK_YOULOST 9

#endif /* _CDDA_TRACKS_H_ */
