#ifndef CFX_RENDERER3D_PORT_H
#define CFX_RENDERER3D_PORT_H
#define CFX_RENDERER_MULTI_LUT 0
#define CFX_RENDERER_WORD_ORDER_PCFX 1
#define CFX_RENDERER_HEADLESS_BYTES 0
#define CFX_RENDERER_USE_V810_ASM 0
#define CFX_RENDERER_DIRECT_RECT 1
#define CFX_RENDERER_DIRECT_ROW_LUT 1
#define CFX_RENDERER_DIRECT_GENERIC_TILE 1
#define CFX_RENDERER_DIRECT_KRAM 0
#define CFX_RENDERER_QUAD_SCANLINE 0
#define CFX_RENDERER_USE_SH1_ASM 0
#endif
