#ifndef CFX_RENDERER3D_PORT_H
#define CFX_RENDERER3D_PORT_H
#if defined(WAIFU_FM_CD32X)
#define CFX_RENDERER_MULTI_LUT 0
#define CFX_RENDERER_WORD_ORDER_PCFX 0
#define CFX_RENDERER_HEADLESS_BYTES 0
#define CFX_RENDERER_USE_V810_ASM 0
#if defined(__sh__) || defined(__SH2__) || defined(__32X__)
#define CFX_RENDERER_USE_SH1_ASM 1
#else
#define CFX_RENDERER_USE_SH1_ASM 0
#endif
#define CFX_RENDERER_DIRECT_RECT 1
#define CFX_RENDERER_DIRECT_ROW_LUT 0
#define CFX_RENDERER_DIRECT_GENERIC_TILE 1
#define CFX_RENDERER_DIRECT_KRAM 0
#define CFX_RENDERER_QUAD_SCANLINE 1
#define CFX_RENDERER_BUILD_SINGLE_LUT 0
#define CFX_RENDERER_DIV_LUT 1
#define CFX_RENDERER_DIRECT_FLAT_ROW 0
#define CFX_RENDERER_SPECIALIZED_BOARD_GRID 0
#elif defined(WAIFU_FM_FMTOWNS)
/* FM TOWNS Marty: flat-shaded only, like CD32X (see
   src/engine/renderer3d_cd32x.c / src/platform/fmtowns/STATUS.md's
   milestone 6 for why -- weaker than the PC-FX's textured/perspective
   renderer). Same span-filler structure as CD32X's branch below, but with
   i386 leaves instead of SH-2 ones, and the opposite pixel-pair byte order:
   this is a little-endian CPU writing a byte-linear framebuffer, so the LOW
   byte of a packed pair is the left pixel (see
   CFX_RENDERER_PAIR_LOW_BYTE_LEFT in renderer3d_internal.h). */
#define CFX_RENDERER_MULTI_LUT 0
#define CFX_RENDERER_WORD_ORDER_PCFX 0
#define CFX_RENDERER_PAIR_LOW_BYTE_LEFT 1
#define CFX_RENDERER_HEADLESS_BYTES 0
#define CFX_RENDERER_USE_V810_ASM 0
#define CFX_RENDERER_USE_SH1_ASM 0
#if defined(__i386__)
#define CFX_RENDERER_USE_I386_ASM 1
#else
#define CFX_RENDERER_USE_I386_ASM 0
#endif
#define CFX_RENDERER_DIRECT_RECT 1
#define CFX_RENDERER_DIRECT_ROW_LUT 0
#define CFX_RENDERER_DIRECT_GENERIC_TILE 1
#define CFX_RENDERER_DIRECT_KRAM 0
#define CFX_RENDERER_QUAD_SCANLINE 1
#define CFX_RENDERER_BUILD_SINGLE_LUT 0
#define CFX_RENDERER_DIV_LUT 1
#define CFX_RENDERER_DIRECT_FLAT_ROW 1
#define CFX_RENDERER_SPECIALIZED_BOARD_GRID 1
#elif defined(WAIFU_FM_PCFX)
#define CFX_RENDERER_MULTI_LUT 0
#define CFX_RENDERER_WORD_ORDER_PCFX 1
#define CFX_RENDERER_PAIR_LOW_BYTE_LEFT 1
#define CFX_RENDERER_HEADLESS_BYTES 0
#if defined(__v810__)
#define CFX_RENDERER_USE_V810_ASM 1
#else
#define CFX_RENDERER_USE_V810_ASM 0
#endif
#define CFX_RENDERER_DIRECT_RECT 1
#define CFX_RENDERER_DIRECT_ROW_LUT 0
#define CFX_RENDERER_DIRECT_GENERIC_TILE 1
#define CFX_RENDERER_DIRECT_KRAM 0
#define CFX_RENDERER_QUAD_SCANLINE 1
#define CFX_RENDERER_USE_SH1_ASM 0
#define CFX_RENDERER_BUILD_SINGLE_LUT 1
#define CFX_RENDERER_DIV_LUT 1
#define CFX_RENDERER_DIRECT_FLAT_ROW 0
#define CFX_RENDERER_SPECIALIZED_BOARD_GRID 0
#else
#define CFX_RENDERER_MULTI_LUT 0
#define CFX_RENDERER_WORD_ORDER_PCFX 0
#define CFX_RENDERER_HEADLESS_BYTES 1
#define CFX_RENDERER_USE_V810_ASM 0
#define CFX_RENDERER_DIRECT_RECT 1
#define CFX_RENDERER_DIRECT_ROW_LUT 0
#define CFX_RENDERER_DIRECT_GENERIC_TILE 0
#define CFX_RENDERER_DIRECT_KRAM 0
#define CFX_RENDERER_QUAD_SCANLINE 1
#define CFX_RENDERER_USE_SH1_ASM 0
#define CFX_RENDERER_BUILD_SINGLE_LUT 1
#define CFX_RENDERER_DIV_LUT 1
#define CFX_RENDERER_DIRECT_FLAT_ROW 0
#define CFX_RENDERER_SPECIALIZED_BOARD_GRID 0
#endif
#endif
