; Generated by tools/snes/gen_snes_deck.py.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_deckassets" BANK 15 SLOT 0 ORG $0000 FORCE
snes_deck_tiles:
    .INCBIN "snes_deck_tiles.bin"
snes_deck_pal:
    .INCBIN "snes_deck_pal.bin"
snes_deck_map:
    .INCBIN "snes_deck_map.bin"
.ENDS
