; Generated by tools/snes/gen_snes_obj.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_objassets" BANK 10 SLOT 0 ORG $0000 FORCE

snes_spr_font:
    .INCBIN "snes_spr_font.bin"

snes_spr_pal:
    .INCBIN "snes_spr_pal.bin"

snes_spr_group:
    .INCBIN "snes_spr_group.bin"

snes_spr_face_pal:
    .INCBIN "snes_spr_face_pal.bin"

snes_bg_pal:
    .INCBIN "snes_bg_pal.bin"

snes_top_tiles:
    .INCBIN "snes_top_tiles.bin"

snes_top_map:
    .INCBIN "snes_top_map.bin"

.ENDS
