; Generated by tools/snes/gen_snes_deck.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_deckicons_4" BANK 4 SLOT 0 ORG $0000 FORCE

snes_deckicons_4:
    .INCBIN "snes_deckicons_4.bin"

.ENDS
