; Generated by tools/snes/gen_snes_textures.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_horizon" BANK 7 SLOT 0 ORG $0000 FORCE

snes_horizon_tex:
    .INCBIN "snes_horizon_tex.bin"

.ENDS
