; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcards_46" BANK 46 SLOT 0 ORG $0000 FORCE

snes_bigcards_46:
    .INCBIN "snes_bigcards_46.bin"

.ENDS
