; Generated by tools/snes/gen_snes_planar.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_pairlut_p0_h1" BANK 52 SLOT 0 ORG $0000 FORCE

snes_pairlut_p0_h1:
    .INCBIN "snes_pairlut_p0_h1.bin"

.ENDS
