; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcards_44" BANK 44 SLOT 0 ORG $0000 FORCE

snes_bigcards_44:
    .INCBIN "snes_bigcards_44.bin"

.ENDS
