; Generated by tools/snes/gen_snes_planar.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_pairlut_p1_h0" BANK 53 SLOT 0 ORG $0000 FORCE

snes_pairlut_p1_h0:
    .INCBIN "snes_pairlut_p1_h0.bin"

.ENDS
