; Generated by tools/snes/gen_snes_planar.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_floor_chunky_1" BANK 62 SLOT 0 ORG $0000 FORCE

snes_floor_chunky_1:
    .INCBIN "snes_floor_chunky_1.bin"

.ENDS
