; Generated by tools/snes/gen_snes_cards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_cards32" BANK 59 SLOT 0 ORG $0000 FORCE

snes_card_tex32:
    .INCBIN "snes_card_tex32.bin"

.ENDS
