; Generated by tools/snes/gen_snes_cards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_cards" BANK 8 SLOT 0 ORG $0000 FORCE

snes_card_tex:
    .INCBIN "snes_card_tex.bin"

snes_card_names:
    .INCBIN "snes_card_names.bin"

.ENDS
