; Generated by tools/snes/gen_snes_cards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_cards32b" BANK 60 SLOT 0 ORG $0000 FORCE

snes_card_tex32b:
    .INCBIN "snes_card_tex32b.bin"

.ENDS
