; Generated by tools/snes/gen_snes_battle_fx.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_battlefx" BANK 15 SLOT 0 ORG $0000 FORCE

snes_fx_tiles:
    .INCBIN "snes_fx_tiles.bin"
snes_fx_pal:
    .INCBIN "snes_fx_pal.bin"
snes_battle_font:
    .INCBIN "snes_battle_font.bin"

.ENDS
