; Generated by tools/snes/gen_snes_obj.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_sprcardshi" BANK 12 SLOT 0 ORG $0000 FORCE

snes_spr_cards_hi:
    .INCBIN "snes_spr_cards_hi.bin"

.ENDS
