; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcards_33" BANK 33 SLOT 0 ORG $0000 FORCE

snes_bigcards_33:
    .INCBIN "snes_bigcards_33.bin"

.ENDS
