; Generated by tools/snes/gen_snes_audio.py.
; Each section is one 64K SPC RAM image.  The SPC header is skipped; the
; loader sends the RAM image through the APU IPL and starts its player at $0200.
.include "hdr.asm"
.BASE $C0

.SECTION "snes_audio_titlealt" BANK 19 SLOT 0 ORG $0000 FORCE
snes_audio_titlealt:
    .INCBIN "audio/titlealt.spc" SKIP $0100 READ $10000
.ENDS

.SECTION "snes_audio_overworld" BANK 20 SLOT 0 ORG $0000 FORCE
snes_audio_overworld:
    .INCBIN "audio/overworld.spc" SKIP $0100 READ $10000
.ENDS

.SECTION "snes_audio_altbattle" BANK 21 SLOT 0 ORG $0000 FORCE
snes_audio_altbattle:
    .INCBIN "audio/altbattle.spc" SKIP $0100 READ $10000
.ENDS

.SECTION "snes_audio_victory" BANK 22 SLOT 0 ORG $0000 FORCE
snes_audio_victory:
    .INCBIN "audio/victory.spc" SKIP $0100 READ $10000
.ENDS

.SECTION "snes_audio_fail" BANK 23 SLOT 0 ORG $0000 FORCE
snes_audio_fail:
    .INCBIN "audio/fail.spc" SKIP $0100 READ $10000
.ENDS
