; Generated by tools/snes/gen_snes_scenes.py.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_title" BANK 9 SLOT 0 ORG $0000 FORCE
snes_title_tiles:
    .INCBIN "snes_title_tiles.bin"
snes_title_pal:
    .INCBIN "snes_title_pal.bin"
snes_title_map:
    .INCBIN "snes_title_map.bin"
.ENDS
