; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcards_43" BANK 43 SLOT 0 ORG $0000 FORCE

snes_bigcards_43:
    .INCBIN "snes_bigcards_43.bin"

.ENDS
