; Generated by tools/snes/gen_snes_scenes.py.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_ending" BANK 13 SLOT 0 ORG $0000 FORCE
snes_ending_tiles:
    .INCBIN "snes_ending_tiles.bin"
snes_ending_pal:
    .INCBIN "snes_ending_pal.bin"
snes_ending_map:
    .INCBIN "snes_ending_map.bin"
.ENDS
