; Generated by tools/snes/gen_snes_planar.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_dbl2lut_p2" BANK 58 SLOT 0 ORG $0000 FORCE

snes_dbl2lut_p2:
    .INCBIN "snes_dbl2lut_p2.bin"

.ENDS
