; Generated by tools/snes/gen_snes_scenes.py.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_story" BANK 7 SLOT 0 ORG $0000 FORCE
snes_story_tiles:
    .INCBIN "snes_story_tiles.bin"
snes_story_pal:
    .INCBIN "snes_story_pal.bin"
snes_story_map:
    .INCBIN "snes_story_map.bin"
.ENDS
