; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcards_34" BANK 34 SLOT 0 ORG $0000 FORCE

snes_bigcards_34:
    .INCBIN "snes_bigcards_34.bin"

.ENDS
