; Generated by tools/snes/gen_snes_deck.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_deckicons_5" BANK 5 SLOT 0 ORG $0000 FORCE

snes_deckicons_5:
    .INCBIN "snes_deckicons_5.bin"

.ENDS
