; Generated by tools/snes/gen_snes_bigcards.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_bigcard_common" BANK 50 SLOT 0 ORG $0000 FORCE

snes_bigcard_feet:
    .INCBIN "snes_bigcard_feet.bin"

snes_bigcard_feet_map:
    .INCBIN "snes_bigcard_feet_map.bin"

snes_bigcard_frame_pal:
    .INCBIN "snes_bigcard_frame_pal.bin"

snes_card_info:
    .INCBIN "snes_card_info.bin"

.ENDS
