; Generated by tools/snes/gen_snes_deck.py; do not edit.
.include "hdr.asm"
.BASE $C0
.SECTION "snes_deckui" BANK 14 SLOT 0 ORG $8000 FORCE

snes_deck_bg1_tiles:
    .INCBIN "snes_deck_bg1_tiles.bin"

snes_deck_bg1_map:
    .INCBIN "snes_deck_bg1_map.bin"

snes_deck_bg1_tabs:
    .INCBIN "snes_deck_bg1_tabs.bin"

snes_deck_text_pal:
    .INCBIN "snes_deck_text_pal.bin"

.ENDS
