/* ─────────────────────────────────────────────────────────────────────────────
 * snes_audio.h — SPC700 music and one-shot SFX for the SNES fork.
 *
 * The assets are standard SPC snapshots generated by tools/snes/gen_snes_audio.py.
 * The first load uses the SNES APU IPL; later scene changes stream only the
 * snapshot regions outside the resident player code.
 * ───────────────────────────────────────────────────────────────────────────── */
#ifndef WAIFU_SNES_AUDIO_H
#define WAIFU_SNES_AUDIO_H

#include "snes_types.h"

enum SnesAudioTrack {
    SNES_AUDIO_TITLEALT = 0,
    SNES_AUDIO_OVERWORLD,
    SNES_AUDIO_ALTBATTLE,
    SNES_AUDIO_VICTORY,
    SNES_AUDIO_FAIL,
    SNES_AUDIO_TRACK_COUNT
};

enum SnesAudioSfx {
    SNES_SFX_CARD_PLACED = 0,
    SNES_SFX_CONFIRM_ALT,
    SNES_SFX_LASER,
    SNES_SFX_SELECT,
    SNES_SFX_COUNT
};

void snesAudioInit(void);
void snesAudioPlay(u8 track);
void snesAudioSfx(u8 effect);

#endif /* WAIFU_SNES_AUDIO_H */
