/* ─────────────────────────────────────────────────────────────────────────────
 *  snes_math.h — Q8.8 arithmetic, and the tables that replace division.
 *
 *  Everything geometric in this port is Q8.8 in a 16-bit word: 816-tcc's int,
 *  short and long are ALL 16 bit and 32-bit is `long long` through the software
 *  routines tcc__mull / tcc__divl, which cost hundreds of cycles a call.  So
 *  there is no 32-bit arithmetic in the renderer at all, and the range is
 *  enforced by construction rather than by a clamp: Q8.8 cannot hold the
 *  intermediate that the Atari ST port's fxdiv overflowed on, so the mistake is
 *  not available here.
 *
 *  The board is about five world units across and one unit is one slot pitch,
 *  so eight integer bits is ample for every coordinate.
 * ───────────────────────────────────────────────────────────────────────────── */
#ifndef WAIFU_SNES_MATH_H
#define WAIFU_SNES_MATH_H

#include "snes_types.h"

#define SNES_Q      8
#define SNES_ONE    256

/* snes_math.asm.  All of these go through the PPU's 8x8 hardware multiplier at
 * $4202/$4203 -> $4216, four times for a 16x16 product; they are called per
 * vertex, per row or per span, never per pixel. */
u16 snesMulHi(u16 a, u16 b);        /* the high 16 bits of an unsigned product */
s16 snesQMul(s16 a, s16 b);         /* (a * b) >> 8, Q8.8 */
u16 snesMulLo(u16 a, u16 b);        /* the low 16 bits, i.e. plain 16-bit * */
/* (a << 8) / b, saturating.  The ONLY division in the port, and confined to
 * per-frame and per-polygon setup -- the floor's two edge slopes, a card's
 * projected corners.  Nothing per row or per pixel reaches it. */
u16 snesUQDiv(u16 a, u16 b);

/* The V counter, latched off $2137.  This is the port's stopwatch: a render is
 * timed in scanlines between two reads, and the number lands in the frame
 * stamp for tools/snes/verify.py to read out of the WRAM dump.  Every perf
 * claim in this port has to come from here or from an ablation. */
u16 snesVCounter(void);
u16 snesClock(void);

/* Generated by tools/snes/gen_snes_tables.py, in ROM.
 *
 * snes_recip_row[n] is 65536/n.  It exists so the plane equation
 * depth = height*focal / rows_below is a multiply: a ROM read is 6 master
 * cycles on a FastROM cartridge and 816-tcc's 32-bit divide is several
 * hundred, and the whole floor mapper is one of these a scanline. */
#define SNES_RECIP_ROWS   256
extern const u16 snes_recip_row[SNES_RECIP_ROWS];
extern const s16 snes_recip_plane[1024];
/* 131072/n: the same divide for rows counted in pixels on the 1:1 board,
 * where a pixel row is half a unit row.  See SnesViewport.sub. */
extern const u16 snes_recip_row2[SNES_RECIP_ROWS];

/* Q8.8 sine over a 256-step turn; cosine is the same table a quarter on. */
extern const s16 snes_sin[256];
#define snesSin(a)  (snes_sin[(u8)(a)])
#define snesCos(a)  (snes_sin[(u8)((a) + 64)])

/* depth = hf / rows_below, with hf already in Q8.8 and rows_below a whole
 * number of scanlines.  Dividing a Q8.8 by an integer is a Q8.8, so this is
 * exactly one table read and one multiply. */
#define snesDepthAtRow(hf, rows_below)  snesMulHi((hf), snes_recip_row[(rows_below)])
/* The same with `rows_below` in pixel rows of a viewport whose unit is
 * 1 << sub pixels. */
#define snesDepthAtRowSub(hf, rows_below, sub) \
    snesMulHi((hf), (sub) ? snes_recip_row2[(rows_below)] : snes_recip_row[(rows_below)])

#endif /* WAIFU_SNES_MATH_H */
