/* Generated by tools/snes/gen_snes_scenes.py. */
#ifndef WAIFU_SNES_SCENE_DATA_H
#define WAIFU_SNES_SCENE_DATA_H

#include "snes_types.h"

#define SNES_SCENE_FONT_BYTES 2304
#define SNES_SCENE_BORDER_TILE 64
#define SNES_SCENE_BORDER_COUNT 8
#define SNES_STORY_TILE_BYTES 36928
#define SNES_ENDING_TILE_BYTES 36928
#define SNES_SCENE_PAL_BYTES 512
#define SNES_SCENE_MAP_BYTES 2048

extern const u8 snes_scene_font[];
extern const u8 snes_story_tiles[];
extern const u8 snes_story_pal[];
extern const u8 snes_story_map[];
extern const u8 snes_ending_tiles[];
extern const u8 snes_ending_pal[];
extern const u8 snes_ending_map[];

#endif /* WAIFU_SNES_SCENE_DATA_H */
