/* Generated by tools/snes/gen_snes_deck.py; do not edit. */
#ifndef WAIFU_SNES_DECK_DATA_H
#define WAIFU_SNES_DECK_DATA_H

#include "snes_types.h"

#define SNES_DECK_TILE_BYTES 1920
#define SNES_DECK_PAL_BYTES  512
#define SNES_DECK_MAP_BYTES  2048

extern const u8 snes_deck_tiles[];
extern const u8 snes_deck_pal[];
extern const u8 snes_deck_map[];

#endif /* WAIFU_SNES_DECK_DATA_H */
