/* Generated by tools/snes/gen_snes_planar.py; do not edit. */
#ifndef WAIFU_SNES_PLANAR_DATA_H
#define WAIFU_SNES_PLANAR_DATA_H

#include "snes_types.h"

/* The resting camera the ROM floors were rendered with, in Q8.8 where the
 * renderer wants Q8.8.  snes_duel.c MUST use these for the resting board, or
 * the cards it draws will not sit on the tiles the floor shows. */
#define SNES_REST_CAM_Z       ((s16)-1280)
#define SNES_REST_CAM_HEIGHT  ((s16)704)
#define SNES_REST_HORIZON_PX  4
#define SNES_REST_W           256
#define SNES_REST_H           144

/* Both poses: chunky 256x144 (the base the cards are drawn over) and the
 * same picture as 576 planar tiles, DMA'd straight to VRAM where no card
 * lies. */
extern const u8 snes_floor_chunky_0[];
extern const u8 snes_floor_chunky_1[];
extern const u8 snes_floor_planar_0[];
extern const u8 snes_floor_planar_1[];
#define SNES_FLOOR_CHUNKY_BANK_0  0xFD
#define SNES_FLOOR_CHUNKY_BANK_1  0xFE
#define SNES_FLOOR_PLANAR_BANK_0  0xFF
#define SNES_FLOOR_PLANAR_BANK_1  0xD0

/* Per 8-row cell band of each floor: {first, last} occupied pixel column,
 * 255/0 where the slab does not reach.  The resting frame's row span. */
static const u8 snes_floor_rowspan_0[36] = { 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 82, 173, 74, 181, 67, 188, 60, 195, 53, 202, 45, 210, 38, 217, 31, 224, 23, 232, 21, 234, 21, 234, 255, 0 };
static const u8 snes_floor_rowspan_1[36] = { 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 255, 0, 82, 173, 74, 181, 67, 188, 60, 195, 53, 202, 45, 210, 38, 217, 31, 224, 23, 232, 21, 234, 21, 234, 255, 0 };

static const u8 snes_rest_slot_boxes[160] = {
    9, 6, 12, 7, 11, 6, 14, 7, 14, 6, 17, 7, 17, 6, 20, 7, 19, 6, 22, 7,
    7, 7, 12, 9, 11, 7, 14, 9, 14, 7, 17, 9, 17, 7, 20, 9, 19, 7, 24, 9,
    5, 9, 11, 11, 9, 9, 14, 11, 13, 9, 18, 11, 17, 9, 22, 11, 20, 9, 26, 11,
    2, 11, 10, 15, 7, 11, 14, 15, 13, 11, 18, 15, 17, 11, 24, 15, 21, 11, 29, 15,
    21, 11, 29, 15, 17, 11, 24, 15, 13, 11, 18, 15, 7, 11, 14, 15, 2, 11, 10, 15,
    20, 9, 26, 11, 17, 9, 22, 11, 13, 9, 18, 11, 9, 9, 14, 11, 5, 9, 11, 11,
    19, 7, 24, 9, 17, 7, 20, 9, 14, 7, 17, 9, 11, 7, 14, 9, 7, 7, 12, 9,
    19, 6, 22, 7, 17, 6, 20, 7, 14, 6, 17, 7, 11, 6, 14, 7, 9, 6, 12, 7,
};

#endif
