/* Generated by tools/snes/gen_snes_obj.py; do not edit. */
#ifndef WAIFU_SNES_OBJ_DATA_H
#define WAIFU_SNES_OBJ_DATA_H

#include "snes_types.h"

/* A card sprite is 32x32 and lives as four rows of four tiles, which is the
 * shape of the OBJ name table a 32x32 sprite reads. */
#define SNES_SPR_CARD_PX      32
#define SNES_SPR_CARD_BYTES   512
#define SNES_SPR_CARD_ROW     128     /* one of its four rows: 4 tiles of 32 */

/* The HUD glyphs: ASCII 32..95, shadowed, OBJ palette 7. */
#define SNES_SPR_GLYPH_FIRST  32
#define SNES_SPR_GLYPH_COUNT  64
#define SNES_SPR_CORNER_COUNT 4
#define SNES_SPR_HUD_PAL      7
#define SNES_SPR_INK          1
#define SNES_SPR_GOLD         3
#define SNES_SPR_RED          4

/* The Mode 3 top view. */
#define SNES_TOP_CELL         48
#define SNES_TOP_X0           8
#define SNES_TOP_Y0           16
#define SNES_TOP_TILE_BYTES   4672

extern const u8 snes_spr_cards[];
extern const u8 snes_spr_font[];
extern const u8 snes_spr_pal[];
extern const u8 snes_spr_group[];     /* the OBJ palette each face was fitted to */
extern const u8 snes_bg_pal[];
extern const u8 snes_top_tiles[];
extern const u8 snes_top_map[];

#endif
