/* Generated by tools/snes/gen_snes_bigcards.py; do not edit. */
#ifndef WAIFU_SNES_BIGCARD_DATA_H
#define WAIFU_SNES_BIGCARD_DATA_H

#include "snes_types.h"

/* One card: the top 120x120 of the PC-FX battle frame as 225
 * 8bpp tiles, then its eighty-colour palette. */
#define SNES_BIGCARD_W          120
#define SNES_BIGCARD_H          160
#define SNES_BIGCARD_TILES_X    15
#define SNES_BIGCARD_TOP_ROWS   15
#define SNES_BIGCARD_FOOT_ROWS  5
#define SNES_BIGCARD_TILES      225
#define SNES_BIGCARD_BYTES      14400
#define SNES_BIGCARD_COLOURS    80
#define SNES_BIGCARD_FIRST      32
#define SNES_BIGCARD_PAL_BYTES  160
#define SNES_BIGCARD_RECORD     14560
#define SNES_BIGCARD_PER_BANK   4
#define SNES_BIGCARD_FIRST_BANK 30
#define SNES_BIGCARD_BANKS      20
#define SNES_BIGCARD_FEET_TILES 23
#define SNES_BIGCARD_KIND_MONSTER 0
#define SNES_BIGCARD_KIND_SPELL   1
#define SNES_BIGCARD_KIND_TRAP    2
/* The card info table the check screen prints. */
#define SNES_CARD_INFO_NAME_LEN 32
#define SNES_CARD_INFO_KIND_LEN 24
#define SNES_CARD_INFO_DESC_LEN 96
#define SNES_CARD_INFO_RECORD   156
#define snesCardInfoName(f) ((const char *)&snes_card_info[(u16)(f) * SNES_CARD_INFO_RECORD])
#define snesCardInfoKind(f) ((const char *)&snes_card_info[(u16)(f) * SNES_CARD_INFO_RECORD + SNES_CARD_INFO_NAME_LEN])
#define snesCardInfoDesc(f) ((const char *)&snes_card_info[(u16)(f) * SNES_CARD_INFO_RECORD + SNES_CARD_INFO_NAME_LEN + SNES_CARD_INFO_KIND_LEN])
#define snesCardInfoStars(f) (snes_card_info[(u16)(f) * SNES_CARD_INFO_RECORD + SNES_CARD_INFO_NAME_LEN + SNES_CARD_INFO_KIND_LEN + SNES_CARD_INFO_DESC_LEN])
#define snesCardInfoFrame(f) (snes_card_info[(u16)(f) * SNES_CARD_INFO_RECORD + SNES_CARD_INFO_NAME_LEN + SNES_CARD_INFO_KIND_LEN + SNES_CARD_INFO_DESC_LEN + 1])

extern const u8 snes_bigcards_30[];
extern const u8 snes_bigcards_31[];
extern const u8 snes_bigcards_32[];
extern const u8 snes_bigcards_33[];
extern const u8 snes_bigcards_34[];
extern const u8 snes_bigcards_35[];
extern const u8 snes_bigcards_36[];
extern const u8 snes_bigcards_37[];
extern const u8 snes_bigcards_38[];
extern const u8 snes_bigcards_39[];
extern const u8 snes_bigcards_40[];
extern const u8 snes_bigcards_41[];
extern const u8 snes_bigcards_42[];
extern const u8 snes_bigcards_43[];
extern const u8 snes_bigcards_44[];
extern const u8 snes_bigcards_45[];
extern const u8 snes_bigcards_46[];
extern const u8 snes_bigcards_47[];
extern const u8 snes_bigcards_48[];
extern const u8 snes_bigcards_49[];
extern const u8 snes_bigcard_feet[];
extern const u8 snes_bigcard_feet_map[];
extern const u8 snes_bigcard_frame_pal[];
extern const u8 snes_card_info[];

/* One case per bank: a far ROM symbol must stay in the DMA
 * expression, or 816-tcc keeps the offset and loses the bank. */
#define SNES_BIGCARD_BANK_SWITCH(bank, offset, EXPR) \
    switch (bank) { \
    case 0: EXPR(snes_bigcards_30, offset); break; \
    case 1: EXPR(snes_bigcards_31, offset); break; \
    case 2: EXPR(snes_bigcards_32, offset); break; \
    case 3: EXPR(snes_bigcards_33, offset); break; \
    case 4: EXPR(snes_bigcards_34, offset); break; \
    case 5: EXPR(snes_bigcards_35, offset); break; \
    case 6: EXPR(snes_bigcards_36, offset); break; \
    case 7: EXPR(snes_bigcards_37, offset); break; \
    case 8: EXPR(snes_bigcards_38, offset); break; \
    case 9: EXPR(snes_bigcards_39, offset); break; \
    case 10: EXPR(snes_bigcards_40, offset); break; \
    case 11: EXPR(snes_bigcards_41, offset); break; \
    case 12: EXPR(snes_bigcards_42, offset); break; \
    case 13: EXPR(snes_bigcards_43, offset); break; \
    case 14: EXPR(snes_bigcards_44, offset); break; \
    case 15: EXPR(snes_bigcards_45, offset); break; \
    case 16: EXPR(snes_bigcards_46, offset); break; \
    case 17: EXPR(snes_bigcards_47, offset); break; \
    case 18: EXPR(snes_bigcards_48, offset); break; \
    case 19: EXPR(snes_bigcards_49, offset); break; \
    default: break; }

#endif
