/* Generated by tools/snes/gen_snes_battle_fx.py; do not edit. */
#ifndef WAIFU_SNES_BATTLE_DATA_H
#define WAIFU_SNES_BATTLE_DATA_H

#include "snes_types.h"

extern const u8 snes_fx_tiles[];
extern const u8 snes_fx_pal[];
extern const u8 snes_battle_font[];

#define SNES_FX_TILE_BYTES   12288
#define SNES_FX_PAL_BYTES    64
#define SNES_FX_FONT_BYTES   1024
#define SNES_FX_BURST_PAL    1
#define SNES_FX_DIGIT_PAL    7
#define SNES_FX_HEAT_FIRST   3
#define SNES_FX_HEAT_BANDS   6
#define SNES_FX_FIELDS       72
#define SNES_FX_CORE_S       0
#define SNES_FX_CORE_M       4
#define SNES_FX_CORE_L       8
#define SNES_FX_BLADE_HEAD   12
#define SNES_FX_BLADE_TAIL   204
#define SNES_FX_ARC0         64
#define SNES_FX_ARC1         68
#define SNES_FX_ARC2         72
#define SNES_FX_ARC3         76
#define SNES_FX_RAY0         128
#define SNES_FX_RAY1         132
#define SNES_FX_RAY2         136
#define SNES_FX_RAY3         140
#define SNES_FX_THIN0        192
#define SNES_FX_THIN1        196
#define SNES_FX_THIN2        200
#define SNES_FX_SPARK0       256
#define SNES_FX_SPARK1       257
#define SNES_FX_SPARK2       258
#define SNES_FX_SPARK3       259
#define SNES_FX_DIGIT0       272
#define SNES_FX_DIGIT_ROW2   304

/* The heat ramp the burst palette's six bands are cut from; cooling
 * by k writes bands k..k+5 into CGRAM. */
static const u16 snes_fx_heat_ramp[10] = { 0x7FFF, 0x5BFF, 0x239F, 0x0A9F, 0x057E, 0x0498, 0x0850, 0x0C29, 0x0804, 0x0000 };
/* Per FX field: the shock ring's radius and the core's radius. */
static const u8 snes_fx_ring_r[72] = { 10, 10, 10, 10, 10, 10, 10, 10, 10, 15, 21, 26, 31, 36, 41, 45, 49, 54, 58, 61, 65, 69, 72, 75, 78, 81, 84, 86, 89, 91, 93, 95, 97, 99, 101, 103, 104, 105, 107, 108, 109, 110, 111, 112, 113, 113, 114, 114, 115, 115, 115, 114, 112, 109, 107, 104, 101, 98, 94, 92, 89, 87, 85, 84, 84, 84, 84, 84, 84, 84, 84, 84 };
static const u8 snes_fx_core_r[72] = { 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 8, 10, 13, 15, 18, 21, 25, 28, 31, 34, 36, 39, 41, 42, 43, 43, 43, 43, 41, 40, 38, 36, 34, 31, 29, 26, 23, 21, 18, 15, 12, 10, 8, 5, 4, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
/* Spark launch velocities, Q12.4 pixels a field, and the variant. */
#define SNES_FX_SPARKS 12
static const u16 snes_fx_spark_vx[12] = { 0xFFDF, 0xFFC3, 0xFFC7, 0x0013, 0xFFF6, 0x0010, 0x0012, 0x003C, 0xFFDA, 0x000E, 0xFFDF, 0x0038 };
static const u16 snes_fx_spark_vy[12] = { 0xFFE4, 0x0018, 0x000D, 0xFFBE, 0xFFC9, 0x0029, 0x0027, 0xFFE2, 0xFFE6, 0xFFD9, 0xFFF2, 0x0004 };
static const u8 snes_fx_spark_kind[12] = { 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3 };

#endif
