/* ─────────────────────────────────────────────────────────────────────────────
 * snes_audio.h — SPC700 music and one-shot SFX for the SNES fork.
 *
 * The assets are standard SPC snapshots generated by tools/snes/gen_snes_audio.py.
 * The first load uses the SNES APU IPL and carries everything, the resident
 * 2-bit SFX bank included; later scene changes stream only the music region.
 * ───────────────────────────────────────────────────────────────────────────── */
#ifndef WAIFU_SNES_AUDIO_H
#define WAIFU_SNES_AUDIO_H

#include "snes_types.h"

enum SnesAudioTrack {
    SNES_AUDIO_TITLEALT = 0,
    SNES_AUDIO_OVERWORLD,
    SNES_AUDIO_ALTBATTLE,
    SNES_AUDIO_VICTORY,
    SNES_AUDIO_FAIL,
    SNES_AUDIO_TRACK_COUNT
};

/* One slot per PC WaifuSoundEffect, in that order (tools/snes/gen_snes_audio.py
 * packs the same source files the PC build plays).  YOU_LOST is a music cue
 * on every console port and is an empty slot. */
enum SnesAudioSfx {
    SNES_SFX_SELECT = 0,
    SNES_SFX_CONFIRM,
    SNES_SFX_CONFIRM_ALT,
    SNES_SFX_CARD_PLACED,
    SNES_SFX_CARD_DESTROYED,
    SNES_SFX_TURN_PASSED,
    SNES_SFX_YOU_LOST,
    SNES_SFX_LASER,
    SNES_SFX_DIRECT_HIT,
    SNES_SFX_CARD_DRAWN,
    SNES_SFX_COUNT
};

void snesAudioInit(void);
void snesAudioPlay(u8 track);
void snesAudioSfx(u8 effect);

#endif /* WAIFU_SNES_AUDIO_H */
