/* Generated by tools/snes/gen_snes_cards.py; do not edit. */
#ifndef WAIFU_SNES_CARDS_H
#define WAIFU_SNES_CARDS_H

#include "snes_types.h"

/* One face is one 256-byte page: 16x16 texels, indexed (v << 4) | u, which is
 * what lets the span walker step u with an eight-bit add that cannot reach v.
 * A face covers one board tile, so 16 texels is one world unit. */
#define SNES_CARD_TEXELS      16
#define SNES_CARD_TEXELS_LOG2 4
#define SNES_CARD_FACES       79
#define SNES_CARD_BACK        78      /* also what a set monster shows */

/* The high half of the span walker's texture index: the face's page. */
#define snesCardPage(face)    ((u16)((u16)(face) << 8))

/* The name the HUD prints, sixteen bytes a face and NUL padded, indexed by the
 * same card id the sheet is.  A fixed stride rather than a pointer table: the
 * name is read every frame and a shift beats a far indirection here. */
#define SNES_CARD_NAME_LEN    16
#define snesCardName(face)    (&snes_card_names[(u16)(face) * SNES_CARD_NAME_LEN])

extern const u8 snes_card_tex[];
extern const char snes_card_names[];

#endif
