; Generated by tools/snes/gen_snes_conv.py; do not edit.
; The unrolled chunky -> planar tile converters.  See the generator for
; the register contract and why there are four copies of each.
.include "hdr.asm"
.include "snes_fb.inc"
.include "snes_fastdp.inc"

.ACCU 16
.INDEX 16
.16BIT

.BASE $C0
.SECTION "snes_conv_gen" SUPERFREE

; jsr targets, indexed by (slot phase << 1).  Same bank as the code:
; jmp (abs,x) reads its table from the program bank.
snesConvFrameTileTab:
    .dw snesConvFrameTile0, snesConvFrameTile1
    .dw snesConvFrameTile2, snesConvFrameTile3
snesConvHalfTileTab:
    .dw snesConvHalfTile0, snesConvHalfTile1
    .dw snesConvHalfTile2, snesConvHalfTile3

; The same, spaced 64 bytes apart: the whole-frame loop indexes them
; with the slot's own phase bits (slot & $C0), no shifting.
snesConvFrameTileTab64:
    .dw snesConvFrameTile0
    .dsb 62, 0
    .dw snesConvFrameTile1
    .dsb 62, 0
    .dw snesConvFrameTile2
    .dsb 62, 0
    .dw snesConvFrameTile3

snesConvHalfTileTab64:
    .dw snesConvHalfTile0
    .dsb 62, 0
    .dw snesConvHalfTile1
    .dsb 62, 0
    .dw snesConvHalfTile2
    .dsb 62, 0
    .dw snesConvHalfTile3

snesConvFrameTile0:
    lda.w snes_frame_fb + 6,y
    asl a
    tax
    bcc _cf0_r0_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r0_p3_j
_cf0_r0_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r0_p3_j:
    sta.b $30
    lda.l snes_pairlut_p0_h0,x
    sta.b $00
    lda.l snes_pairlut_p1_h0,x
    sta.b $10
    lda.l snes_pairlut_p2_h0,x
    sta.b $20
    lda.w snes_frame_fb + 4,y
    asl a
    tax
    bcc _cf0_r0_p2_h0
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r0_p2_j
_cf0_r0_p2_h0:
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r0_p2_j:
    sta.b $30
    lda.b $00
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $00
    lda.b $10
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $10
    lda.b $20
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $20
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _cf0_r0_p1_h0
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r0_p1_j
_cf0_r0_p1_h0:
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r0_p1_j:
    sta.b $30
    lda.b $00
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $00
    lda.b $10
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $10
    lda.b $20
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $20
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _cf0_r0_p0_h0
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r0_p0_j
_cf0_r0_p0_h0:
    lda.b $30
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r0_p0_j:
    sta.b $30
    lda.b $00
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $00
    lda.b $10
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $10
    lda.b $20
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $20
    lda.w snes_frame_fb + 262,y
    asl a
    tax
    bcc _cf0_r1_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r1_p3_j
_cf0_r1_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r1_p3_j:
    sta.b $32
    lda.l snes_pairlut_p0_h0,x
    sta.b $02
    lda.l snes_pairlut_p1_h0,x
    sta.b $12
    lda.l snes_pairlut_p2_h0,x
    sta.b $22
    lda.w snes_frame_fb + 260,y
    asl a
    tax
    bcc _cf0_r1_p2_h0
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r1_p2_j
_cf0_r1_p2_h0:
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r1_p2_j:
    sta.b $32
    lda.b $02
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $02
    lda.b $12
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $12
    lda.b $22
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $22
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _cf0_r1_p1_h0
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r1_p1_j
_cf0_r1_p1_h0:
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r1_p1_j:
    sta.b $32
    lda.b $02
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $02
    lda.b $12
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $12
    lda.b $22
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $22
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _cf0_r1_p0_h0
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r1_p0_j
_cf0_r1_p0_h0:
    lda.b $32
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r1_p0_j:
    sta.b $32
    lda.b $02
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $02
    lda.b $12
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $12
    lda.b $22
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $22
    lda.w snes_frame_fb + 518,y
    asl a
    tax
    bcc _cf0_r2_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r2_p3_j
_cf0_r2_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r2_p3_j:
    sta.b $34
    lda.l snes_pairlut_p0_h0,x
    sta.b $04
    lda.l snes_pairlut_p1_h0,x
    sta.b $14
    lda.l snes_pairlut_p2_h0,x
    sta.b $24
    lda.w snes_frame_fb + 516,y
    asl a
    tax
    bcc _cf0_r2_p2_h0
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r2_p2_j
_cf0_r2_p2_h0:
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r2_p2_j:
    sta.b $34
    lda.b $04
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $04
    lda.b $14
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $14
    lda.b $24
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $24
    lda.w snes_frame_fb + 514,y
    asl a
    tax
    bcc _cf0_r2_p1_h0
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r2_p1_j
_cf0_r2_p1_h0:
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r2_p1_j:
    sta.b $34
    lda.b $04
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $04
    lda.b $14
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $14
    lda.b $24
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $24
    lda.w snes_frame_fb + 512,y
    asl a
    tax
    bcc _cf0_r2_p0_h0
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r2_p0_j
_cf0_r2_p0_h0:
    lda.b $34
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r2_p0_j:
    sta.b $34
    lda.b $04
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $04
    lda.b $14
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $14
    lda.b $24
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $24
    lda.w snes_frame_fb + 774,y
    asl a
    tax
    bcc _cf0_r3_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r3_p3_j
_cf0_r3_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r3_p3_j:
    sta.b $36
    lda.l snes_pairlut_p0_h0,x
    sta.b $06
    lda.l snes_pairlut_p1_h0,x
    sta.b $16
    lda.l snes_pairlut_p2_h0,x
    sta.b $26
    lda.w snes_frame_fb + 772,y
    asl a
    tax
    bcc _cf0_r3_p2_h0
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r3_p2_j
_cf0_r3_p2_h0:
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r3_p2_j:
    sta.b $36
    lda.b $06
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $06
    lda.b $16
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $16
    lda.b $26
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $26
    lda.w snes_frame_fb + 770,y
    asl a
    tax
    bcc _cf0_r3_p1_h0
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r3_p1_j
_cf0_r3_p1_h0:
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r3_p1_j:
    sta.b $36
    lda.b $06
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $06
    lda.b $16
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $16
    lda.b $26
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $26
    lda.w snes_frame_fb + 768,y
    asl a
    tax
    bcc _cf0_r3_p0_h0
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r3_p0_j
_cf0_r3_p0_h0:
    lda.b $36
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r3_p0_j:
    sta.b $36
    lda.b $06
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $06
    lda.b $16
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $16
    lda.b $26
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $26
    lda.w snes_frame_fb + 1030,y
    asl a
    tax
    bcc _cf0_r4_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r4_p3_j
_cf0_r4_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r4_p3_j:
    sta.b $38
    lda.l snes_pairlut_p0_h0,x
    sta.b $08
    lda.l snes_pairlut_p1_h0,x
    sta.b $18
    lda.l snes_pairlut_p2_h0,x
    sta.b $28
    lda.w snes_frame_fb + 1028,y
    asl a
    tax
    bcc _cf0_r4_p2_h0
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r4_p2_j
_cf0_r4_p2_h0:
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r4_p2_j:
    sta.b $38
    lda.b $08
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $08
    lda.b $18
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $18
    lda.b $28
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $28
    lda.w snes_frame_fb + 1026,y
    asl a
    tax
    bcc _cf0_r4_p1_h0
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r4_p1_j
_cf0_r4_p1_h0:
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r4_p1_j:
    sta.b $38
    lda.b $08
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $08
    lda.b $18
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $18
    lda.b $28
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $28
    lda.w snes_frame_fb + 1024,y
    asl a
    tax
    bcc _cf0_r4_p0_h0
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r4_p0_j
_cf0_r4_p0_h0:
    lda.b $38
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r4_p0_j:
    sta.b $38
    lda.b $08
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $08
    lda.b $18
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $18
    lda.b $28
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $28
    lda.w snes_frame_fb + 1286,y
    asl a
    tax
    bcc _cf0_r5_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r5_p3_j
_cf0_r5_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r5_p3_j:
    sta.b $3A
    lda.l snes_pairlut_p0_h0,x
    sta.b $0A
    lda.l snes_pairlut_p1_h0,x
    sta.b $1A
    lda.l snes_pairlut_p2_h0,x
    sta.b $2A
    lda.w snes_frame_fb + 1284,y
    asl a
    tax
    bcc _cf0_r5_p2_h0
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r5_p2_j
_cf0_r5_p2_h0:
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r5_p2_j:
    sta.b $3A
    lda.b $0A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0A
    lda.b $1A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1A
    lda.b $2A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2A
    lda.w snes_frame_fb + 1282,y
    asl a
    tax
    bcc _cf0_r5_p1_h0
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r5_p1_j
_cf0_r5_p1_h0:
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r5_p1_j:
    sta.b $3A
    lda.b $0A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0A
    lda.b $1A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1A
    lda.b $2A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2A
    lda.w snes_frame_fb + 1280,y
    asl a
    tax
    bcc _cf0_r5_p0_h0
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r5_p0_j
_cf0_r5_p0_h0:
    lda.b $3A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r5_p0_j:
    sta.b $3A
    lda.b $0A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0A
    lda.b $1A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1A
    lda.b $2A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2A
    lda.w snes_frame_fb + 1542,y
    asl a
    tax
    bcc _cf0_r6_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r6_p3_j
_cf0_r6_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r6_p3_j:
    sta.b $3C
    lda.l snes_pairlut_p0_h0,x
    sta.b $0C
    lda.l snes_pairlut_p1_h0,x
    sta.b $1C
    lda.l snes_pairlut_p2_h0,x
    sta.b $2C
    lda.w snes_frame_fb + 1540,y
    asl a
    tax
    bcc _cf0_r6_p2_h0
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r6_p2_j
_cf0_r6_p2_h0:
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r6_p2_j:
    sta.b $3C
    lda.b $0C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0C
    lda.b $1C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1C
    lda.b $2C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2C
    lda.w snes_frame_fb + 1538,y
    asl a
    tax
    bcc _cf0_r6_p1_h0
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r6_p1_j
_cf0_r6_p1_h0:
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r6_p1_j:
    sta.b $3C
    lda.b $0C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0C
    lda.b $1C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1C
    lda.b $2C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2C
    lda.w snes_frame_fb + 1536,y
    asl a
    tax
    bcc _cf0_r6_p0_h0
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r6_p0_j
_cf0_r6_p0_h0:
    lda.b $3C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r6_p0_j:
    sta.b $3C
    lda.b $0C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0C
    lda.b $1C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1C
    lda.b $2C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2C
    lda.w snes_frame_fb + 1798,y
    asl a
    tax
    bcc _cf0_r7_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf0_r7_p3_j
_cf0_r7_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf0_r7_p3_j:
    sta.b $3E
    lda.l snes_pairlut_p0_h0,x
    sta.b $0E
    lda.l snes_pairlut_p1_h0,x
    sta.b $1E
    lda.l snes_pairlut_p2_h0,x
    sta.b $2E
    lda.w snes_frame_fb + 1796,y
    asl a
    tax
    bcc _cf0_r7_p2_h0
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r7_p2_j
_cf0_r7_p2_h0:
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r7_p2_j:
    sta.b $3E
    lda.b $0E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0E
    lda.b $1E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1E
    lda.b $2E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2E
    lda.w snes_frame_fb + 1794,y
    asl a
    tax
    bcc _cf0_r7_p1_h0
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r7_p1_j
_cf0_r7_p1_h0:
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r7_p1_j:
    sta.b $3E
    lda.b $0E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0E
    lda.b $1E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1E
    lda.b $2E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2E
    lda.w snes_frame_fb + 1792,y
    asl a
    tax
    bcc _cf0_r7_p0_h0
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf0_r7_p0_j
_cf0_r7_p0_h0:
    lda.b $3E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf0_r7_p0_j:
    sta.b $3E
    lda.b $0E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $0E
    lda.b $1E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $1E
    lda.b $2E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $2E
    rts

snesConvFrameTile1:
    lda.w snes_frame_fb + 6,y
    asl a
    tax
    bcc _cf1_r0_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r0_p3_j
_cf1_r0_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r0_p3_j:
    sta.b $70
    lda.l snes_pairlut_p0_h0,x
    sta.b $40
    lda.l snes_pairlut_p1_h0,x
    sta.b $50
    lda.l snes_pairlut_p2_h0,x
    sta.b $60
    lda.w snes_frame_fb + 4,y
    asl a
    tax
    bcc _cf1_r0_p2_h0
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r0_p2_j
_cf1_r0_p2_h0:
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r0_p2_j:
    sta.b $70
    lda.b $40
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $40
    lda.b $50
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $50
    lda.b $60
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $60
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _cf1_r0_p1_h0
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r0_p1_j
_cf1_r0_p1_h0:
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r0_p1_j:
    sta.b $70
    lda.b $40
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $40
    lda.b $50
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $50
    lda.b $60
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $60
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _cf1_r0_p0_h0
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r0_p0_j
_cf1_r0_p0_h0:
    lda.b $70
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r0_p0_j:
    sta.b $70
    lda.b $40
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $40
    lda.b $50
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $50
    lda.b $60
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $60
    lda.w snes_frame_fb + 262,y
    asl a
    tax
    bcc _cf1_r1_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r1_p3_j
_cf1_r1_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r1_p3_j:
    sta.b $72
    lda.l snes_pairlut_p0_h0,x
    sta.b $42
    lda.l snes_pairlut_p1_h0,x
    sta.b $52
    lda.l snes_pairlut_p2_h0,x
    sta.b $62
    lda.w snes_frame_fb + 260,y
    asl a
    tax
    bcc _cf1_r1_p2_h0
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r1_p2_j
_cf1_r1_p2_h0:
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r1_p2_j:
    sta.b $72
    lda.b $42
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $42
    lda.b $52
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $52
    lda.b $62
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $62
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _cf1_r1_p1_h0
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r1_p1_j
_cf1_r1_p1_h0:
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r1_p1_j:
    sta.b $72
    lda.b $42
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $42
    lda.b $52
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $52
    lda.b $62
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $62
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _cf1_r1_p0_h0
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r1_p0_j
_cf1_r1_p0_h0:
    lda.b $72
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r1_p0_j:
    sta.b $72
    lda.b $42
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $42
    lda.b $52
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $52
    lda.b $62
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $62
    lda.w snes_frame_fb + 518,y
    asl a
    tax
    bcc _cf1_r2_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r2_p3_j
_cf1_r2_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r2_p3_j:
    sta.b $74
    lda.l snes_pairlut_p0_h0,x
    sta.b $44
    lda.l snes_pairlut_p1_h0,x
    sta.b $54
    lda.l snes_pairlut_p2_h0,x
    sta.b $64
    lda.w snes_frame_fb + 516,y
    asl a
    tax
    bcc _cf1_r2_p2_h0
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r2_p2_j
_cf1_r2_p2_h0:
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r2_p2_j:
    sta.b $74
    lda.b $44
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $44
    lda.b $54
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $54
    lda.b $64
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $64
    lda.w snes_frame_fb + 514,y
    asl a
    tax
    bcc _cf1_r2_p1_h0
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r2_p1_j
_cf1_r2_p1_h0:
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r2_p1_j:
    sta.b $74
    lda.b $44
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $44
    lda.b $54
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $54
    lda.b $64
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $64
    lda.w snes_frame_fb + 512,y
    asl a
    tax
    bcc _cf1_r2_p0_h0
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r2_p0_j
_cf1_r2_p0_h0:
    lda.b $74
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r2_p0_j:
    sta.b $74
    lda.b $44
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $44
    lda.b $54
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $54
    lda.b $64
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $64
    lda.w snes_frame_fb + 774,y
    asl a
    tax
    bcc _cf1_r3_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r3_p3_j
_cf1_r3_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r3_p3_j:
    sta.b $76
    lda.l snes_pairlut_p0_h0,x
    sta.b $46
    lda.l snes_pairlut_p1_h0,x
    sta.b $56
    lda.l snes_pairlut_p2_h0,x
    sta.b $66
    lda.w snes_frame_fb + 772,y
    asl a
    tax
    bcc _cf1_r3_p2_h0
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r3_p2_j
_cf1_r3_p2_h0:
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r3_p2_j:
    sta.b $76
    lda.b $46
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $46
    lda.b $56
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $56
    lda.b $66
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $66
    lda.w snes_frame_fb + 770,y
    asl a
    tax
    bcc _cf1_r3_p1_h0
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r3_p1_j
_cf1_r3_p1_h0:
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r3_p1_j:
    sta.b $76
    lda.b $46
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $46
    lda.b $56
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $56
    lda.b $66
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $66
    lda.w snes_frame_fb + 768,y
    asl a
    tax
    bcc _cf1_r3_p0_h0
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r3_p0_j
_cf1_r3_p0_h0:
    lda.b $76
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r3_p0_j:
    sta.b $76
    lda.b $46
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $46
    lda.b $56
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $56
    lda.b $66
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $66
    lda.w snes_frame_fb + 1030,y
    asl a
    tax
    bcc _cf1_r4_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r4_p3_j
_cf1_r4_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r4_p3_j:
    sta.b $78
    lda.l snes_pairlut_p0_h0,x
    sta.b $48
    lda.l snes_pairlut_p1_h0,x
    sta.b $58
    lda.l snes_pairlut_p2_h0,x
    sta.b $68
    lda.w snes_frame_fb + 1028,y
    asl a
    tax
    bcc _cf1_r4_p2_h0
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r4_p2_j
_cf1_r4_p2_h0:
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r4_p2_j:
    sta.b $78
    lda.b $48
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $48
    lda.b $58
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $58
    lda.b $68
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $68
    lda.w snes_frame_fb + 1026,y
    asl a
    tax
    bcc _cf1_r4_p1_h0
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r4_p1_j
_cf1_r4_p1_h0:
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r4_p1_j:
    sta.b $78
    lda.b $48
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $48
    lda.b $58
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $58
    lda.b $68
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $68
    lda.w snes_frame_fb + 1024,y
    asl a
    tax
    bcc _cf1_r4_p0_h0
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r4_p0_j
_cf1_r4_p0_h0:
    lda.b $78
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r4_p0_j:
    sta.b $78
    lda.b $48
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $48
    lda.b $58
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $58
    lda.b $68
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $68
    lda.w snes_frame_fb + 1286,y
    asl a
    tax
    bcc _cf1_r5_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r5_p3_j
_cf1_r5_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r5_p3_j:
    sta.b $7A
    lda.l snes_pairlut_p0_h0,x
    sta.b $4A
    lda.l snes_pairlut_p1_h0,x
    sta.b $5A
    lda.l snes_pairlut_p2_h0,x
    sta.b $6A
    lda.w snes_frame_fb + 1284,y
    asl a
    tax
    bcc _cf1_r5_p2_h0
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r5_p2_j
_cf1_r5_p2_h0:
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r5_p2_j:
    sta.b $7A
    lda.b $4A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4A
    lda.b $5A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5A
    lda.b $6A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6A
    lda.w snes_frame_fb + 1282,y
    asl a
    tax
    bcc _cf1_r5_p1_h0
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r5_p1_j
_cf1_r5_p1_h0:
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r5_p1_j:
    sta.b $7A
    lda.b $4A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4A
    lda.b $5A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5A
    lda.b $6A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6A
    lda.w snes_frame_fb + 1280,y
    asl a
    tax
    bcc _cf1_r5_p0_h0
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r5_p0_j
_cf1_r5_p0_h0:
    lda.b $7A
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r5_p0_j:
    sta.b $7A
    lda.b $4A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4A
    lda.b $5A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5A
    lda.b $6A
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6A
    lda.w snes_frame_fb + 1542,y
    asl a
    tax
    bcc _cf1_r6_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r6_p3_j
_cf1_r6_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r6_p3_j:
    sta.b $7C
    lda.l snes_pairlut_p0_h0,x
    sta.b $4C
    lda.l snes_pairlut_p1_h0,x
    sta.b $5C
    lda.l snes_pairlut_p2_h0,x
    sta.b $6C
    lda.w snes_frame_fb + 1540,y
    asl a
    tax
    bcc _cf1_r6_p2_h0
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r6_p2_j
_cf1_r6_p2_h0:
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r6_p2_j:
    sta.b $7C
    lda.b $4C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4C
    lda.b $5C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5C
    lda.b $6C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6C
    lda.w snes_frame_fb + 1538,y
    asl a
    tax
    bcc _cf1_r6_p1_h0
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r6_p1_j
_cf1_r6_p1_h0:
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r6_p1_j:
    sta.b $7C
    lda.b $4C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4C
    lda.b $5C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5C
    lda.b $6C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6C
    lda.w snes_frame_fb + 1536,y
    asl a
    tax
    bcc _cf1_r6_p0_h0
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r6_p0_j
_cf1_r6_p0_h0:
    lda.b $7C
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r6_p0_j:
    sta.b $7C
    lda.b $4C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4C
    lda.b $5C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5C
    lda.b $6C
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6C
    lda.w snes_frame_fb + 1798,y
    asl a
    tax
    bcc _cf1_r7_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf1_r7_p3_j
_cf1_r7_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf1_r7_p3_j:
    sta.b $7E
    lda.l snes_pairlut_p0_h0,x
    sta.b $4E
    lda.l snes_pairlut_p1_h0,x
    sta.b $5E
    lda.l snes_pairlut_p2_h0,x
    sta.b $6E
    lda.w snes_frame_fb + 1796,y
    asl a
    tax
    bcc _cf1_r7_p2_h0
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r7_p2_j
_cf1_r7_p2_h0:
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r7_p2_j:
    sta.b $7E
    lda.b $4E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4E
    lda.b $5E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5E
    lda.b $6E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6E
    lda.w snes_frame_fb + 1794,y
    asl a
    tax
    bcc _cf1_r7_p1_h0
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r7_p1_j
_cf1_r7_p1_h0:
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r7_p1_j:
    sta.b $7E
    lda.b $4E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4E
    lda.b $5E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5E
    lda.b $6E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6E
    lda.w snes_frame_fb + 1792,y
    asl a
    tax
    bcc _cf1_r7_p0_h0
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf1_r7_p0_j
_cf1_r7_p0_h0:
    lda.b $7E
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf1_r7_p0_j:
    sta.b $7E
    lda.b $4E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $4E
    lda.b $5E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $5E
    lda.b $6E
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $6E
    rts

snesConvFrameTile2:
    lda.w snes_frame_fb + 6,y
    asl a
    tax
    bcc _cf2_r0_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r0_p3_j
_cf2_r0_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r0_p3_j:
    sta.b $B0
    lda.l snes_pairlut_p0_h0,x
    sta.b $80
    lda.l snes_pairlut_p1_h0,x
    sta.b $90
    lda.l snes_pairlut_p2_h0,x
    sta.b $A0
    lda.w snes_frame_fb + 4,y
    asl a
    tax
    bcc _cf2_r0_p2_h0
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r0_p2_j
_cf2_r0_p2_h0:
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r0_p2_j:
    sta.b $B0
    lda.b $80
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $80
    lda.b $90
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $90
    lda.b $A0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A0
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _cf2_r0_p1_h0
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r0_p1_j
_cf2_r0_p1_h0:
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r0_p1_j:
    sta.b $B0
    lda.b $80
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $80
    lda.b $90
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $90
    lda.b $A0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A0
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _cf2_r0_p0_h0
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r0_p0_j
_cf2_r0_p0_h0:
    lda.b $B0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r0_p0_j:
    sta.b $B0
    lda.b $80
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $80
    lda.b $90
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $90
    lda.b $A0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A0
    lda.w snes_frame_fb + 262,y
    asl a
    tax
    bcc _cf2_r1_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r1_p3_j
_cf2_r1_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r1_p3_j:
    sta.b $B2
    lda.l snes_pairlut_p0_h0,x
    sta.b $82
    lda.l snes_pairlut_p1_h0,x
    sta.b $92
    lda.l snes_pairlut_p2_h0,x
    sta.b $A2
    lda.w snes_frame_fb + 260,y
    asl a
    tax
    bcc _cf2_r1_p2_h0
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r1_p2_j
_cf2_r1_p2_h0:
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r1_p2_j:
    sta.b $B2
    lda.b $82
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $82
    lda.b $92
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $92
    lda.b $A2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A2
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _cf2_r1_p1_h0
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r1_p1_j
_cf2_r1_p1_h0:
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r1_p1_j:
    sta.b $B2
    lda.b $82
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $82
    lda.b $92
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $92
    lda.b $A2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A2
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _cf2_r1_p0_h0
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r1_p0_j
_cf2_r1_p0_h0:
    lda.b $B2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r1_p0_j:
    sta.b $B2
    lda.b $82
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $82
    lda.b $92
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $92
    lda.b $A2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A2
    lda.w snes_frame_fb + 518,y
    asl a
    tax
    bcc _cf2_r2_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r2_p3_j
_cf2_r2_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r2_p3_j:
    sta.b $B4
    lda.l snes_pairlut_p0_h0,x
    sta.b $84
    lda.l snes_pairlut_p1_h0,x
    sta.b $94
    lda.l snes_pairlut_p2_h0,x
    sta.b $A4
    lda.w snes_frame_fb + 516,y
    asl a
    tax
    bcc _cf2_r2_p2_h0
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r2_p2_j
_cf2_r2_p2_h0:
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r2_p2_j:
    sta.b $B4
    lda.b $84
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $84
    lda.b $94
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $94
    lda.b $A4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A4
    lda.w snes_frame_fb + 514,y
    asl a
    tax
    bcc _cf2_r2_p1_h0
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r2_p1_j
_cf2_r2_p1_h0:
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r2_p1_j:
    sta.b $B4
    lda.b $84
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $84
    lda.b $94
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $94
    lda.b $A4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A4
    lda.w snes_frame_fb + 512,y
    asl a
    tax
    bcc _cf2_r2_p0_h0
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r2_p0_j
_cf2_r2_p0_h0:
    lda.b $B4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r2_p0_j:
    sta.b $B4
    lda.b $84
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $84
    lda.b $94
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $94
    lda.b $A4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A4
    lda.w snes_frame_fb + 774,y
    asl a
    tax
    bcc _cf2_r3_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r3_p3_j
_cf2_r3_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r3_p3_j:
    sta.b $B6
    lda.l snes_pairlut_p0_h0,x
    sta.b $86
    lda.l snes_pairlut_p1_h0,x
    sta.b $96
    lda.l snes_pairlut_p2_h0,x
    sta.b $A6
    lda.w snes_frame_fb + 772,y
    asl a
    tax
    bcc _cf2_r3_p2_h0
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r3_p2_j
_cf2_r3_p2_h0:
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r3_p2_j:
    sta.b $B6
    lda.b $86
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $86
    lda.b $96
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $96
    lda.b $A6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A6
    lda.w snes_frame_fb + 770,y
    asl a
    tax
    bcc _cf2_r3_p1_h0
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r3_p1_j
_cf2_r3_p1_h0:
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r3_p1_j:
    sta.b $B6
    lda.b $86
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $86
    lda.b $96
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $96
    lda.b $A6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A6
    lda.w snes_frame_fb + 768,y
    asl a
    tax
    bcc _cf2_r3_p0_h0
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r3_p0_j
_cf2_r3_p0_h0:
    lda.b $B6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r3_p0_j:
    sta.b $B6
    lda.b $86
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $86
    lda.b $96
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $96
    lda.b $A6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A6
    lda.w snes_frame_fb + 1030,y
    asl a
    tax
    bcc _cf2_r4_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r4_p3_j
_cf2_r4_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r4_p3_j:
    sta.b $B8
    lda.l snes_pairlut_p0_h0,x
    sta.b $88
    lda.l snes_pairlut_p1_h0,x
    sta.b $98
    lda.l snes_pairlut_p2_h0,x
    sta.b $A8
    lda.w snes_frame_fb + 1028,y
    asl a
    tax
    bcc _cf2_r4_p2_h0
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r4_p2_j
_cf2_r4_p2_h0:
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r4_p2_j:
    sta.b $B8
    lda.b $88
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $88
    lda.b $98
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $98
    lda.b $A8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A8
    lda.w snes_frame_fb + 1026,y
    asl a
    tax
    bcc _cf2_r4_p1_h0
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r4_p1_j
_cf2_r4_p1_h0:
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r4_p1_j:
    sta.b $B8
    lda.b $88
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $88
    lda.b $98
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $98
    lda.b $A8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A8
    lda.w snes_frame_fb + 1024,y
    asl a
    tax
    bcc _cf2_r4_p0_h0
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r4_p0_j
_cf2_r4_p0_h0:
    lda.b $B8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r4_p0_j:
    sta.b $B8
    lda.b $88
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $88
    lda.b $98
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $98
    lda.b $A8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $A8
    lda.w snes_frame_fb + 1286,y
    asl a
    tax
    bcc _cf2_r5_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r5_p3_j
_cf2_r5_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r5_p3_j:
    sta.b $BA
    lda.l snes_pairlut_p0_h0,x
    sta.b $8A
    lda.l snes_pairlut_p1_h0,x
    sta.b $9A
    lda.l snes_pairlut_p2_h0,x
    sta.b $AA
    lda.w snes_frame_fb + 1284,y
    asl a
    tax
    bcc _cf2_r5_p2_h0
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r5_p2_j
_cf2_r5_p2_h0:
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r5_p2_j:
    sta.b $BA
    lda.b $8A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8A
    lda.b $9A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9A
    lda.b $AA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AA
    lda.w snes_frame_fb + 1282,y
    asl a
    tax
    bcc _cf2_r5_p1_h0
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r5_p1_j
_cf2_r5_p1_h0:
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r5_p1_j:
    sta.b $BA
    lda.b $8A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8A
    lda.b $9A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9A
    lda.b $AA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AA
    lda.w snes_frame_fb + 1280,y
    asl a
    tax
    bcc _cf2_r5_p0_h0
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r5_p0_j
_cf2_r5_p0_h0:
    lda.b $BA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r5_p0_j:
    sta.b $BA
    lda.b $8A
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8A
    lda.b $9A
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9A
    lda.b $AA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AA
    lda.w snes_frame_fb + 1542,y
    asl a
    tax
    bcc _cf2_r6_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r6_p3_j
_cf2_r6_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r6_p3_j:
    sta.b $BC
    lda.l snes_pairlut_p0_h0,x
    sta.b $8C
    lda.l snes_pairlut_p1_h0,x
    sta.b $9C
    lda.l snes_pairlut_p2_h0,x
    sta.b $AC
    lda.w snes_frame_fb + 1540,y
    asl a
    tax
    bcc _cf2_r6_p2_h0
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r6_p2_j
_cf2_r6_p2_h0:
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r6_p2_j:
    sta.b $BC
    lda.b $8C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8C
    lda.b $9C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9C
    lda.b $AC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AC
    lda.w snes_frame_fb + 1538,y
    asl a
    tax
    bcc _cf2_r6_p1_h0
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r6_p1_j
_cf2_r6_p1_h0:
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r6_p1_j:
    sta.b $BC
    lda.b $8C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8C
    lda.b $9C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9C
    lda.b $AC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AC
    lda.w snes_frame_fb + 1536,y
    asl a
    tax
    bcc _cf2_r6_p0_h0
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r6_p0_j
_cf2_r6_p0_h0:
    lda.b $BC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r6_p0_j:
    sta.b $BC
    lda.b $8C
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8C
    lda.b $9C
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9C
    lda.b $AC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AC
    lda.w snes_frame_fb + 1798,y
    asl a
    tax
    bcc _cf2_r7_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf2_r7_p3_j
_cf2_r7_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf2_r7_p3_j:
    sta.b $BE
    lda.l snes_pairlut_p0_h0,x
    sta.b $8E
    lda.l snes_pairlut_p1_h0,x
    sta.b $9E
    lda.l snes_pairlut_p2_h0,x
    sta.b $AE
    lda.w snes_frame_fb + 1796,y
    asl a
    tax
    bcc _cf2_r7_p2_h0
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r7_p2_j
_cf2_r7_p2_h0:
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r7_p2_j:
    sta.b $BE
    lda.b $8E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8E
    lda.b $9E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9E
    lda.b $AE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AE
    lda.w snes_frame_fb + 1794,y
    asl a
    tax
    bcc _cf2_r7_p1_h0
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r7_p1_j
_cf2_r7_p1_h0:
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r7_p1_j:
    sta.b $BE
    lda.b $8E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8E
    lda.b $9E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9E
    lda.b $AE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AE
    lda.w snes_frame_fb + 1792,y
    asl a
    tax
    bcc _cf2_r7_p0_h0
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf2_r7_p0_j
_cf2_r7_p0_h0:
    lda.b $BE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf2_r7_p0_j:
    sta.b $BE
    lda.b $8E
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $8E
    lda.b $9E
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $9E
    lda.b $AE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $AE
    rts

snesConvFrameTile3:
    lda.w snes_frame_fb + 6,y
    asl a
    tax
    bcc _cf3_r0_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r0_p3_j
_cf3_r0_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r0_p3_j:
    sta.b $F0
    lda.l snes_pairlut_p0_h0,x
    sta.b $C0
    lda.l snes_pairlut_p1_h0,x
    sta.b $D0
    lda.l snes_pairlut_p2_h0,x
    sta.b $E0
    lda.w snes_frame_fb + 4,y
    asl a
    tax
    bcc _cf3_r0_p2_h0
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r0_p2_j
_cf3_r0_p2_h0:
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r0_p2_j:
    sta.b $F0
    lda.b $C0
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C0
    lda.b $D0
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D0
    lda.b $E0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E0
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _cf3_r0_p1_h0
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r0_p1_j
_cf3_r0_p1_h0:
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r0_p1_j:
    sta.b $F0
    lda.b $C0
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C0
    lda.b $D0
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D0
    lda.b $E0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E0
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _cf3_r0_p0_h0
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r0_p0_j
_cf3_r0_p0_h0:
    lda.b $F0
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r0_p0_j:
    sta.b $F0
    lda.b $C0
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C0
    lda.b $D0
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D0
    lda.b $E0
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E0
    lda.w snes_frame_fb + 262,y
    asl a
    tax
    bcc _cf3_r1_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r1_p3_j
_cf3_r1_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r1_p3_j:
    sta.b $F2
    lda.l snes_pairlut_p0_h0,x
    sta.b $C2
    lda.l snes_pairlut_p1_h0,x
    sta.b $D2
    lda.l snes_pairlut_p2_h0,x
    sta.b $E2
    lda.w snes_frame_fb + 260,y
    asl a
    tax
    bcc _cf3_r1_p2_h0
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r1_p2_j
_cf3_r1_p2_h0:
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r1_p2_j:
    sta.b $F2
    lda.b $C2
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C2
    lda.b $D2
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D2
    lda.b $E2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E2
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _cf3_r1_p1_h0
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r1_p1_j
_cf3_r1_p1_h0:
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r1_p1_j:
    sta.b $F2
    lda.b $C2
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C2
    lda.b $D2
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D2
    lda.b $E2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E2
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _cf3_r1_p0_h0
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r1_p0_j
_cf3_r1_p0_h0:
    lda.b $F2
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r1_p0_j:
    sta.b $F2
    lda.b $C2
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C2
    lda.b $D2
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D2
    lda.b $E2
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E2
    lda.w snes_frame_fb + 518,y
    asl a
    tax
    bcc _cf3_r2_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r2_p3_j
_cf3_r2_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r2_p3_j:
    sta.b $F4
    lda.l snes_pairlut_p0_h0,x
    sta.b $C4
    lda.l snes_pairlut_p1_h0,x
    sta.b $D4
    lda.l snes_pairlut_p2_h0,x
    sta.b $E4
    lda.w snes_frame_fb + 516,y
    asl a
    tax
    bcc _cf3_r2_p2_h0
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r2_p2_j
_cf3_r2_p2_h0:
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r2_p2_j:
    sta.b $F4
    lda.b $C4
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C4
    lda.b $D4
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D4
    lda.b $E4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E4
    lda.w snes_frame_fb + 514,y
    asl a
    tax
    bcc _cf3_r2_p1_h0
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r2_p1_j
_cf3_r2_p1_h0:
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r2_p1_j:
    sta.b $F4
    lda.b $C4
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C4
    lda.b $D4
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D4
    lda.b $E4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E4
    lda.w snes_frame_fb + 512,y
    asl a
    tax
    bcc _cf3_r2_p0_h0
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r2_p0_j
_cf3_r2_p0_h0:
    lda.b $F4
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r2_p0_j:
    sta.b $F4
    lda.b $C4
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C4
    lda.b $D4
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D4
    lda.b $E4
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E4
    lda.w snes_frame_fb + 774,y
    asl a
    tax
    bcc _cf3_r3_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r3_p3_j
_cf3_r3_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r3_p3_j:
    sta.b $F6
    lda.l snes_pairlut_p0_h0,x
    sta.b $C6
    lda.l snes_pairlut_p1_h0,x
    sta.b $D6
    lda.l snes_pairlut_p2_h0,x
    sta.b $E6
    lda.w snes_frame_fb + 772,y
    asl a
    tax
    bcc _cf3_r3_p2_h0
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r3_p2_j
_cf3_r3_p2_h0:
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r3_p2_j:
    sta.b $F6
    lda.b $C6
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C6
    lda.b $D6
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D6
    lda.b $E6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E6
    lda.w snes_frame_fb + 770,y
    asl a
    tax
    bcc _cf3_r3_p1_h0
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r3_p1_j
_cf3_r3_p1_h0:
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r3_p1_j:
    sta.b $F6
    lda.b $C6
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C6
    lda.b $D6
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D6
    lda.b $E6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E6
    lda.w snes_frame_fb + 768,y
    asl a
    tax
    bcc _cf3_r3_p0_h0
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r3_p0_j
_cf3_r3_p0_h0:
    lda.b $F6
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r3_p0_j:
    sta.b $F6
    lda.b $C6
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C6
    lda.b $D6
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D6
    lda.b $E6
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E6
    lda.w snes_frame_fb + 1030,y
    asl a
    tax
    bcc _cf3_r4_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r4_p3_j
_cf3_r4_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r4_p3_j:
    sta.b $F8
    lda.l snes_pairlut_p0_h0,x
    sta.b $C8
    lda.l snes_pairlut_p1_h0,x
    sta.b $D8
    lda.l snes_pairlut_p2_h0,x
    sta.b $E8
    lda.w snes_frame_fb + 1028,y
    asl a
    tax
    bcc _cf3_r4_p2_h0
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r4_p2_j
_cf3_r4_p2_h0:
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r4_p2_j:
    sta.b $F8
    lda.b $C8
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C8
    lda.b $D8
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D8
    lda.b $E8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E8
    lda.w snes_frame_fb + 1026,y
    asl a
    tax
    bcc _cf3_r4_p1_h0
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r4_p1_j
_cf3_r4_p1_h0:
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r4_p1_j:
    sta.b $F8
    lda.b $C8
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C8
    lda.b $D8
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D8
    lda.b $E8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E8
    lda.w snes_frame_fb + 1024,y
    asl a
    tax
    bcc _cf3_r4_p0_h0
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r4_p0_j
_cf3_r4_p0_h0:
    lda.b $F8
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r4_p0_j:
    sta.b $F8
    lda.b $C8
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $C8
    lda.b $D8
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $D8
    lda.b $E8
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $E8
    lda.w snes_frame_fb + 1286,y
    asl a
    tax
    bcc _cf3_r5_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r5_p3_j
_cf3_r5_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r5_p3_j:
    sta.b $FA
    lda.l snes_pairlut_p0_h0,x
    sta.b $CA
    lda.l snes_pairlut_p1_h0,x
    sta.b $DA
    lda.l snes_pairlut_p2_h0,x
    sta.b $EA
    lda.w snes_frame_fb + 1284,y
    asl a
    tax
    bcc _cf3_r5_p2_h0
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r5_p2_j
_cf3_r5_p2_h0:
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r5_p2_j:
    sta.b $FA
    lda.b $CA
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CA
    lda.b $DA
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DA
    lda.b $EA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EA
    lda.w snes_frame_fb + 1282,y
    asl a
    tax
    bcc _cf3_r5_p1_h0
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r5_p1_j
_cf3_r5_p1_h0:
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r5_p1_j:
    sta.b $FA
    lda.b $CA
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CA
    lda.b $DA
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DA
    lda.b $EA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EA
    lda.w snes_frame_fb + 1280,y
    asl a
    tax
    bcc _cf3_r5_p0_h0
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r5_p0_j
_cf3_r5_p0_h0:
    lda.b $FA
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r5_p0_j:
    sta.b $FA
    lda.b $CA
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CA
    lda.b $DA
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DA
    lda.b $EA
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EA
    lda.w snes_frame_fb + 1542,y
    asl a
    tax
    bcc _cf3_r6_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r6_p3_j
_cf3_r6_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r6_p3_j:
    sta.b $FC
    lda.l snes_pairlut_p0_h0,x
    sta.b $CC
    lda.l snes_pairlut_p1_h0,x
    sta.b $DC
    lda.l snes_pairlut_p2_h0,x
    sta.b $EC
    lda.w snes_frame_fb + 1540,y
    asl a
    tax
    bcc _cf3_r6_p2_h0
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r6_p2_j
_cf3_r6_p2_h0:
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r6_p2_j:
    sta.b $FC
    lda.b $CC
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CC
    lda.b $DC
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DC
    lda.b $EC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EC
    lda.w snes_frame_fb + 1538,y
    asl a
    tax
    bcc _cf3_r6_p1_h0
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r6_p1_j
_cf3_r6_p1_h0:
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r6_p1_j:
    sta.b $FC
    lda.b $CC
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CC
    lda.b $DC
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DC
    lda.b $EC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EC
    lda.w snes_frame_fb + 1536,y
    asl a
    tax
    bcc _cf3_r6_p0_h0
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r6_p0_j
_cf3_r6_p0_h0:
    lda.b $FC
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r6_p0_j:
    sta.b $FC
    lda.b $CC
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CC
    lda.b $DC
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DC
    lda.b $EC
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EC
    lda.w snes_frame_fb + 1798,y
    asl a
    tax
    bcc _cf3_r7_p3_h0
    lda.l snes_pairlut_p3_h1,x
    bra _cf3_r7_p3_j
_cf3_r7_p3_h0:
    lda.l snes_pairlut_p3_h0,x
_cf3_r7_p3_j:
    sta.b $FE
    lda.l snes_pairlut_p0_h0,x
    sta.b $CE
    lda.l snes_pairlut_p1_h0,x
    sta.b $DE
    lda.l snes_pairlut_p2_h0,x
    sta.b $EE
    lda.w snes_frame_fb + 1796,y
    asl a
    tax
    bcc _cf3_r7_p2_h0
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r7_p2_j
_cf3_r7_p2_h0:
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r7_p2_j:
    sta.b $FE
    lda.b $CE
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CE
    lda.b $DE
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DE
    lda.b $EE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EE
    lda.w snes_frame_fb + 1794,y
    asl a
    tax
    bcc _cf3_r7_p1_h0
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r7_p1_j
_cf3_r7_p1_h0:
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r7_p1_j:
    sta.b $FE
    lda.b $CE
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CE
    lda.b $DE
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DE
    lda.b $EE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EE
    lda.w snes_frame_fb + 1792,y
    asl a
    tax
    bcc _cf3_r7_p0_h0
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h1,x
    bra _cf3_r7_p0_j
_cf3_r7_p0_h0:
    lda.b $FE
    lsr a
    lsr a
    ora.l snes_pairlut_p3_h0,x
_cf3_r7_p0_j:
    sta.b $FE
    lda.b $CE
    lsr a
    lsr a
    ora.l snes_pairlut_p0_h0,x
    sta.b $CE
    lda.b $DE
    lsr a
    lsr a
    ora.l snes_pairlut_p1_h0,x
    sta.b $DE
    lda.b $EE
    lsr a
    lsr a
    ora.l snes_pairlut_p2_h0,x
    sta.b $EE
    rts

snesConvHalfTile0:
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _ch0_r0_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch0_r0_p0_j
_ch0_r0_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch0_r0_p0_j:
    sta.b $30
    lda.l snes_dbl2lut_p0,x
    sta.b $00
    lda.l snes_dbl2lut_p1,x
    sta.b $10
    lda.l snes_dbl2lut_p2,x
    sta.b $20
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _ch0_r0_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch0_r0_p1_j
_ch0_r0_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch0_r0_p1_j:
    ora.b $30
    sta.b $30
    sta.b $32
    lda.l snes_dbl2lut4_p0,x
    ora.b $00
    sta.b $00
    sta.b $02
    lda.l snes_dbl2lut4_p1,x
    ora.b $10
    sta.b $10
    sta.b $12
    lda.l snes_dbl2lut4_p2,x
    ora.b $20
    sta.b $20
    sta.b $22
    lda.w snes_frame_fb + 128,y
    asl a
    tax
    bcc _ch0_r1_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch0_r1_p0_j
_ch0_r1_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch0_r1_p0_j:
    sta.b $34
    lda.l snes_dbl2lut_p0,x
    sta.b $04
    lda.l snes_dbl2lut_p1,x
    sta.b $14
    lda.l snes_dbl2lut_p2,x
    sta.b $24
    lda.w snes_frame_fb + 130,y
    asl a
    tax
    bcc _ch0_r1_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch0_r1_p1_j
_ch0_r1_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch0_r1_p1_j:
    ora.b $34
    sta.b $34
    sta.b $36
    lda.l snes_dbl2lut4_p0,x
    ora.b $04
    sta.b $04
    sta.b $06
    lda.l snes_dbl2lut4_p1,x
    ora.b $14
    sta.b $14
    sta.b $16
    lda.l snes_dbl2lut4_p2,x
    ora.b $24
    sta.b $24
    sta.b $26
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _ch0_r2_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch0_r2_p0_j
_ch0_r2_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch0_r2_p0_j:
    sta.b $38
    lda.l snes_dbl2lut_p0,x
    sta.b $08
    lda.l snes_dbl2lut_p1,x
    sta.b $18
    lda.l snes_dbl2lut_p2,x
    sta.b $28
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _ch0_r2_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch0_r2_p1_j
_ch0_r2_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch0_r2_p1_j:
    ora.b $38
    sta.b $38
    sta.b $3A
    lda.l snes_dbl2lut4_p0,x
    ora.b $08
    sta.b $08
    sta.b $0A
    lda.l snes_dbl2lut4_p1,x
    ora.b $18
    sta.b $18
    sta.b $1A
    lda.l snes_dbl2lut4_p2,x
    ora.b $28
    sta.b $28
    sta.b $2A
    lda.w snes_frame_fb + 384,y
    asl a
    tax
    bcc _ch0_r3_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch0_r3_p0_j
_ch0_r3_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch0_r3_p0_j:
    sta.b $3C
    lda.l snes_dbl2lut_p0,x
    sta.b $0C
    lda.l snes_dbl2lut_p1,x
    sta.b $1C
    lda.l snes_dbl2lut_p2,x
    sta.b $2C
    lda.w snes_frame_fb + 386,y
    asl a
    tax
    bcc _ch0_r3_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch0_r3_p1_j
_ch0_r3_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch0_r3_p1_j:
    ora.b $3C
    sta.b $3C
    sta.b $3E
    lda.l snes_dbl2lut4_p0,x
    ora.b $0C
    sta.b $0C
    sta.b $0E
    lda.l snes_dbl2lut4_p1,x
    ora.b $1C
    sta.b $1C
    sta.b $1E
    lda.l snes_dbl2lut4_p2,x
    ora.b $2C
    sta.b $2C
    sta.b $2E
    rts

snesConvHalfTile1:
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _ch1_r0_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch1_r0_p0_j
_ch1_r0_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch1_r0_p0_j:
    sta.b $70
    lda.l snes_dbl2lut_p0,x
    sta.b $40
    lda.l snes_dbl2lut_p1,x
    sta.b $50
    lda.l snes_dbl2lut_p2,x
    sta.b $60
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _ch1_r0_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch1_r0_p1_j
_ch1_r0_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch1_r0_p1_j:
    ora.b $70
    sta.b $70
    sta.b $72
    lda.l snes_dbl2lut4_p0,x
    ora.b $40
    sta.b $40
    sta.b $42
    lda.l snes_dbl2lut4_p1,x
    ora.b $50
    sta.b $50
    sta.b $52
    lda.l snes_dbl2lut4_p2,x
    ora.b $60
    sta.b $60
    sta.b $62
    lda.w snes_frame_fb + 128,y
    asl a
    tax
    bcc _ch1_r1_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch1_r1_p0_j
_ch1_r1_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch1_r1_p0_j:
    sta.b $74
    lda.l snes_dbl2lut_p0,x
    sta.b $44
    lda.l snes_dbl2lut_p1,x
    sta.b $54
    lda.l snes_dbl2lut_p2,x
    sta.b $64
    lda.w snes_frame_fb + 130,y
    asl a
    tax
    bcc _ch1_r1_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch1_r1_p1_j
_ch1_r1_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch1_r1_p1_j:
    ora.b $74
    sta.b $74
    sta.b $76
    lda.l snes_dbl2lut4_p0,x
    ora.b $44
    sta.b $44
    sta.b $46
    lda.l snes_dbl2lut4_p1,x
    ora.b $54
    sta.b $54
    sta.b $56
    lda.l snes_dbl2lut4_p2,x
    ora.b $64
    sta.b $64
    sta.b $66
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _ch1_r2_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch1_r2_p0_j
_ch1_r2_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch1_r2_p0_j:
    sta.b $78
    lda.l snes_dbl2lut_p0,x
    sta.b $48
    lda.l snes_dbl2lut_p1,x
    sta.b $58
    lda.l snes_dbl2lut_p2,x
    sta.b $68
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _ch1_r2_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch1_r2_p1_j
_ch1_r2_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch1_r2_p1_j:
    ora.b $78
    sta.b $78
    sta.b $7A
    lda.l snes_dbl2lut4_p0,x
    ora.b $48
    sta.b $48
    sta.b $4A
    lda.l snes_dbl2lut4_p1,x
    ora.b $58
    sta.b $58
    sta.b $5A
    lda.l snes_dbl2lut4_p2,x
    ora.b $68
    sta.b $68
    sta.b $6A
    lda.w snes_frame_fb + 384,y
    asl a
    tax
    bcc _ch1_r3_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch1_r3_p0_j
_ch1_r3_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch1_r3_p0_j:
    sta.b $7C
    lda.l snes_dbl2lut_p0,x
    sta.b $4C
    lda.l snes_dbl2lut_p1,x
    sta.b $5C
    lda.l snes_dbl2lut_p2,x
    sta.b $6C
    lda.w snes_frame_fb + 386,y
    asl a
    tax
    bcc _ch1_r3_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch1_r3_p1_j
_ch1_r3_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch1_r3_p1_j:
    ora.b $7C
    sta.b $7C
    sta.b $7E
    lda.l snes_dbl2lut4_p0,x
    ora.b $4C
    sta.b $4C
    sta.b $4E
    lda.l snes_dbl2lut4_p1,x
    ora.b $5C
    sta.b $5C
    sta.b $5E
    lda.l snes_dbl2lut4_p2,x
    ora.b $6C
    sta.b $6C
    sta.b $6E
    rts

snesConvHalfTile2:
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _ch2_r0_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch2_r0_p0_j
_ch2_r0_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch2_r0_p0_j:
    sta.b $B0
    lda.l snes_dbl2lut_p0,x
    sta.b $80
    lda.l snes_dbl2lut_p1,x
    sta.b $90
    lda.l snes_dbl2lut_p2,x
    sta.b $A0
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _ch2_r0_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch2_r0_p1_j
_ch2_r0_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch2_r0_p1_j:
    ora.b $B0
    sta.b $B0
    sta.b $B2
    lda.l snes_dbl2lut4_p0,x
    ora.b $80
    sta.b $80
    sta.b $82
    lda.l snes_dbl2lut4_p1,x
    ora.b $90
    sta.b $90
    sta.b $92
    lda.l snes_dbl2lut4_p2,x
    ora.b $A0
    sta.b $A0
    sta.b $A2
    lda.w snes_frame_fb + 128,y
    asl a
    tax
    bcc _ch2_r1_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch2_r1_p0_j
_ch2_r1_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch2_r1_p0_j:
    sta.b $B4
    lda.l snes_dbl2lut_p0,x
    sta.b $84
    lda.l snes_dbl2lut_p1,x
    sta.b $94
    lda.l snes_dbl2lut_p2,x
    sta.b $A4
    lda.w snes_frame_fb + 130,y
    asl a
    tax
    bcc _ch2_r1_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch2_r1_p1_j
_ch2_r1_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch2_r1_p1_j:
    ora.b $B4
    sta.b $B4
    sta.b $B6
    lda.l snes_dbl2lut4_p0,x
    ora.b $84
    sta.b $84
    sta.b $86
    lda.l snes_dbl2lut4_p1,x
    ora.b $94
    sta.b $94
    sta.b $96
    lda.l snes_dbl2lut4_p2,x
    ora.b $A4
    sta.b $A4
    sta.b $A6
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _ch2_r2_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch2_r2_p0_j
_ch2_r2_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch2_r2_p0_j:
    sta.b $B8
    lda.l snes_dbl2lut_p0,x
    sta.b $88
    lda.l snes_dbl2lut_p1,x
    sta.b $98
    lda.l snes_dbl2lut_p2,x
    sta.b $A8
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _ch2_r2_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch2_r2_p1_j
_ch2_r2_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch2_r2_p1_j:
    ora.b $B8
    sta.b $B8
    sta.b $BA
    lda.l snes_dbl2lut4_p0,x
    ora.b $88
    sta.b $88
    sta.b $8A
    lda.l snes_dbl2lut4_p1,x
    ora.b $98
    sta.b $98
    sta.b $9A
    lda.l snes_dbl2lut4_p2,x
    ora.b $A8
    sta.b $A8
    sta.b $AA
    lda.w snes_frame_fb + 384,y
    asl a
    tax
    bcc _ch2_r3_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch2_r3_p0_j
_ch2_r3_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch2_r3_p0_j:
    sta.b $BC
    lda.l snes_dbl2lut_p0,x
    sta.b $8C
    lda.l snes_dbl2lut_p1,x
    sta.b $9C
    lda.l snes_dbl2lut_p2,x
    sta.b $AC
    lda.w snes_frame_fb + 386,y
    asl a
    tax
    bcc _ch2_r3_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch2_r3_p1_j
_ch2_r3_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch2_r3_p1_j:
    ora.b $BC
    sta.b $BC
    sta.b $BE
    lda.l snes_dbl2lut4_p0,x
    ora.b $8C
    sta.b $8C
    sta.b $8E
    lda.l snes_dbl2lut4_p1,x
    ora.b $9C
    sta.b $9C
    sta.b $9E
    lda.l snes_dbl2lut4_p2,x
    ora.b $AC
    sta.b $AC
    sta.b $AE
    rts

snesConvHalfTile3:
    lda.w snes_frame_fb + 0,y
    asl a
    tax
    bcc _ch3_r0_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch3_r0_p0_j
_ch3_r0_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch3_r0_p0_j:
    sta.b $F0
    lda.l snes_dbl2lut_p0,x
    sta.b $C0
    lda.l snes_dbl2lut_p1,x
    sta.b $D0
    lda.l snes_dbl2lut_p2,x
    sta.b $E0
    lda.w snes_frame_fb + 2,y
    asl a
    tax
    bcc _ch3_r0_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch3_r0_p1_j
_ch3_r0_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch3_r0_p1_j:
    ora.b $F0
    sta.b $F0
    sta.b $F2
    lda.l snes_dbl2lut4_p0,x
    ora.b $C0
    sta.b $C0
    sta.b $C2
    lda.l snes_dbl2lut4_p1,x
    ora.b $D0
    sta.b $D0
    sta.b $D2
    lda.l snes_dbl2lut4_p2,x
    ora.b $E0
    sta.b $E0
    sta.b $E2
    lda.w snes_frame_fb + 128,y
    asl a
    tax
    bcc _ch3_r1_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch3_r1_p0_j
_ch3_r1_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch3_r1_p0_j:
    sta.b $F4
    lda.l snes_dbl2lut_p0,x
    sta.b $C4
    lda.l snes_dbl2lut_p1,x
    sta.b $D4
    lda.l snes_dbl2lut_p2,x
    sta.b $E4
    lda.w snes_frame_fb + 130,y
    asl a
    tax
    bcc _ch3_r1_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch3_r1_p1_j
_ch3_r1_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch3_r1_p1_j:
    ora.b $F4
    sta.b $F4
    sta.b $F6
    lda.l snes_dbl2lut4_p0,x
    ora.b $C4
    sta.b $C4
    sta.b $C6
    lda.l snes_dbl2lut4_p1,x
    ora.b $D4
    sta.b $D4
    sta.b $D6
    lda.l snes_dbl2lut4_p2,x
    ora.b $E4
    sta.b $E4
    sta.b $E6
    lda.w snes_frame_fb + 256,y
    asl a
    tax
    bcc _ch3_r2_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch3_r2_p0_j
_ch3_r2_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch3_r2_p0_j:
    sta.b $F8
    lda.l snes_dbl2lut_p0,x
    sta.b $C8
    lda.l snes_dbl2lut_p1,x
    sta.b $D8
    lda.l snes_dbl2lut_p2,x
    sta.b $E8
    lda.w snes_frame_fb + 258,y
    asl a
    tax
    bcc _ch3_r2_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch3_r2_p1_j
_ch3_r2_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch3_r2_p1_j:
    ora.b $F8
    sta.b $F8
    sta.b $FA
    lda.l snes_dbl2lut4_p0,x
    ora.b $C8
    sta.b $C8
    sta.b $CA
    lda.l snes_dbl2lut4_p1,x
    ora.b $D8
    sta.b $D8
    sta.b $DA
    lda.l snes_dbl2lut4_p2,x
    ora.b $E8
    sta.b $E8
    sta.b $EA
    lda.w snes_frame_fb + 384,y
    asl a
    tax
    bcc _ch3_r3_p0_h0
    lda.l snes_dbl2lut_p3,x
    ora #$3000
    bra _ch3_r3_p0_j
_ch3_r3_p0_h0:
    lda.l snes_dbl2lut_p3,x
_ch3_r3_p0_j:
    sta.b $FC
    lda.l snes_dbl2lut_p0,x
    sta.b $CC
    lda.l snes_dbl2lut_p1,x
    sta.b $DC
    lda.l snes_dbl2lut_p2,x
    sta.b $EC
    lda.w snes_frame_fb + 386,y
    asl a
    tax
    bcc _ch3_r3_p1_h0
    lda.l snes_dbl2lut4_p3,x
    ora #$0300
    bra _ch3_r3_p1_j
_ch3_r3_p1_h0:
    lda.l snes_dbl2lut4_p3,x
_ch3_r3_p1_j:
    ora.b $FC
    sta.b $FC
    sta.b $FE
    lda.l snes_dbl2lut4_p0,x
    ora.b $CC
    sta.b $CC
    sta.b $CE
    lda.l snes_dbl2lut4_p1,x
    ora.b $DC
    sta.b $DC
    sta.b $DE
    lda.l snes_dbl2lut4_p2,x
    ora.b $EC
    sta.b $EC
    sta.b $EE
    rts

.INCLUDE "snes_conv_drivers.inc"

.ENDS
