; ─────────────────────────────────────────────────────────────────────────────
; snes_audio.asm — SNES APU IPL upload and MIDI2SPC snapshot streaming.
;
; The SPC700 player is generated by tools/snes/gen_snes_audio.py.  It polls
; the existing MIDI2SPC SFX ports and additionally accepts:
;
;   F5=$FF, F6/F7=destination, F4=token: receive 256 bytes in 3-byte groups
;   F5=$FE, F4=token: acknowledge and restart at SPC $0200
;
; Every transfer is synchronous and NMI-safe.  Audio scene changes happen
; between frame work, and the NMI enable value is restored before returning.
; ─────────────────────────────────────────────────────────────────────────────
.include "hdr.asm"

.ACCU 8
.INDEX 16
.8BIT

.BASE $00
.RAMSECTION "snes_audio_dp" BANK 0 SLOT 1 ALIGN 256 KEEP
snes_audio_src       ds 2
snes_audio_src_bank  ds 1
snes_audio_token     ds 1
snes_audio_dest      ds 2
.ENDS

.BASE $C0
.SECTION "snes_audio_runtime" SUPERFREE
.DEFINE SNES_AUDIO_SFX_COUNT 4
; The generated player starts at $0200.  Upload through $E7FF, which covers
; the resident player, music, samples, and reload metadata while never
; touching the SPC I/O register window at $00F0-$00FF.
.DEFINE SNES_AUDIO_BOOT_START $0200
.DEFINE SNES_AUDIO_BOOT_BYTES $E600

; -----------------------------------------------------------------------------
; void snesAudioLoadSnapshot(const u8 *snapshot)
;
; Loads the boot payload through the standard Nintendo IPL protocol.  The SPC
; snapshot header, zero-page state, DSP registers, and trailing unused RAM are
; intentionally not sent: the generated player starts at $0200 and
; initializes its own state and DSP.
; -----------------------------------------------------------------------------
snesAudioLoadSnapshot:
    php
    sei
    phb
    phd
    rep #$20
    lda.w #snes_audio_src
    tad
    sep #$20
    lda #$00
    pha
    plb

    rep #$20
    lda 8,s
    clc
    adc #SNES_AUDIO_BOOT_START
    sta.b <snes_audio_src
    sep #$20
    lda 10,s
    sta.b <snes_audio_src_bank
    stz.b <snes_audio_token

    lda.l $4200
    pha
    stz $4200

    ; Wait for the SPC IPL ready word ($BBAA), then select ARAM $0000.
    rep #$20
snes_audio_boot_ready:
    ldx $2140
    cpx #$BBAA
    bne snes_audio_boot_ready
    ; Do not use 16-bit writes for the APU ports.  The ports are independent
    ; byte mailboxes, and the accurate SNES core (like hardware) can observe
    ; the two halves of a word store independently.  Port 1 is the non-zero
    ; transfer command; ports 2/3 are the destination address.
    sep #$20
    lda #$01
    sta.l $2141
    stz $2142
    lda #$02
    sta.l $2143
    sep #$20
    lda #$CC
    sta.l $2140
snes_audio_boot_cc:
    cmp.l $2140
    bne snes_audio_boot_cc

    ; A is the transfer token and B is the current byte.  The first byte is
    ; sent immediately; subsequent bytes wait for the IPL echo before reading
    ; the next ROM byte.  Y wraps after exactly 65536 bytes.
    ldy #$0000
    ldx #SNES_AUDIO_BOOT_BYTES
    lda.b [<snes_audio_src],y
    xba
    lda #$00
snes_audio_boot_send:
    sep #$20
    ; B holds the byte and A holds the current acknowledge token.  The SPC
    ; samples port 1 when it sees the new port-0 token, so publish the payload
    ; first and the token second.  A 16-bit store at $2140 is not equivalent:
    ; it can expose the token before the payload on an accurate APU model.
    xba
    sta.l $2141
    xba
    sta.l $2140
    iny
    dex
    beq snes_audio_boot_done
    xba
    lda.b [<snes_audio_src],y
    xba
snes_audio_boot_wait:
    cmp.l $2140
    bne snes_audio_boot_wait
    ina
    bra snes_audio_boot_send

snes_audio_boot_done:
snes_audio_boot_final_wait:
    cmp.l $2140
    bne snes_audio_boot_final_wait
    ina
    ina
    stz $2141
    rep #$20
    ldx #$0200
    stx $2142
    sep #$20
    sta.l $2140
snes_audio_boot_start_wait:
    cmp.l $2140
    bne snes_audio_boot_start_wait
    stz $2140

    pla
    ora #$80
    sta.l $4200
    pld
    plb
    plp
    rtl

; -----------------------------------------------------------------------------
; void snesAudioStreamBlock(const u8 *snapshot, u16 destination)
; -----------------------------------------------------------------------------
snesAudioStreamBlock:
    php
    sei
    phb
    phd
    rep #$20
    lda.w #snes_audio_src
    tad
    sep #$20
    lda #$00
    pha
    plb

    rep #$20
    lda 8,s
    sta.b <snes_audio_src
    sep #$20
    lda 10,s
    sta.b <snes_audio_src_bank
    rep #$20
    lda 12,s
    sta.b <snes_audio_dest
    sep #$20

    lda.l $4200
    pha
    stz $4200

    ; Command header: destination is written before the token, so the SPC
    ; sees a complete header when it observes the changed F4 token.
    lda #$FF
    sta.l $2141
    rep #$20
    lda.b <snes_audio_dest
    sta.l $2142
    sep #$20
    jsr snes_audio_next_token
    sta.l $2140
snes_audio_block_command_wait:
    cmp.l $2140
    bne snes_audio_block_command_wait

    rep #$10
    ldy #$0000
    ldx #$0055
    sep #$20
snes_audio_block_loop:
    lda.b [<snes_audio_src],y
    sta.l $2141
    iny
    lda.b [<snes_audio_src],y
    sta.l $2142
    iny
    lda.b [<snes_audio_src],y
    sta.l $2143
    jsr snes_audio_next_token
    sta.l $2140
snes_audio_block_group_wait:
    cmp.l $2140
    bne snes_audio_block_group_wait
    iny
    dex
    bne snes_audio_block_loop

    ; 85 groups cover 255 bytes; the final token carries the byte at $FF.
    lda.b [<snes_audio_src],y
    sta.l $2141
    jsr snes_audio_next_token
    sta.l $2140
snes_audio_block_last_wait:
    cmp.l $2140
    bne snes_audio_block_last_wait

    pla
    ora #$80
    sta.l $4200
    pld
    plb
    plp
    rtl

; -----------------------------------------------------------------------------
; void snesAudioRestart(void)
; -----------------------------------------------------------------------------
snesAudioRestart:
    php
    sei
    phb
    phd
    rep #$20
    lda.w #snes_audio_src
    tad
    sep #$20
    lda #$00
    pha
    plb

    lda.l $4200
    pha
    stz $4200
    lda #$FE
    sta.l $2141
    jsr snes_audio_next_token
    sta.l $2140
snes_audio_restart_wait:
    cmp.l $2140
    bne snes_audio_restart_wait

    pla
    ora #$80
    sta.l $4200
    pld
    plb
    plp
    rtl

; -----------------------------------------------------------------------------
; void snesAudioPlaySfx(u8 slot)
; -----------------------------------------------------------------------------
snesAudioPlaySfx:
    php
    sei
    phb
    phd
    rep #$20
    lda.w #snes_audio_src
    tad
    sep #$20
    lda #$00
    pha
    plb

    lda 8,s
    cmp #SNES_AUDIO_SFX_COUNT
    bcs snes_audio_sfx_out
    sta.l $2141
    lda #$60
    sta.l $2142
    sta.l $2143
    jsr snes_audio_next_token
    sta.l $2140

snes_audio_sfx_out:
    pld
    plb
    plp
    rtl

; A <- next non-zero command token, and the new token is saved.
snes_audio_next_token:
    lda.b <snes_audio_token
    ina
    bne snes_audio_token_ready
    lda #$01
snes_audio_token_ready:
    sta.b <snes_audio_token
    rts

.ENDS
