#!/usr/bin/env python3
"""Extract the game's real 256x240 8bpp title screen + palette out of the
committed src/generated/title_asset.h into raw binaries an FM TOWNS build
can stage onto its CD image (see Makefile.fmtowns).

title_asset.h already matches this platform's native resolution exactly
(WAIFU_FM_WIDTH/HEIGHT == 256x240, see src/engine/cfx_screen_config.h's
non-CD32X branch) and is regenerated by tools/gen_title_asset.py from the
real source art -- this script does not touch that pipeline, it just
repacks the same already-generated bytes for a different medium.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / 'src/generated/title_asset.h'


def extract_array(text, name, count):
    m = re.search(r'static const uint8_t\s+' + re.escape(name) + r'\[[^\]]*\]\s*=\s*\{(.*?)\};', text, re.S)
    if not m:
        raise SystemExit(f'{name}[] not found in {SRC}')
    nums = [int(x) for x in re.findall(r'\d+', m.group(1))]
    if len(nums) != count:
        raise SystemExit(f'{name}[] has {len(nums)} entries, expected {count}')
    return bytes(nums)


def main():
    if len(sys.argv) != 3:
        raise SystemExit(f'usage: {sys.argv[0]} <out_pixels.bin> <out_palette.bin>')
    text = SRC.read_text()
    pixels = extract_array(text, 'title_screen_img', 256 * 240)
    palette = extract_array(text, 'title_screen_palette_rgb', 256 * 3)
    Path(sys.argv[1]).write_bytes(pixels)
    Path(sys.argv[2]).write_bytes(palette)
    print(f'{sys.argv[1]}: {len(pixels)} bytes, {sys.argv[2]}: {len(palette)} bytes')


if __name__ == '__main__':
    main()
