#!/usr/bin/env python3
"""Pack projected FM TOWNS field-card texture writes for the turn poses.

The capture is produced by the host-only WAIFU_DUMP_TURN_CARD_RASTER probe.
Each record is a destination framebuffer offset, a source-card texel, and the
horizontal width of the 4x2 sample block.  Source texels stay in the packed
table while the card pointer remains live, so the cache works for arbitrary
card art/back/support textures with the same non-defense field geometry.

Usage:
    gen_turn_card_cache.py /tmp/turnframes/card_raster.bin \
        src/generated/fmtowns_turn_card_cache.h
"""

from __future__ import annotations

import argparse
import struct
from pathlib import Path


MAGIC = 0x54435231
FIELD_SLOT_FIRST = 5
FIELD_SLOTS = 10
CAPTURE_SLOTS = 20
RECORD_BYTES = 6


def format_bytes(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        lines.append('    ' + ', '.join(f'0x{v:02x}' for v in data[i:i + 16]) + ',')
    return '\n'.join(lines)


def format_words(values: list[int], width: int, suffix: str) -> str:
    lines = []
    for i in range(0, len(values), width):
        lines.append('    ' + ', '.join(str(v) + suffix for v in values[i:i + width]) + ',')
    return '\n'.join(lines)


def read_capture(path: Path):
    raw = path.read_bytes()
    if len(raw) < 12:
        raise ValueError(f'{path}: truncated header')
    magic, poses, slots = struct.unpack_from('<III', raw, 0)
    if magic != MAGIC or slots != CAPTURE_SLOTS:
        raise ValueError(f'{path}: unexpected capture header')
    off = 12
    capture = []
    for pose in range(poses):
        if off + CAPTURE_SLOTS * 4 > len(raw):
            raise ValueError(f'{path}: truncated counts at pose {pose}')
        counts = struct.unpack_from('<20I', raw, off)
        off += CAPTURE_SLOTS * 4
        by_slot = [[] for _ in range(FIELD_SLOTS)]
        for slot, count in enumerate(counts):
            if off + count * RECORD_BYTES > len(raw):
                raise ValueError(f'{path}: truncated records at pose {pose}')
            for _ in range(count):
                dst, sample, width, record_slot = struct.unpack_from('<HHBB', raw, off)
                off += RECORD_BYTES
                if record_slot != slot:
                    raise ValueError(f'{path}: record slot mismatch at pose {pose}')
                if slot < FIELD_SLOT_FIRST or slot >= FIELD_SLOT_FIRST + FIELD_SLOTS:
                    if count:
                        raise ValueError(f'{path}: non-field slot {slot} has records')
                else:
                    if width < 1 or width > 4 or sample >= 0x1000:
                        raise ValueError(f'{path}: invalid record at pose {pose}, slot {slot}')
                    by_slot[slot - FIELD_SLOT_FIRST].append((dst, sample, width))
        capture.append(by_slot)
    if off != len(raw):
        raise ValueError(f'{path}: trailing bytes')
    return capture


def generate(raw_path: Path, output_path: Path) -> None:
    capture = read_capture(raw_path)
    poses = len(capture)
    packed = bytearray()
    offsets = []
    record_count = 0
    for pose in capture:
        row = [len(packed)]
        for records in pose:
            for dst, sample, width in records:
                payload = ((width - 1) << 12) | sample
                packed.extend(struct.pack('<HH', dst, payload))
            record_count += len(records)
            row.append(len(packed))
        offsets.append(row)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    text = f'''/* Generated by tools/fmtowns/gen_turn_card_cache.py. Do not edit. */
#ifndef WAIFU_FMTOWNS_TURN_CARD_CACHE_H
#define WAIFU_FMTOWNS_TURN_CARD_CACHE_H

#include <stdint.h>

#define WAIFU_FMTOWNS_TURN_CARD_CACHE_POSES {poses}
#define WAIFU_FMTOWNS_TURN_CARD_CACHE_SLOTS {FIELD_SLOTS}
#define WAIFU_FMTOWNS_TURN_CARD_CACHE_RECORD_BYTES 4
#define WAIFU_FMTOWNS_TURN_CARD_CACHE_BYTES {len(packed)}

static const uint32_t waifu_fmtowns_turn_card_cache_offsets[{poses}][{FIELD_SLOTS + 1}] = {{
'''
    for row in offsets:
        text += '    {' + ', '.join(str(value) + 'u' for value in row) + '},\n'
    text += f'''}};

static const uint8_t waifu_fmtowns_turn_card_cache_data[{len(packed)}] = {{
{format_bytes(bytes(packed))}
}};

#endif
'''
    output_path.write_text(text)
    print(f'generated {output_path}: poses={poses} records={record_count} '
          f'packed={len(packed)} bytes')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('capture', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.capture, args.output)


if __name__ == '__main__':
    main()
