#!/usr/bin/env python3
"""Compile a text input script into a C table for the FM TOWNS debug build.

Nothing in this environment can inject a real button press into Tsugaru_CUI:
the monitor's TYPE command reaches the keyboard controller but not the game
ports, and AUTOSHOT only drives a physical host gamepad.  So the FM TOWNS
headless build presses its own buttons instead -- FMTOWNS_DEBUG_INPUT
compiles the table this script generates into the payload and ORs it into
the real pad read every frame (see fmtowns_main.c).  Being frame-indexed
rather than wall-clock-indexed, a script replays identically no matter how
fast or slow the emulator runs.

Script syntax, one step per line:

    <frame> <BUTTON[+BUTTON...]> [hold_frames] [xCOUNT@PERIOD]

    frame        game frame (60 per second of game time) to press on
    BUTTON       UP DOWN LEFT RIGHT A B START TAB, '+'-combined
    hold_frames  frames to hold it down, default 4
    xCOUNT@PERIOD  repeat the press COUNT times, PERIOD frames apart

The repeat form exists because walking a duel forward means tapping A every
half second for as long as the capture runs, and how many taps that is
changes whenever the port's frame rate does -- a faster build covers the same
wall-clock capture in far more game frames.  Writing that as one line keeps
the script from having to be regenerated by hand after every optimisation.

Blank lines and '#' comments are ignored.  Steps may be listed in any order.

Usage: gen_input_script.py script.txt out.h
"""
import sys

BUTTONS = {
    "UP": 0, "DOWN": 1, "LEFT": 2, "RIGHT": 3,
    "A": 4, "B": 5, "START": 6, "RUN": 6, "TAB": 7, "Z": 7,
}

DEFAULT_HOLD = 4


def parse(path):
    steps = []
    for lineno, raw in enumerate(open(path), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 2:
            sys.exit(f"{path}:{lineno}: expected '<frame> <BUTTON> [hold]'")
        try:
            frame = int(parts[0], 0)
        except ValueError:
            sys.exit(f"{path}:{lineno}: bad frame number {parts[0]!r}")
        bits = 0
        for name in parts[1].upper().split("+"):
            if name not in BUTTONS:
                sys.exit(f"{path}:{lineno}: unknown button {name!r}")
            bits |= 1 << BUTTONS[name]
        rest = parts[2:]
        repeat = "1@0"
        if rest and rest[-1].startswith("x"):
            repeat = rest.pop()[1:]
        hold = int(rest[0], 0) if rest else DEFAULT_HOLD
        if hold < 1:
            sys.exit(f"{path}:{lineno}: hold must be >= 1")
        try:
            count, _, period = repeat.partition("@")
            count, period = int(count, 0), int(period or 0, 0)
        except ValueError:
            sys.exit(f"{path}:{lineno}: bad repeat {repeat!r}, want xCOUNT@PERIOD")
        if count < 1 or (count > 1 and period < 1):
            sys.exit(f"{path}:{lineno}: repeat needs count >= 1 and period >= 1")
        for i in range(count):
            f = frame + i * period
            # The generated table holds frames in an unsigned short; a repeat
            # running past that would silently wrap to the start of the run
            # and press buttons in the title screen.
            if f > 0xFFFF:
                sys.exit(f"{path}:{lineno}: repeat reaches frame {f}, past 65535")
            steps.append((f, hold, bits))
    steps.sort(key=lambda s: s[0])
    return steps


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, dst = sys.argv[1], sys.argv[2]
    steps = parse(src)
    with open(dst, "w") as out:
        out.write("/* Generated by tools/fmtowns/gen_input_script.py from %s.\n"
                  " * Do not edit; edit that script and rebuild. */\n"
                  "#ifndef FMTOWNS_INPUT_SCRIPT_H\n"
                  "#define FMTOWNS_INPUT_SCRIPT_H\n\n"
                  "typedef struct FmtownsInputStep {\n"
                  "    unsigned short frame;\n"
                  "    unsigned short hold;\n"
                  "    unsigned char  bits;   /* 0=up 1=down 2=left 3=right"
                  " 4=a 5=b 6=start 7=tab */\n"
                  "} FmtownsInputStep;\n\n"
                  "static const FmtownsInputStep g_fmtowns_input_script[] = {\n"
                  % src)
        for frame, hold, bits in steps:
            out.write("    { %5d, %3d, 0x%02x },\n" % (frame, hold, bits))
        out.write("};\n\n"
                  "#define FMTOWNS_INPUT_SCRIPT_STEPS %d\n\n"
                  "#endif /* FMTOWNS_INPUT_SCRIPT_H */\n" % len(steps))
    last = steps[-1][0] + steps[-1][1] if steps else 0
    print("input script: %d steps, ends at frame %d (~%ds of game time)"
          % (len(steps), last, last // 60))


if __name__ == "__main__":
    main()
