#!/usr/bin/env python3
"""Pack projected FM TOWNS turn-card corners into a generated header.

The input is host-probe output containing lines of the form::

    GEOM pose slot x0 y0 x1 y1 x2 y2 x3 y3

The fixed-pose probe can print a few duplicate rows while warming its
benchmark poses; the final occurrence for each pose/slot is retained.

Usage:
    gen_turn_card_geometry.py card_geometry.txt \
        src/generated/fmtowns_turn_card_geometry.h
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path


LINE = re.compile(r"GEOM (-?\d+) (\d+) ((?:-?\d+ ){7}-?\d+)$")
POSES = 59
SLOTS = 10


def read_geometry(path: Path) -> list[list[list[int]]]:
    rows: dict[tuple[int, int], list[int]] = {}
    for line in path.read_text().splitlines():
        match = LINE.fullmatch(line.strip())
        if not match:
            continue
        pose = int(match.group(1))
        slot = int(match.group(2))
        points = [int(value) for value in match.group(3).split()]
        if not 0 <= pose < POSES or not 0 <= slot < SLOTS:
            continue
        if len(points) != 8 or any(not 0 <= value < 256 for value in points):
            raise ValueError(f'{path}: invalid geometry at pose {pose}, slot {slot}')
        rows[(pose, slot)] = points
    missing = [(pose, slot) for pose in range(POSES) for slot in range(SLOTS)
               if (pose, slot) not in rows]
    if missing:
        raise ValueError(f'{path}: missing geometry rows, first is {missing[0]}')
    return [[rows[(pose, slot)] for slot in range(SLOTS)] for pose in range(POSES)]


def generate(input_path: Path, output_path: Path) -> None:
    geometry = read_geometry(input_path)
    lines = [
        '/* Generated by tools/fmtowns/gen_turn_card_geometry.py. Do not edit. */',
        '#ifndef WAIFU_FMTOWNS_TURN_CARD_GEOMETRY_H',
        '#define WAIFU_FMTOWNS_TURN_CARD_GEOMETRY_H',
        '',
        '#include <stdint.h>',
        '',
        f'#define WAIFU_FMTOWNS_TURN_CARD_GEOMETRY_POSES {POSES}',
        f'#define WAIFU_FMTOWNS_TURN_CARD_GEOMETRY_SLOTS {SLOTS}',
        '',
        f'static const uint8_t waifu_fmtowns_turn_card_geometry[{POSES}][{SLOTS}][8] = {{',
    ]
    for pose in geometry:
        lines.append('    {')
        for points in pose:
            lines.append('        {' + ', '.join(str(value) for value in points) + '},')
        lines.append('    },')
    lines.extend(['};', '', '#endif', ''])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text('\n'.join(lines))
    print(f'generated {output_path}: poses={POSES} slots={SLOTS} bytes={POSES * SLOTS * 8}')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('input', type=Path)
    parser.add_argument('output', type=Path)
    args = parser.parse_args()
    generate(args.input, args.output)


if __name__ == '__main__':
    main()
