#!/usr/bin/env python3
"""Generate the MSX2 card stat tables from the shared generated asset header.

The MSX2 port is a separate frontend that never compiles src/main.c and never
sees waifu_assets.h (5.3 MB of pixel data).  What the Z80 duel rules actually
need out of that header is four small tables: ATK, DEF, attribute and tribe.
This tool lifts them into src/generated/msx2_card_tables.h as compact ROM data
(2 + 2 + 1 + 1 bytes per card, 72 cards = 432 bytes).

Regenerated by Makefile.msx2; do not hand-edit the output.
"""

import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "src", "generated", "waifu_assets.h")
CARD_DATA = os.path.join(ROOT, "assets", "source", "cards", "card_data.txt")
OUT = os.path.join(ROOT, "src", "generated", "msx2_card_tables.h")

ATTRS = ["Dark", "Light", "Earth", "Water", "Fire", "Wind"]
TRIBES = [
    "Fiend", "Insect", "Spellcaster", "Beast", "Dragon", "Fish", "Aqua",
    "Machine", "Warrior", "Winged Beast", "Reptile", "Plant", "Zombie",
    "Rock", "Thunder", "Dinosaur", "Sea Serpent",
]

# Identifier spelling for the #define emitted per tribe.
TRIBE_IDENT = {"Winged Beast": "WINGED_BEAST", "Sea Serpent": "SEA_SERPENT"}


def read(path):
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        return fh.read()


def num_table(text, name):
    m = re.search(r"waifu_card_%s\[WAIFU_CARD_COUNT\]\s*=\s*\{([^}]*)\}" % name, text)
    if not m:
        sys.exit("gen_msx_tables: table waifu_card_%s not found in %s" % (name, SRC))
    return [int(v) for v in m.group(1).replace("\n", " ").split(",") if v.strip()]


def str_table(text, name):
    m = re.search(r"waifu_card_%s\[WAIFU_CARD_COUNT\]\s*=\s*\{(.*?)\n\};" % name, text, re.S)
    if not m:
        sys.exit("gen_msx_tables: table waifu_card_%s not found in %s" % (name, SRC))
    return re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1))


def enum_index(values, table, what):
    out = []
    for v in values:
        if v not in table:
            sys.exit("gen_msx_tables: unknown %s '%s' -- add it to the table in %s"
                     % (what, v, __file__))
        out.append(table.index(v))
    return out


def emit_rows(values, per_row=12):
    lines = []
    for i in range(0, len(values), per_row):
        lines.append("    " + ",".join("%5d" % v for v in values[i:i + per_row]) + ",")
    return "\n".join(lines)


def main():
    text = read(SRC)
    atk = num_table(text, "atk")
    dfn = num_table(text, "def")
    attr = str_table(text, "attr")
    tribe = str_table(text, "tribe")
    names = str_table(text, "names")
    count = len(atk)
    for label, tbl in (("def", dfn), ("attr", attr), ("tribe", tribe), ("names", names)):
        if len(tbl) != count:
            sys.exit("gen_msx_tables: waifu_card_%s has %d entries, expected %d"
                     % (label, len(tbl), count))

    attr_i = enum_index(attr, ATTRS, "attribute")
    tribe_i = enum_index(tribe, TRIBES, "tribe")

    # Short names: the MSX board has 32 columns, so only the part before the
    # comma ("Nyxara, Abstract Chimera" -> "Nyxara") is carried, capped at 15.
    short = [n.split(",")[0].strip()[:15] for n in names]

    stamp = hashlib.sha256()
    stamp.update(read(SRC).encode("utf-8", "replace")[:0] or b"")
    for tbl in (atk, dfn, attr_i, tribe_i):
        stamp.update((",".join(str(v) for v in tbl)).encode())
    stamp.update("|".join(short).encode())
    if os.path.exists(CARD_DATA):
        stamp.update(open(CARD_DATA, "rb").read())
    digest = stamp.hexdigest()[:16]

    body = []
    body.append("/* Generated by tools/msx2/gen_msx_tables.py -- do not edit. */")
    body.append("/* Source: src/generated/waifu_assets.h + assets/source/cards/card_data.txt */")
    body.append("#ifndef MSX2_CARD_TABLES_H")
    body.append("#define MSX2_CARD_TABLES_H")
    body.append("")
    body.append('#define MSX2_CARD_TABLES_STAMP "%s"' % digest)
    body.append("#define MSX2_CARD_COUNT %d" % count)
    body.append("")
    body.append("/* Attribute ids */")
    for i, a in enumerate(ATTRS):
        body.append("#define MSX2_ATTR_%-12s %d" % (a.upper(), i))
    body.append("")
    body.append("/* Tribe ids */")
    for i, t in enumerate(TRIBES):
        body.append("#define MSX2_TRIBE_%-12s %d" % (TRIBE_IDENT.get(t, t.upper()), i))
    body.append("")
    body.append("/* The tables themselves are emitted only in the translation unit that")
    body.append("   defines MSX2_CARD_TABLES_IMPL (src/msx2/msx2_cards.c); every other")
    body.append("   includer just sees the declarations. */")
    body.append("#ifdef MSX2_CARD_TABLES_IMPL")
    body.append("")
    body.append("const u16 g_msx2_card_atk[MSX2_CARD_COUNT] = {")
    body.append(emit_rows(atk))
    body.append("};")
    body.append("")
    body.append("const u16 g_msx2_card_def[MSX2_CARD_COUNT] = {")
    body.append(emit_rows(dfn))
    body.append("};")
    body.append("")
    body.append("const u8 g_msx2_card_attr[MSX2_CARD_COUNT] = {")
    body.append(emit_rows(attr_i, 16))
    body.append("};")
    body.append("")
    body.append("const u8 g_msx2_card_tribe[MSX2_CARD_COUNT] = {")
    body.append(emit_rows(tribe_i, 16))
    body.append("};")
    body.append("")
    # No name table.  The card names the game prints come out of the
    # cartridge's TEXT segment (MSX2_NAME_OFFSET), which is where 78 of them at
    # a fixed stride belong; a second copy as C string literals was 1.1 KB of a
    # 32 KB code budget that nothing ever read.
    body.append("#else /* !MSX2_CARD_TABLES_IMPL */")
    body.append("")
    body.append("extern const u16 g_msx2_card_atk[MSX2_CARD_COUNT];")
    body.append("extern const u16 g_msx2_card_def[MSX2_CARD_COUNT];")
    body.append("extern const u8  g_msx2_card_attr[MSX2_CARD_COUNT];")
    body.append("extern const u8  g_msx2_card_tribe[MSX2_CARD_COUNT];")
    body.append("")
    body.append("#endif /* MSX2_CARD_TABLES_IMPL */")
    body.append("")
    body.append("#endif /* MSX2_CARD_TABLES_H */")

    out = "\n".join(body) + "\n"
    prev = read(OUT) if os.path.exists(OUT) else None
    if prev == out:
        print("gen_msx_tables: up to date (%s)" % digest)
        return
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(out)
    print("gen_msx_tables: wrote %s (%d cards, stamp %s)" % (OUT, count, digest))


if __name__ == "__main__":
    main()
