#!/usr/bin/env python3
"""Generate packed 8-bpp console image headers using the shared palette map."""
from __future__ import annotations
import argparse
from pathlib import Path
from PIL import Image

TRANSPARENT_YUV = 0x0888

def clamp(v: float, lo: int = 0, hi: int = 255) -> int:
    return lo if v < lo else hi if v > hi else int(round(v))

UV_OFFSETS: list[tuple[int, int, float, float, float]] = []
for _u4 in range(16):
    for _v4 in range(16):
        _u = (_u4 << 4) - 128
        _v = (_v4 << 4) - 128
        _ro = -0.000039457070707 * _u + 1.139827967171717 * _v
        _go = -0.394610164141414 * _u - 0.580500315656566 * _v
        _bo = 2.031999684343434 * _u - 0.000481376262626 * _v
        UV_OFFSETS.append((_u4, _v4, _ro, _go, _bo))

def rgb_to_pcfx_yuv_word(rgb: tuple[int, int, int]) -> int:
    r, g, b = rgb
    best_word = TRANSPARENT_YUV
    best_err = 1e30
    wr, wg, wb = 2.0, 4.0, 1.0
    for u4, v4, ro, go, bo in UV_OFFSETS:
        y = (wr * (r - ro) + wg * (g - go) + wb * (b - bo)) / (wr + wg + wb)
        yi = clamp(y)
        rr = clamp(yi + ro)
        gg = clamp(yi + go)
        bb = clamp(yi + bo)
        err = wr * (rr - r) * (rr - r) + wg * (gg - g) * (gg - g) + wb * (bb - b) * (bb - b)
        if err < best_err:
            best_err = err
            best_word = (yi << 8) | (u4 << 4) | v4
    return best_word

def rgb_to_rgb555_word(rgb: tuple[int, int, int]) -> int:
    r, g, b = rgb
    return ((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3)


def read_index_map(path: Path) -> list[int]:
    mapping = list(range(256))
    seen: set[int] = set()
    for lineno, line in enumerate(path.read_text().splitlines(), start=1):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"{path}:{lineno}: expected 'old new'")
        old, new = int(parts[0], 0), int(parts[1], 0)
        if not (0 <= old <= 255 and 0 <= new <= 255):
            raise ValueError(f"{path}:{lineno}: palette index out of range")
        mapping[old] = new
        seen.add(old)
    if len(seen) != 256:
        raise ValueError(f"{path}: map must define all 256 entries")
    return mapping


def load_indexed(path: Path, width: int, height: int) -> bytes:
    im = Image.open(path)
    if im.mode != 'P':
        raise ValueError(f"{path}: expected indexed PNG, got {im.mode}")
    if im.size != (width, height):
        raise ValueError(f"{path}: expected {width}x{height}, got {im.size}")
    return bytes(im.getdata())


def write_packed_header(path: Path, symbol: str, pixels: bytes, mapping: list[int]) -> None:
    remapped = bytes(mapping[p] for p in pixels)
    if len(remapped) & 1:
        raise ValueError(f"{symbol}: packed image byte count must be even")
    words = [(remapped[i] << 8) | remapped[i + 1] for i in range(0, len(remapped), 2)]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_console_assets.py. */\n')
        f.write(f'const unsigned short {symbol}[{len(words)}] = {{\n')
        for i in range(0, len(words), 8):
            f.write('\t' + ', '.join(f'0x{x:04x}' for x in words[i:i + 8]))
            if i + 8 < len(words):
                f.write(',')
            f.write('\n')
        f.write('};\n')



def write_gamepal(path: Path, old_palette: list[int], mapping: list[int], texture_indices: set[int], platform: str) -> None:
    fixed = {0, 255, *range(192, 208)}
    new_rgb = [(0, 0, 0)] * 256
    for old in range(256):
        new = mapping[old]
        new_rgb[new] = tuple(old_palette[old * 3:old * 3 + 3])
    # Texture colors may intentionally be duplicated into the low signed-byte
    # bank after a rare non-texture color was sacrificed to the same entry.
    # Restore texture entries last so renderer texels always match the palette.
    for old in sorted(texture_indices):
        new_rgb[mapping[old]] = tuple(old_palette[old * 3:old * 3 + 3])
    # PC-FX DEBUG_FPS uses SUP palette bank 12 directly; preserve it even when
    # a texture color from that source range was duplicated into the low bank.
    for old in fixed:
        new_rgb[old] = tuple(old_palette[old * 3:old * 3 + 3])
    vals = [rgb_to_pcfx_yuv_word(c) if platform == 'pcfx' else rgb_to_rgb555_word(c) for c in new_rgb]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_console_assets.py. */\n')
        f.write('const unsigned short gamepal[256] = {\n')
        for i in range(0, 256, 8):
            f.write('\t' + ', '.join(f'0x{x:04x}' for x in vals[i:i + 8]))
            if i + 8 < 256:
                f.write(',')
            f.write('\n')
        f.write('};\n\nconst int gamepal_length = 256;\n')

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--platform', choices=['pcfx', 'casloopy'], required=True)
    ap.add_argument('--src', type=Path, default=Path('assets/source'))
    ap.add_argument('--out-root', type=Path, default=Path('assets/generated'))
    ap.add_argument('--map', type=Path, default=Path('tools/texture_low_index_map.txt'))
    ns = ap.parse_args()
    mapping = read_index_map(ns.map)
    out = ns.out_root / ns.platform
    title_im = Image.open(ns.src / 'title.png')
    if title_im.mode != 'P' or title_im.getpalette() is None or len(title_im.getpalette()) < 768:
        raise ValueError('title.png must be an indexed PNG with a 256-entry palette')
    texture_indices = set(load_indexed(ns.src / 'textures.png', 32, 224))
    write_gamepal(out / 'gamepal.h', title_im.getpalette()[:768], mapping, texture_indices, ns.platform)
    write_packed_header(out / 'title.h', 'bg_title', load_indexed(ns.src / 'title.png', 256, 240), mapping)
    write_packed_header(out / 'background.h', 'bg_game', load_indexed(ns.src / 'background2.png', 256, 240), mapping)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
