#!/usr/bin/env python3
"""Generate indexed headless assets from source PNGs.

The headless target renders into an 8-bpp index buffer.  This generator applies
Cascade FX's low-index texture remap to every indexed source asset it uses, then
writes a matching RGB555 palette and packed title/background headers.  That
keeps the framebuffer bytes and the palette coherent for BMP/PNG indexed dumps.
"""
from __future__ import annotations
import argparse
from pathlib import Path
from PIL import Image


def read_index_map(path: Path) -> list[int]:
    mapping = list(range(256))
    seen = set()
    for lineno, line in enumerate(path.read_text().splitlines(), start=1):
        line = line.split('#', 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 2:
            raise ValueError(f"{path}:{lineno}: expected 'old new'")
        old, new = int(parts[0], 0), int(parts[1], 0)
        if not (0 <= old <= 255 and 0 <= new <= 255):
            raise ValueError(f"{path}:{lineno}: palette index out of range")
        mapping[old] = new
        seen.add(old)
    if len(seen) != 256:
        raise ValueError(f"{path}: map must define all 256 entries")
    return mapping


def load_indexed(path: Path, width: int, height: int) -> tuple[Image.Image, list[int], bytes]:
    im = Image.open(path)
    if im.mode != 'P':
        raise ValueError(f"{path}: expected indexed PNG, got {im.mode}")
    if im.size != (width, height):
        raise ValueError(f"{path}: expected {width}x{height}, got {im.size}")
    pal = im.getpalette()
    if pal is None or len(pal) < 768:
        raise ValueError(f"{path}: missing 256-entry palette")
    return im, pal[:768], bytes(im.getdata())


def write_gamepal(path: Path, old_palette: list[int], mapping: list[int], texture_indices: set[int]) -> None:
    # old_palette is RGB888 at old palette indices.  The generated gamepal is
    # RGB555 at remapped indices, matching the remapped frame/title/texture data.
    new_rgb = [(0, 0, 0)] * 256
    for old in range(256):
        new = mapping[old]
        new_rgb[new] = tuple(old_palette[old * 3:old * 3 + 3])
    for old in sorted(texture_indices):
        new_rgb[mapping[old]] = tuple(old_palette[old * 3:old * 3 + 3])
    for old in {0, 255, *range(192, 208)}:
        new_rgb[old] = tuple(old_palette[old * 3:old * 3 + 3])
    vals = []
    for r, g, b in new_rgb:
        vals.append(((r >> 3) << 10) | ((g >> 3) << 5) | (b >> 3))
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_headless_assets.py. */\n')
        f.write('const unsigned short gamepal[256] = {\n')
        for i in range(0, 256, 8):
            f.write('\t' + ', '.join(f'0x{x:04x}' for x in vals[i:i + 8]))
            if i + 8 < 256:
                f.write(',')
            f.write('\n')
        f.write('};\n\nconst int gamepal_length = 256;\n')


def write_packed_header(path: Path, symbol: str, pixels: bytes, mapping: list[int]) -> None:
    if len(pixels) & 1:
        raise ValueError(f"{symbol}: packed image must have even byte count")
    remap = bytes(mapping[p] for p in pixels)
    words = [(remap[i] << 8) | remap[i + 1] for i in range(0, len(remap), 2)]
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_headless_assets.py. */\n')
        f.write(f'const unsigned short {symbol}[{len(words)}] = {{\n')
        for i in range(0, len(words), 8):
            f.write('\t' + ', '.join(f'0x{x:04x}' for x in words[i:i + 8]))
            if i + 8 < len(words):
                f.write(',')
            f.write('\n')
        f.write('};\n')


def write_texture_header(path: Path, pixels: bytes, mapping: list[int]) -> None:
    remap = bytes(mapping[p] for p in pixels)
    if max(remap) >= 128:
        raise ValueError('texture remap did not keep all texels below 128')
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_headless_assets.py. */\n')
        f.write(f'const unsigned char texture[{len(remap)}] = {{\n')
        for i in range(0, len(remap), 16):
            f.write('\t' + ', '.join(f'0x{x:02x}' for x in remap[i:i + 16]))
            if i + 16 < len(remap):
                f.write(',')
            f.write('\n')
        f.write('};\n')



def write_index_map_header(path: Path, mapping: list[int]) -> None:
    with path.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/generate_headless_assets.py. */\n')
        f.write('const unsigned char cfx_palette_index_map[256] = {\n')
        for i in range(0, 256, 16):
            f.write('\t' + ', '.join(f'0x{x:02x}' for x in mapping[i:i + 16]))
            if i + 16 < 256:
                f.write(',')
            f.write('\n')
        f.write('};\n')

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--src', type=Path, default=Path('assets/source'))
    ap.add_argument('--out', type=Path, default=Path('assets/generated/headless'))
    ap.add_argument('--map', type=Path, default=Path('tools/texture_low_index_map.txt'))
    ns = ap.parse_args()
    ns.out.mkdir(parents=True, exist_ok=True)
    mapping = read_index_map(ns.map)
    _title, pal, title_pixels = load_indexed(ns.src / 'title.png', 256, 240)
    _title320, pal320, title320_pixels = load_indexed(ns.src / 'title320.png', 320, 240)
    _background320, pal_bg320, background320_pixels = load_indexed(ns.src / 'background320.png', 320, 240)
    _tex, _texpal, tex_pixels = load_indexed(ns.src / 'textures.png', 32, 224)
    # title320.png is the canonical 320-wide title artwork.  It uses the same
    # palette as the 256-wide title in the original asset set; keep a strict
    # check so the generated indexed output cannot silently mix palettes.
    if pal320 != pal or pal_bg320 != pal:
        raise ValueError('title/background headless PNGs must share the same indexed palette')
    write_gamepal(ns.out / 'gamepal.h', pal320, mapping, set(tex_pixels))
    write_packed_header(ns.out / 'title.h', 'bg_title', title_pixels, mapping)
    write_packed_header(ns.out / 'title320.h', 'bg_title320', title320_pixels, mapping)
    write_packed_header(ns.out / 'background320.h', 'bg_game320', background320_pixels, mapping)
    write_texture_header(ns.out / 'textures.h', tex_pixels, mapping)
    write_index_map_header(ns.out / 'index_map.h', mapping)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
