#include "waifu_pcfx_audio.h"
#include "waifu_pcfx_cdrom.h"

/* cdda_tracks.h is generated by pcfx-cdlink when cddaheader is set.
   It defines CDDA_TRACK_<STEM> constants matching the alphabetical
   order of WAV files found in Music/ (or cdda/).  Fall back to zero
   (silence) for any track that wasn't compiled in. */
#if defined(WAIFU_FM_PCFX) && defined(WAIFU_HAVE_CDDA_TRACKS)
#include "cdda_tracks.h"
#endif

#ifndef CDDA_TRACK_BATTLE
#define CDDA_TRACK_BATTLE 0
#endif
#ifndef CDDA_TRACK_BOSS
#define CDDA_TRACK_BOSS 0
#endif
#ifndef CDDA_TRACK_FINALBOSS
#define CDDA_TRACK_FINALBOSS 0
#endif
#ifndef CDDA_TRACK_OVERWORLD
#define CDDA_TRACK_OVERWORLD 0
#endif
#ifndef CDDA_TRACK_TITLESCREEN_MOONLITCIPHER
#define CDDA_TRACK_TITLESCREEN_MOONLITCIPHER 0
#endif
#ifndef CDDA_TRACK_VICTORY
#define CDDA_TRACK_VICTORY 0
#endif

struct WaifuPcfxAudio {
    WaifuFmMusicTrack current_music; /* last music enum handed to us */
    uint8_t desired_track;           /* CD track we want looping (0 = silent) */
    uint8_t active_track;            /* CD track we last issued a play for */
    uint32_t active_seq;             /* cd-read seq at the moment we started it */
    uint32_t last_read_seq;          /* cd-read seq seen on the previous pump */
};

static WaifuPcfxAudio g_audio;

/* Returns the CD track number for a music enum value, or 0 for silence.
   Track numbers match the alphabetical sort of WAV files in Music/ as
   emitted by pcfx-cdlink into cdda_tracks.h. */
static uint8_t music_to_cdda_track(WaifuFmMusicTrack track)
{
    switch (track) {
    case WAIFU_FM_MUSIC_TITLE:        return CDDA_TRACK_TITLESCREEN_MOONLITCIPHER;
    case WAIFU_FM_MUSIC_OPENING_DREAM:return CDDA_TRACK_OVERWORLD;
    case WAIFU_FM_MUSIC_DECK_EDITOR:  return CDDA_TRACK_OVERWORLD;
    case WAIFU_FM_MUSIC_BOSS:         return CDDA_TRACK_BOSS;
    case WAIFU_FM_MUSIC_FINAL_BOSS:   return CDDA_TRACK_FINALBOSS;
    case WAIFU_FM_MUSIC_RANDOM_BATTLE:return CDDA_TRACK_BATTLE;
    case WAIFU_FM_MUSIC_RESULTS:      return CDDA_TRACK_VICTORY;
    default:                          return 0;
    }
}

WaifuPcfxAudio *waifu_pcfx_audio_create(void)
{
    g_audio.current_music = WAIFU_FM_MUSIC_NONE;
    g_audio.desired_track = 0;
    g_audio.active_track = 0;
    g_audio.active_seq = 0;
    g_audio.last_read_seq = waifu_pcfx_cd_read_seq();
    waifu_pcfx_cdda_set_volume(63, 63);
    return &g_audio;
}

void waifu_pcfx_audio_destroy(WaifuPcfxAudio *audio)
{
    (void)audio;
}

void waifu_pcfx_audio_set_music(WaifuPcfxAudio *audio, WaifuFmMusicTrack track)
{
    if (!audio) return;
    if (audio->current_music == track) return;
    audio->current_music = track;
    /* Record intent only.  The actual SCSI play is issued from the pump once
       any in-flight CD data load has settled, because a data read would stop
       CD-DA again immediately.  This also handles re-arming after a load. */
    audio->desired_track = music_to_cdda_track(track);
}

/* Issue/refresh CD-DA playback to match desired_track, but only when CD reads
   have settled for a frame.  A data read stops the drive's audio engine, so we
   restart the loop whenever a read has happened since we last started it. */
void waifu_pcfx_audio_pump(WaifuPcfxAudio *audio)
{
    uint32_t seq;
    if (!audio) return;

    seq = waifu_pcfx_cd_read_seq();
    if (seq != audio->last_read_seq) {
        /* A CD data load happened during this frame; it has stopped any CD-DA.
           Wait until a frame passes with no further reads before (re)starting,
           so we don't fight an in-progress multi-sector load. */
        audio->last_read_seq = seq;
        return;
    }

    if (audio->desired_track == 0) {
        if (audio->active_track != 0) {
            waifu_pcfx_cdda_stop();
            audio->active_track = 0;
        }
        return;
    }

    /* Start when the track changed, or when a read has interrupted the loop
       since we last issued it (active_seq lags the current read seq).

       The CD-DA end track is EXCLUSIVE: the drive plays from the start track up
       to (not including) the start of the end track.  To play track N in full
       the end position must be the start of track N+1, so pass desired+1.  For
       the final track, N+1 is one past the last track and the drive clamps it
       to the lead-out, i.e. plays to end of disc. */
    if (audio->desired_track != audio->active_track || seq != audio->active_seq) {
        waifu_pcfx_cdda_play(audio->desired_track,
                             (uint8_t)(audio->desired_track + 1), WAIFU_CDDA_LOOP);
        audio->active_track = audio->desired_track;
        audio->active_seq = seq;
    }
}

void waifu_pcfx_audio_stop_all(WaifuPcfxAudio *audio)
{
    if (!audio) return;
    audio->current_music = WAIFU_FM_MUSIC_NONE;
    audio->desired_track = 0;
    audio->active_track = 0;
    waifu_pcfx_cdda_stop();
}
