#include "waifu_pcfx_cdrom.h"
#include "assets.h"

#include <string.h>
#include <eris/cd.h>

/* In CD-ROM builds this header is generated by the fixed vendored
   pcfx-cdlink before the final compile.  Do not guard it with
   __has_include: the old V810 GCC preprocessor does not reliably expose
   that operator, and silently falling back to LBA 0 makes the title/card
   blobs unreadable on hardware/emulator. */
#if defined(WAIFU_ASSET_USE_CDROM) && defined(WAIFU_HAVE_GENERATED_LBAS)
#include "lbas.h"
#endif

#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN
#define BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN
#define BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN 0
#endif

#define PCFX_CD_SECTOR_SIZE 2048u

struct WaifuPcfxCdrom {
    int last_track;
};

static WaifuPcfxCdrom g_cdrom;
static uint8_t g_cd_sector_scratch[PCFX_CD_SECTOR_SIZE] __attribute__((aligned(4)));

static uint32_t blob_lba(WaifuAssetBlobId blob)
{
    switch (blob) {
    case WAIFU_ASSET_BLOB_TITLE_SCREEN:
#if BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN;
#else
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN;
#endif
    case WAIFU_ASSET_BLOB_TITLE_SCREEN_PCFX_YUV16:
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN;
    case WAIFU_ASSET_BLOB_TITLE_SCREEN_PCFX_YUV422:
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN;
    case WAIFU_ASSET_BLOB_STORY_PORTRAITS: return BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN;
    case WAIFU_ASSET_BLOB_STORY_PORTRAIT_MASK: return BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN;
    case WAIFU_ASSET_BLOB_CARD_FACES: return BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN;
    case WAIFU_ASSET_BLOB_CARD_BIG_ART: return BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN;
    case WAIFU_ASSET_BLOB_CARD_BIG_ART_CD: return BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN;
    case WAIFU_ASSET_BLOB_CARD_BACK: return BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_FACE: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_BIG_ART: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_BIG_ART_CD: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN;
    default: return 0;
    }
}

WaifuPcfxCdrom *waifu_pcfx_cdrom_create(void)
{
    g_cdrom.last_track = 0;
    eris_cd_reset();
    return &g_cdrom;
}

void waifu_pcfx_cdrom_destroy(WaifuPcfxCdrom *cdrom)
{
    (void)cdrom;
}

int waifu_pcfx_cdrom_read_asset(WaifuPcfxCdrom *cdrom, WaifuPcfxCdAssetId asset, void *dst, size_t dst_size)
{
    WaifuAssetBlobId blob;
    (void)cdrom;
    switch (asset) {
    case WAIFU_PCFX_CD_ASSET_TITLE: blob = WAIFU_ASSET_BLOB_TITLE_SCREEN; break;
    case WAIFU_PCFX_CD_ASSET_CARD_BANK: blob = WAIFU_ASSET_BLOB_CARD_FACES; break;
    case WAIFU_PCFX_CD_ASSET_STORY_PORTRAITS: blob = WAIFU_ASSET_BLOB_STORY_PORTRAITS; break;
    default: return 0;
    }
    return waifu_assets_platform_read_blob_slice(blob, dst, 0, dst_size);
}

/* Platform hook used by src/game/assets.c in WAIFU_ASSET_USE_CDROM builds.
   The public asset layer remains hardware-agnostic; this module resolves blob
   ids to cdlink LBAs and reads only the requested byte range.  Full-sector
   reads go directly to the destination; unaligned heads/tails use one 2 KiB
   scratch sector. */
int waifu_assets_platform_read_blob_slice(WaifuAssetBlobId blob, void *dst, size_t offset, size_t bytes)
{
    uint32_t base_lba = blob_lba(blob);
    uint8_t *out = (uint8_t *)dst;
    if (!base_lba || !dst) return 0;

    /* Fast path for sector-aligned blobs.  The 112x112 big-art CD blobs are
       padded to 7 whole sectors per card, so a cache miss becomes one SCSI/CD
       transfer into the small RAM art slot instead of seven per-sector calls. */
    if (((offset | bytes) & (PCFX_CD_SECTOR_SIZE - 1u)) == 0) {
        uint32_t lba = base_lba + (uint32_t)(offset / PCFX_CD_SECTOR_SIZE);
        return eris_cd_read(lba, out, (uint32_t)bytes) != 0;
    }

    while (bytes > 0) {
        uint32_t lba = base_lba + (uint32_t)(offset / PCFX_CD_SECTOR_SIZE);
        size_t sector_off = offset & (PCFX_CD_SECTOR_SIZE - 1u);
        if (sector_off == 0 && bytes >= PCFX_CD_SECTOR_SIZE) {
            /* Read every whole sector that remains in ONE multi-sector command
               rather than looping one sector at a time.  Single-sector reads have
               heavy per-command latency on PC-FX CD; the old loop turned a
               ~18 KiB story portrait into ~10 separate reads (and the pixels +
               mask pair into ~20), which is the long Serena-load stall. */
            size_t whole = bytes & ~((size_t)PCFX_CD_SECTOR_SIZE - 1u);
            if (!eris_cd_read(lba, out, (uint32_t)whole)) return 0;
            out += whole;
            offset += whole;
            bytes -= whole;
        } else {
            size_t chunk = PCFX_CD_SECTOR_SIZE - sector_off;
            if (chunk > bytes) chunk = bytes;
            if (!eris_cd_read(lba, g_cd_sector_scratch, PCFX_CD_SECTOR_SIZE)) return 0;
            memcpy(out, g_cd_sector_scratch + sector_off, chunk);
            out += chunk;
            offset += chunk;
            bytes -= chunk;
        }
    }
    return 1;
}

void waifu_pcfx_cdrom_play_cdda_stub(WaifuPcfxCdrom *cdrom, int track, int loop)
{
    if (cdrom) cdrom->last_track = track;
    (void)loop;
}

void waifu_pcfx_cdrom_stop_cdda_stub(WaifuPcfxCdrom *cdrom)
{
    if (cdrom) cdrom->last_track = 0;
}
