#include "waifu_pcfx_cdrom.h"
#include "assets.h"
#include "title_asset.h"
#include "rainbow_bg_assets.h"

#include <string.h>
#include <eris/cd.h>
#include <eris/cdda.h>
#include <eris/scsi.h>
/* Used by the optional ADPCM RAM-load debug path. */
#include "fastking.h"
#include <pcfx/king.h>

#ifndef WAIFU_PCFX_ADPCM_RAM_LOAD
#define WAIFU_PCFX_ADPCM_RAM_LOAD 0
#endif

/* In CD-ROM builds this header is generated by the fixed vendored
   pcfx-cdlink before the final compile.  Do not guard it with
   __has_include: the old V810 GCC preprocessor does not reliably expose
   that operator, and silently falling back to LBA 0 makes the title/card
   blobs unreadable on hardware/emulator. */
#if defined(WAIFU_ASSET_USE_CDROM) && defined(WAIFU_HAVE_GENERATED_LBAS)
#include "lbas.h"
#endif

#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN
#define BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_ENDING_SCREEN_PCFX_YUV422_BIN
#define BINARY_LBA_ASSETS_GENERATED_ENDING_SCREEN_PCFX_YUV422_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN
#define BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN
#define BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN
#define BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN
#define BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_SFX_ADPCM_BIN
#define BINARY_LBA_ASSETS_GENERATED_SFX_ADPCM_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_RAINBOW_DESERT_BIN
#define BINARY_LBA_ASSETS_GENERATED_RAINBOW_DESERT_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_RAINBOW_STONE_BIN
#define BINARY_LBA_ASSETS_GENERATED_RAINBOW_STONE_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_RAINBOW_EMBER_BIN
#define BINARY_LBA_ASSETS_GENERATED_RAINBOW_EMBER_BIN 0
#endif
#ifndef BINARY_LBA_ASSETS_GENERATED_RAINBOW_SKY_BIN
#define BINARY_LBA_ASSETS_GENERATED_RAINBOW_SKY_BIN 0
#endif


#define PCFX_CD_SECTOR_SIZE 2048u

/* KING PageSetting register layout follows the pcfxemu/HuC6272 behavior used
   by the test target.  DMA selects page 1 with bit 0, BG fetches select page 1
   with bit 4, ADPCM selects page 1 with bit 8, and RAINBOW selects page 1
   with bit 12. */
#define WAIFU_PCFX_KRAM_PAGESETTING_SCSI1   0x00000001u
#define WAIFU_PCFX_KRAM_PAGESETTING_BG1     0x00000010u
#define WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1  0x00000100u
#define WAIFU_PCFX_KRAM_PAGESETTING_RAINBOW1 0x00001000u


struct WaifuPcfxCdrom {
    int last_track;
};

static WaifuPcfxCdrom g_cdrom;
static uint8_t g_cd_sector_scratch[PCFX_CD_SECTOR_SIZE] __attribute__((aligned(4)));

static uint32_t blob_lba(WaifuAssetBlobId blob)
{
    switch (blob) {
    case WAIFU_ASSET_BLOB_TITLE_SCREEN:
#if BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_IMG_BIN;
#else
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_IMG_BIN;
#endif
    case WAIFU_ASSET_BLOB_TITLE_SCREEN_PCFX_YUV16:
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV16_BIN;
    case WAIFU_ASSET_BLOB_TITLE_SCREEN_PCFX_YUV422:
        return BINARY_LBA_ASSETS_GENERATED_TITLE_SCREEN_PCFX_YUV422_BIN;
    case WAIFU_ASSET_BLOB_ENDING_SCREEN_PCFX_YUV422:
        return BINARY_LBA_ASSETS_GENERATED_ENDING_SCREEN_PCFX_YUV422_BIN;
    case WAIFU_ASSET_BLOB_STORY_PORTRAITS: return BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAITS_BIN;
    case WAIFU_ASSET_BLOB_STORY_PORTRAIT_MASK: return BINARY_LBA_ASSETS_GENERATED_STORY_PORTRAIT_MASK_BIN;
    case WAIFU_ASSET_BLOB_CARD_FACES: return BINARY_LBA_ASSETS_GENERATED_CARD_FACES_BIN;
    case WAIFU_ASSET_BLOB_CARD_BIG_ART: return BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_BIN;
    case WAIFU_ASSET_BLOB_CARD_BIG_ART_CD: return BINARY_LBA_ASSETS_GENERATED_CARD_BIG_ART_CD_BIN;
    case WAIFU_ASSET_BLOB_CARD_BACK: return BINARY_LBA_ASSETS_GENERATED_CARD_BACK_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_FACE: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_FACE_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_BIG_ART: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_BIN;
    case WAIFU_ASSET_BLOB_SUPPORT_BIG_ART_CD: return BINARY_LBA_ASSETS_GENERATED_SUPPORT_BIG_ART_CD_BIN;
    default: return 0;
    }
}

/* ROOT-CAUSE FIX for the pervasive PC-FX "SCSI freeze" (equip->battle and others).
   The KING chip multiplexes ONE IRQ line to the V810 across CD/SCSI, ADPCM, DMA and
   the raster/vsync interrupt.  The KING SCSI "phase-mismatch" CD interrupt (control
   register 2, bit 1) is left ENABLED by the BIOS boot loader.  liberis does CD reads
   by POLLING and latches the phase-match register (reg 3) to BUS_FREE, so while a
   read walks the command/data-in phases the bus phase != reg3 and CDInterrupt is
   asserted; it normally de-asserts when the bus returns to BUS_FREE, but if a read
   does not drain cleanly it stays asserted.  A stuck CDInterrupt holds the shared
   KING IRQ line high, so the BIOS KING handler never advances the raster/vsync path
   and the BIOS vsync frame counter (RAM 0x1F1E20) stops -- the BIOS "wait for vsync"
   routine (0xfff04c82) then spins forever (verified by BIOS disassembly + the stuck
   EIPC).  The game never uses this interrupt, so clearing reg 2 (bit 1 low) acks the
   stuck CDInterrupt AND disables the mismatch IRQ for good.  Reproduces on hardware. */
static inline void scsi_clear_phase_irq(void)
{
    __asm__ volatile (
        "out.h %[two],0x600[r0]\n"
        "out.h r0,0x604[r0]\n"
        :: [two] "r" (2) : "memory");
}

static inline void king_set_page_setting(uint32_t page_setting)
{
    uint32_t reg;
    __asm__ volatile (
        "movea 15,r0,%[reg]\n"
        "out.h %[reg],0x600[r0]\n"
        "out.w %[ps],0x604[r0]\n"
        : [reg] "=&r" (reg)
        : [ps] "r" (page_setting)
        : "memory");
}

/* A CD data read leaves the drive's CD-DA engine stopped (real hardware and
   emulation both), so every read site reports itself to libpcfx's CD-DA music
   manager, which re-issues playback once the bus has settled.  The counter
   lives in libpcfx now instead of here, so the manager and the reader can
   never disagree about how many reads have happened. */
static void cd_note_read(void)
{
    eris_cdda_notify_cd_read();
}

static uint32_t cd_round_sector_bytes_u32(uint32_t bytes)
{
    return (bytes + (PCFX_CD_SECTOR_SIZE - 1u)) & ~(PCFX_CD_SECTOR_SIZE - 1u);
}

/* The 512x256 affine triple buffer owns page-0 words 0x00000..0x2FFFF.
   Keep CD->RAM DMA in the unused fourth quarter, below physical page 1's
   ADPCM/RAINBOW bank; the old 0x18000 scratch overlapped affine page 1. */
#define WAIFU_PCFX_CD_BOUNCE_KRAM_WORD 0x30000u
#define WAIFU_PCFX_CD_BOUNCE_WORDS     0x4000u   /* 32 KiB (16 sectors) per pass */

#define WAIFU_CD_SPIN_LONG 0x200000u

/* Phase-driven (count-0) CD -> KRAM real-DMA read -- the way commercial PC-FX
   titles read from disc.  Restored verbatim in behaviour from the reader that
   commit 1d5a775 ("Use retail DMA CD readers on PC-FX") deleted; that deletion
   is the head of the chain that black-screens and HANGS this port on a real
   console.  Two independent real-hardware errata rule out every alternative,
   and this shape is the only one immune to both:

     * CPU-driven PIO reads (per-byte manual ACK: eris_cd_read,
       eris_cd_read_kram_pio) are unreliable on real hardware.  pcfxemu models
       this (docs/king-pio-read-erratum.md, ENABLED by default) from a real
       capture, and probe 027 on hardware pins the mechanism: a failed PIO read
       dies so fast that all 8 driver attempts fit in one vblank field, and once
       ONE attempt fails EVERY later one does too -- REQUEST SENSE and seek
       recovery never help, only a full SCSI bus reset restores the bus.  It is
       a poisoned bus, not a per-command error.  So a PIO "fallback" does not
       degrade gracefully: the first time it runs it wedges the drive for the
       rest of the session.  Commit 1e6abcc added exactly that fallback to fix
       the black boot, which is why the console now hangs instead.

     * A COUNT-BOUNDED KING DMA (exact programmed length) trips the KING
       "retire one past the count" erratum and never signals completion.
       eris_cd_read_dma() arms count-bounded chunks for every non-final chunk,
       so any transfer larger than one bounce pass takes that shape -- which is
       most asset blobs here.

   A count-0 transfer is PHASE-DRIVEN: the KING SCSI engine auto-ACKs the whole
   DATA-IN phase in hardware (immune to the CPU-ACK failure) and retires when
   the drive leaves DATA IN rather than on an exact count (immune to the
   retire-past erratum).  It works on real hardware and in both accurate
   emulators.  pcfxemu's own erratum doc records this port, in its pre-1d5a775
   shape, as the homebrew that "loads fine" on real hardware for this reason.

   The caller selects the target KRAM page with king_set_page_setting() first.
   The DMA address register carries NO page bit -- per libpcfx docs/KING_REGS.md
   the engine's target page comes from REG.0F SCP -- so unlike eris_cd_read_kram
   (which self-verifies through the CPU cursor, and therefore needed D31) this
   takes a bare word address.  Returns 1 on GOOD status, 0 otherwise.
   Every loop here is spin-bounded, so a dead drive fails rather than hangs. */
static int cd_dma_read_kram(uint32_t lba, uint32_t kram_addr, uint32_t bytes)
{
    uint8_t cdb[10];
    uint32_t blocks = cd_round_sector_bytes_u32(bytes) >> 11;   /* / 2048 */
    uint32_t spins;
    int reached;

    if (!lba || !blocks) return 0;

    cdb[0] = 0x28;                        /* READ(10) */
    cdb[1] = 0;
    cdb[2] = (uint8_t)(lba >> 24);
    cdb[3] = (uint8_t)(lba >> 16);
    cdb[4] = (uint8_t)(lba >> 8);
    cdb[5] = (uint8_t)lba;
    cdb[6] = 0;
    cdb[7] = (uint8_t)(blocks >> 8);
    cdb[8] = (uint8_t)blocks;
    cdb[9] = 0;

    if (eris_scsi_command(cdb, 10) == (int)SCSI_ERR_TIMEOUT) return 0;

    /* Wait (bounded) for the drive to present DATA IN. */
    reached = 0;
    spins = WAIFU_CD_SPIN_LONG;
    while (spins--) {
        scsi_phase ph = eris_scsi_get_phase();
        if (ph == SCSI_PHASE_DATA_IN) { reached = 1; break; }
        if (ph == SCSI_PHASE_STATUS || ph == SCSI_PHASE_BUS_FREE) break;
    }
    if (!reached) return 0;

    /* Count 0 => phase-driven DMA: it retires when the drive leaves DATA IN.
       Polling the phase register advances the KING DMA (each read runs the
       engine), so the bytes stream into KRAM while we wait here. */
    eris_scsi_begin_dma(kram_addr, 0);
    spins = WAIFU_CD_SPIN_LONG;
    while (spins-- && eris_scsi_get_phase() == SCSI_PHASE_DATA_IN) { }
    eris_scsi_finish_dma();

    /* Consume STATUS. */
    spins = WAIFU_CD_SPIN_LONG;
    while (spins--) {
        scsi_phase ph = eris_scsi_get_phase();
        if (ph == SCSI_PHASE_STATUS)
            return (eris_scsi_status() == SCSI_STATUS_GOOD) ? 1 : 0;
        if (ph == SCSI_PHASE_BUS_FREE)
            return 1;   /* transfer completed and the drive dropped the bus */
    }
    return 0;
}

/* Read CD -> main RAM via the KING real-DMA engine, NOT CPU-PIO.  The DMA can
   only target KRAM, so bounce through the scratch window and CPU-copy KRAM ->
   RAM (word reads through the KING data port, which never touch the failing
   CPU-ACK path). */
static uint32_t cd_read(uint32_t lba, uint8_t *buf, uint32_t bytes)
{
    uint32_t total = cd_round_sector_bytes_u32(bytes);
    uint32_t done = 0;

    if (!lba || !bytes) return 0;

    /* Route the SCSI DMA to KRAM physical page 0 (no SCSI page-1 bit); keep
       ADPCM fetching from page 1 as elsewhere. */
    king_set_page_setting(WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1);

    while (done < total) {
        uint32_t pass_bytes = total - done;
        uint32_t pass_words;
        uint32_t i;
        if (pass_bytes > WAIFU_PCFX_CD_BOUNCE_WORDS * 2u)
            pass_bytes = WAIFU_PCFX_CD_BOUNCE_WORDS * 2u;
        pass_words = pass_bytes >> 1;

        if (!cd_dma_read_kram(lba + (done / PCFX_CD_SECTOR_SIZE),
                              WAIFU_PCFX_CD_BOUNCE_KRAM_WORD, pass_bytes)) {
            scsi_clear_phase_irq();
            cd_note_read();
            return 0;
        }

        /* Copy the DMAed words out of the scratch into RAM (little endian:
           low byte first, matching eris_cd_read_kram's packing). */
        king_set_kram_read(WAIFU_PCFX_CD_BOUNCE_KRAM_WORD, 1);
        for (i = 0; i < pass_words; i++) {
            uint16_t w = king_kram_read();
            buf[done + i * 2u]      = (uint8_t)(w & 0xffu);
            buf[done + i * 2u + 1u] = (uint8_t)(w >> 8);
        }
        done += pass_bytes;
    }

    scsi_clear_phase_irq();
    cd_note_read();
    return bytes;
}

/* Direct CD->KRAM read.  One phase-driven KING SCSI DMA for the whole transfer
   (see cd_dma_read_kram).  page_bit selects KRAM physical page 1 through REG.0F
   SCP; it is deliberately NOT OR'd into the DMA address, which has no page
   field.  dma_only is retained for call-site clarity -- there is no longer any
   non-DMA path to forbid, but the RAINBOW streams genuinely require the SCSI
   DMA engine (the HuC6271 decoder does not accept data delivered through the
   CPU KRAM write port), so the flag documents that requirement at the seam. */
static int cd_dma_read_to_kram(uint32_t lba, uint32_t kram_addr, uint32_t bytes,
                               uint32_t page_bit, int dma_only)
{
    uint32_t size = cd_round_sector_bytes_u32(bytes);
    int ok;
    (void)dma_only;
    if (!lba || !bytes) return 0;

    king_set_page_setting((page_bit ? WAIFU_PCFX_KRAM_PAGESETTING_SCSI1 : 0u)
                          | WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1);

    ok = cd_dma_read_kram(lba, kram_addr, size);

    scsi_clear_phase_irq();
    cd_note_read();
    return ok;
}

static int cd_read_kram_on_page(uint32_t lba, uint32_t kram_addr, uint32_t bytes, int scsi_page1)
{
    int r;
    if (!lba || !bytes) return 0;

    r = cd_dma_read_to_kram(lba, kram_addr, bytes, scsi_page1 ? 0x80000000u : 0u, 0);
    /* Leave ADPCM fetching from physical page 1; video will OR this bit into
       its BG page flips as well. */
    king_set_page_setting(WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1);
    return r;
}

static int cd_read_kram_with_page_setting(uint32_t lba, uint32_t kram_addr, uint32_t bytes,
                                          uint32_t dma_page_setting, uint32_t restore_page_setting,
                                          int dma_only)
{
    int r;
    uint32_t page_bit;
    if (!lba || !bytes) return 0;

    /* Route the DMA to the requested physical KRAM page. */
    page_bit = (dma_page_setting & WAIFU_PCFX_KRAM_PAGESETTING_SCSI1) ? 0x80000000u : 0u;
    r = cd_dma_read_to_kram(lba, kram_addr, bytes, page_bit, dma_only);
    king_set_page_setting(restore_page_setting);
    return r;
}

static int cd_read_kram(uint32_t lba, uint32_t kram_addr, uint32_t bytes)
{
    return cd_read_kram_on_page(lba, kram_addr, bytes, 0);
}

int waifu_pcfx_cdrom_read_title_yuv422_to_kram(uint32_t kram_addr, size_t bytes)
{
    uint32_t base_lba = blob_lba(WAIFU_ASSET_BLOB_TITLE_SCREEN_PCFX_YUV422);
    if (!base_lba) return 0;
    if (bytes == 0) bytes = (size_t)TITLE_SCREEN_W * 256u * 2u;
    return cd_read_kram(base_lba, kram_addr, (uint32_t)bytes);
}

int waifu_pcfx_cdrom_read_ending_yuv422_to_kram(uint32_t kram_addr, size_t bytes)
{
    uint32_t base_lba = blob_lba(WAIFU_ASSET_BLOB_ENDING_SCREEN_PCFX_YUV422);
    if (!base_lba) return 0;
    if (bytes == 0) bytes = (size_t)TITLE_SCREEN_W * 256u * 2u;
    return cd_read_kram(base_lba, kram_addr, (uint32_t)bytes);
}

int waifu_pcfx_cdrom_read_sfx_adpcm_to_kram(uint32_t kram_addr, size_t bytes)
{
#if WAIFU_PCFX_ADPCM_RAM_LOAD
    uint32_t remaining;
    uint32_t lba;
    uint32_t word_addr;
#endif
    if (!BINARY_LBA_ASSETS_GENERATED_SFX_ADPCM_BIN || bytes == 0) return 0;

#if WAIFU_PCFX_ADPCM_RAM_LOAD
    /* Optional debug fallback: CD -> RAM scratch -> KING KRAM write.
       The normal path below uses direct CD->KRAM DMA and is the shipping path. */
    remaining = cd_round_sector_bytes_u32((uint32_t)bytes);
    lba = BINARY_LBA_ASSETS_GENERATED_SFX_ADPCM_BIN;
    word_addr = kram_addr;
    king_set_page_setting(WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1);
    while (remaining) {
        uint32_t chunk = remaining > PCFX_CD_SECTOR_SIZE ? PCFX_CD_SECTOR_SIZE : remaining;
        cd_read(lba, g_cd_sector_scratch, PCFX_CD_SECTOR_SIZE);
        king_set_kram_write(0x80000000u | word_addr, 1);
        king_kram_write_buffer(g_cd_sector_scratch, (int)chunk);
        word_addr += chunk >> 1;
        remaining -= chunk;
        ++lba;
    }
    king_set_page_setting(WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1);
    return 1;
#else
    /* ADPCM samples live on KING physical page 1. */
    return cd_read_kram_on_page(BINARY_LBA_ASSETS_GENERATED_SFX_ADPCM_BIN,
                                kram_addr, (uint32_t)bytes, 1);
#endif
}

int waifu_pcfx_cdrom_read_rainbow_bg_to_kram(WaifuPcfxRainbowBgAsset asset, uint32_t kram_addr, size_t bytes)
{
    uint32_t lba = 0;
    switch (asset) {
    case WAIFU_PCFX_RAINBOW_BG_STONE:
        lba = BINARY_LBA_ASSETS_GENERATED_RAINBOW_STONE_BIN;
        if (bytes == 0) bytes = WAIFU_PCFX_RAINBOW_STONE_BYTES;
        break;
    case WAIFU_PCFX_RAINBOW_BG_EMBER:
        lba = BINARY_LBA_ASSETS_GENERATED_RAINBOW_EMBER_BIN;
        if (bytes == 0) bytes = WAIFU_PCFX_RAINBOW_EMBER_BYTES;
        break;
    case WAIFU_PCFX_RAINBOW_BG_SKY:
        lba = BINARY_LBA_ASSETS_GENERATED_RAINBOW_SKY_BIN;
        if (bytes == 0) bytes = WAIFU_PCFX_RAINBOW_SKY_BYTES;
        break;
    case WAIFU_PCFX_RAINBOW_BG_DESERT:
    default:
        lba = BINARY_LBA_ASSETS_GENERATED_RAINBOW_DESERT_BIN;
        if (bytes == 0) bytes = WAIFU_PCFX_RAINBOW_DESERT_BYTES;
        break;
    }
    return cd_read_kram_with_page_setting(
        lba,
        kram_addr,
        (uint32_t)bytes,
        WAIFU_PCFX_KRAM_PAGESETTING_SCSI1 | WAIFU_PCFX_KRAM_PAGESETTING_RAINBOW1 | WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1,
        WAIFU_PCFX_KRAM_PAGESETTING_RAINBOW1 | WAIFU_PCFX_KRAM_PAGESETTING_ADPCM1,
        1 /* DMA only: the HuC6271 never sees CPU-PIO KRAM writes */);
}

WaifuPcfxCdrom *waifu_pcfx_cdrom_create(void)
{
    g_cdrom.last_track = 0;
    eris_cd_reset();
    scsi_clear_phase_irq();
    return &g_cdrom;
}

void waifu_pcfx_cdrom_destroy(WaifuPcfxCdrom *cdrom)
{
    (void)cdrom;
}

int waifu_pcfx_cdrom_read_asset(WaifuPcfxCdrom *cdrom, WaifuPcfxCdAssetId asset, void *dst, size_t dst_size)
{
    WaifuAssetBlobId blob;
    (void)cdrom;
    switch (asset) {
    case WAIFU_PCFX_CD_ASSET_TITLE: blob = WAIFU_ASSET_BLOB_TITLE_SCREEN; break;
    case WAIFU_PCFX_CD_ASSET_CARD_BANK: blob = WAIFU_ASSET_BLOB_CARD_FACES; break;
    case WAIFU_PCFX_CD_ASSET_STORY_PORTRAITS: blob = WAIFU_ASSET_BLOB_STORY_PORTRAITS; break;
    default: return 0;
    }
    return waifu_assets_platform_read_blob_slice(blob, dst, 0, dst_size);
}

/* Platform hook used by src/game/assets.c in WAIFU_ASSET_USE_CDROM builds.
   The public asset layer remains hardware-agnostic; this module resolves blob
   ids to cdlink LBAs and reads only the requested byte range.  Full-sector
   reads go directly to the destination; unaligned heads/tails use one 2 KiB
   scratch sector. */
int waifu_assets_platform_read_blob_slice(WaifuAssetBlobId blob, void *dst, size_t offset, size_t bytes)
{
    uint32_t base_lba = blob_lba(blob);
    uint8_t *out = (uint8_t *)dst;
    if (!base_lba || !dst) return 0;

    /* Fast path for sector-aligned blobs.  The 112x112 big-art CD blobs are
       padded to 7 whole sectors per card, so a cache miss becomes one SCSI/CD
       transfer into the small RAM art slot instead of seven per-sector calls. */
    if (((offset | bytes) & (PCFX_CD_SECTOR_SIZE - 1u)) == 0) {
        uint32_t lba = base_lba + (uint32_t)(offset / PCFX_CD_SECTOR_SIZE);
        return cd_read(lba, out, (uint32_t)bytes) != 0;
    }

    while (bytes > 0) {
        uint32_t lba = base_lba + (uint32_t)(offset / PCFX_CD_SECTOR_SIZE);
        size_t sector_off = offset & (PCFX_CD_SECTOR_SIZE - 1u);
        if (sector_off == 0 && bytes >= PCFX_CD_SECTOR_SIZE) {
            /* Read every whole sector that remains in ONE multi-sector command
               rather than looping one sector at a time.  Single-sector reads have
               heavy per-command latency on PC-FX CD; the old loop turned a
               ~18 KiB story portrait into ~10 separate reads (and the pixels +
               mask pair into ~20), which is the long Serena-load stall. */
            size_t whole = bytes & ~((size_t)PCFX_CD_SECTOR_SIZE - 1u);
            if (!cd_read(lba, out, (uint32_t)whole)) return 0;
            out += whole;
            offset += whole;
            bytes -= whole;
        } else {
            size_t chunk = PCFX_CD_SECTOR_SIZE - sector_off;
            if (chunk > bytes) chunk = bytes;
            if (!cd_read(lba, g_cd_sector_scratch, PCFX_CD_SECTOR_SIZE)) return 0;
            memcpy(out, g_cd_sector_scratch + sector_off, chunk);
            out += chunk;
            offset += chunk;
            bytes -= chunk;
        }
    }
    return 1;
}

/* CD-DA is issued by libpcfx (eris/cdda.h), not from here.
 *
 * This file used to carry its own D8/D9/DA command layer, and every one of its
 * differences from libpcfx's is a reason the music did not play on a real
 * console (it all worked in emulation, which is why it survived this long):
 *
 *   * It started playback with D8 mode 0 (seek, stay paused) and relied on the
 *     following D9 to actually start the audio.  D8 returns GOOD as soon as the
 *     command is accepted and then the head seeks -- and a music change here
 *     always follows an asset load, so the head is somewhere in the data track
 *     and that seek is long.  The D9 lands mid-seek, the drive answers BUSY,
 *     and BUSY in SCSI means the command was NOT executed: no end position, no
 *     mode, drive parked at the start position forever.  libpcfx plays with a
 *     single D8 carrying mode 1 (CDDA_SAPSP_PLAY) -- what the PC-FX BIOS's own
 *     CD player sends -- which cannot be refused halfway through its own seek,
 *     and defers the bounding D9 to later frames where a refusal is free.
 *   * It put track numbers on the bus as plain binary.  The drive parses cdb[2]
 *     in track-address mode as BCD, so anything above track 9 is either an
 *     invalid nibble (CHECK CONDITION) or addresses the wrong track.  This disc
 *     has more than nine CD-DA tracks, so several songs could never play.
 *   * Its eris_scsi_command()/eris_scsi_status() sequences ran unguarded.  Those
 *     are KING 0x600/0x604 register-select/data pairs; an interval-timer IRQ
 *     landing between the halves corrupts them on silicon (it cannot in the
 *     emulator, which has no such window).
 *   * It ended the PLAY path with a MODE-register write (scsi_clear_phase_irq),
 *     touching the bus again just as the drive started streaming audio.  That
 *     write belongs on the stop path only.
 *
 * The audio layer now drives eris_cdda_music_* directly, which also owns the
 * settle/retry policy around loads. */
