#include "waifu_pcfx_audio.h"
#include "waifu_pcfx_cdrom.h"
#include "pcfx_sfx_adpcm.h"
#include "sounds.h"

#include <eris/types.h>
#include <eris/low/soundbox.h>
#include <stdint.h>

/* cdda_tracks.h is generated by pcfx-cdlink when cddaheader is set.
   It defines CDDA_TRACK_<STEM> constants matching the alphabetical
   order of WAV files found in Music/ (or cdda/).  Fall back to zero
   (silence) for any track that wasn't compiled in. */
#if defined(WAIFU_FM_PCFX) && defined(WAIFU_HAVE_CDDA_TRACKS)
#include "cdda_tracks.h"
#endif

#ifndef CDDA_TRACK_BATTLE
#define CDDA_TRACK_BATTLE 0
#endif
#ifndef CDDA_TRACK_BOSS
#define CDDA_TRACK_BOSS 0
#endif
#ifndef CDDA_TRACK_FINALBOSS
#define CDDA_TRACK_FINALBOSS 0
#endif
#ifndef CDDA_TRACK_OVERWORLD
#define CDDA_TRACK_OVERWORLD 0
#endif
#ifndef CDDA_TRACK_TITLESCREEN_MOONLITCIPHER
#define CDDA_TRACK_TITLESCREEN_MOONLITCIPHER 0
#endif
#ifndef CDDA_TRACK_VICTORY
#define CDDA_TRACK_VICTORY 0
#endif
#ifndef CDDA_TRACK_YOULOST
#define CDDA_TRACK_YOULOST 0
#endif

struct WaifuPcfxAudio {
    WaifuFmMusicTrack current_music; /* last music enum handed to us */
    uint8_t desired_track;           /* CD track we want (0 = silent) */
    uint8_t desired_loop;            /* WAIFU_CDDA_LOOP for looping music, 0 for one-shot */
    uint8_t active_track;            /* CD track we last issued a play for */
    uint8_t active_loop;             /* loop mode of the active play command */
    uint32_t active_seq;             /* cd-read seq at the moment we started it */
    uint32_t last_read_seq;          /* cd-read seq seen on the previous pump */
    uint8_t silence_stop_frames;     /* force STOP briefly after entering silence */
};

static WaifuPcfxAudio g_audio;

#define WAIFU_PCFX_CDDA_BASE_VOLUME 56u   /* Slight music trim; 63 is full-scale. */
#define WAIFU_PCFX_CDDA_DUCK_VOLUME 38u   /* Temporary SFX duck, not a global music cut. */
#define WAIFU_PCFX_CDDA_DUCK_SHORT 24u
#define WAIFU_PCFX_CDDA_DUCK_LONG  58u
static uint8_t g_cdda_mix_volume = 255u;
static uint8_t g_cdda_duck_frames = 0u;
static uint8_t g_turn_jingle_guard_frames = 0u;

static void waifu_pcfx_cdda_apply_mix_volume(uint8_t volume)
{
    if (g_cdda_mix_volume == volume) return;
    waifu_pcfx_cdda_set_volume(volume, volume);
    g_cdda_mix_volume = volume;
}

static void waifu_pcfx_cdda_request_duck(uint8_t frames)
{
    if (frames > g_cdda_duck_frames) g_cdda_duck_frames = frames;
}

static void waifu_pcfx_cdda_pump_mix_volume(void)
{
    uint8_t target = g_cdda_duck_frames ? WAIFU_PCFX_CDDA_DUCK_VOLUME : WAIFU_PCFX_CDDA_BASE_VOLUME;
    waifu_pcfx_cdda_apply_mix_volume(target);
    if (g_cdda_duck_frames) --g_cdda_duck_frames;
    if (g_turn_jingle_guard_frames) --g_turn_jingle_guard_frames;
}

/* PC-FX game SFX now use the SoundBox PSG directly.  This is the same
   six-channel HuC6230/PCE-family PSG exposed by liberis: 32x5-bit custom
   waveform channels, per-channel period/balance/volume, and noise on the last
   two channels.  CD-DA music remains on the drive mixer, and the ADPCM helpers
   below are intentionally retained for future voice/dialogue playback. */
#define WAIFU_PCFX_PSG_CHANNELS 6
#define WAIFU_PCFX_PSG_SFX_VOICES 6
#define WAIFU_PCFX_PSG_CLOCK_DIV32 111875u /* 3.58 MHz / 32, matching liberis docs. */

typedef enum WaifuPcfxPsgWaveId {
    PSG_WAVE_SQUARE = 0,
    PSG_WAVE_PULSE,
    PSG_WAVE_TRIANGLE,
    PSG_WAVE_SOFT,
    PSG_WAVE_SAW,
    PSG_WAVE_PLUCK,
    PSG_WAVE_BELL,
    PSG_WAVE_METAL,
    PSG_WAVE_THIN
} WaifuPcfxPsgWaveId;

#define PSG_STEP_NOISE 0x01u

typedef struct WaifuPcfxPsgStep {
    uint8_t wave_id;
    uint8_t flags;
    uint8_t duration;
    uint8_t vol0;
    uint8_t vol1;
    uint8_t pan_l;
    uint8_t pan_r;
    uint16_t hz0;
    uint16_t hz1;
    uint8_t noise0;
    uint8_t noise1;
} WaifuPcfxPsgStep;

typedef struct WaifuPcfxPsgVoice {
    uint8_t active;
    uint8_t channel;
    uint8_t frame;
    uint8_t step_index;
    uint8_t step_count;
    uint8_t loaded_wave;
    const WaifuPcfxPsgStep *steps;
    uint8_t duration;
    uint8_t volume0;
    uint8_t volume1;
    uint8_t pan_l;
    uint8_t pan_r;
    uint8_t noise;
    uint8_t noise0;
    uint8_t noise1;
    uint16_t age;
    uint16_t max_age;
    uint16_t period0;
    uint16_t period1;
} WaifuPcfxPsgVoice;

static WaifuPcfxPsgVoice g_psg_voices[WAIFU_PCFX_PSG_SFX_VOICES];
static uint8_t g_psg_off_guard[WAIFU_PCFX_PSG_CHANNELS];
static int g_adpcm_loaded = 0;

static const uint8_t g_psg_wave_square[32] = {
    31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
static const uint8_t g_psg_wave_pulse[32] = {
    31,31,31,31,31,31, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};
static const uint8_t g_psg_wave_triangle[32] = {
     0, 2, 4, 6, 8,10,12,14,16,18,20,22,24,26,28,30,
    31,29,27,25,23,21,19,17,15,13,11, 9, 7, 5, 3, 1
};
static const uint8_t g_psg_wave_soft[32] = {
    16,18,20,22,24,25,26,27,28,28,27,26,25,24,22,20,
    18,16,14,12,10, 8, 7, 6, 5, 4, 4, 5, 7, 9,12,14
};
static const uint8_t g_psg_wave_saw[32] = {
     0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12,13,14,15,
    16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31
};
/* Extra PSG-only timbres for card-game effects.  These are handcrafted 5-bit
   waveforms, not decoded samples: short pluck, glass/bell partials, a harsher
   metal wave, and a thin click wave for menu transients. */
static const uint8_t g_psg_wave_pluck[32] = {
    16,25,31,28,20,11, 4, 2, 5,12,20,25,24,18,10, 5,
     3, 6,12,18,20,17,11, 6, 4, 6,10,14,15,13,10, 8
};
static const uint8_t g_psg_wave_bell[32] = {
    16,29,24, 8, 2,12,27,31,19, 5, 6,22,30,25,10, 1,
    14,28,26,11, 3, 9,23,31,21, 7, 4,18,29,27,13, 5
};
static const uint8_t g_psg_wave_metal[32] = {
    31, 3,24, 6,29,12,18, 1,27, 8,21, 5,30,10,16, 0,
    25, 4,20, 7,28,13,15, 2,23, 9,19, 6,26,11,17, 1
};
static const uint8_t g_psg_wave_thin[32] = {
    31,31, 0, 0,24,24, 0, 0,16,16, 0, 0, 8, 8, 0, 0,
    31, 0,24, 0,16, 0, 8, 0, 4, 0, 2, 0, 1, 0, 0, 0
};

static const uint8_t *psg_wave_ptr(uint8_t wave_id)
{
    switch ((WaifuPcfxPsgWaveId)wave_id) {
    case PSG_WAVE_PULSE:    return g_psg_wave_pulse;
    case PSG_WAVE_TRIANGLE: return g_psg_wave_triangle;
    case PSG_WAVE_SOFT:     return g_psg_wave_soft;
    case PSG_WAVE_SAW:      return g_psg_wave_saw;
    case PSG_WAVE_PLUCK:    return g_psg_wave_pluck;
    case PSG_WAVE_BELL:     return g_psg_wave_bell;
    case PSG_WAVE_METAL:    return g_psg_wave_metal;
    case PSG_WAVE_THIN:     return g_psg_wave_thin;
    case PSG_WAVE_SQUARE:
    default:                return g_psg_wave_square;
    }
}

static uint16_t psg_period_from_hz(uint16_t hz)
{
    uint32_t p;
    if (hz == 0) return 0;
    p = (WAIFU_PCFX_PSG_CLOCK_DIV32 + (uint32_t)hz / 2u) / (uint32_t)hz;
    if (p < 1u) p = 1u;
    if (p > 0x0FFFu) p = 0x0FFFu;
    return (uint16_t)p;
}

static uint16_t lerp_u16(uint16_t a, uint16_t b, uint8_t frame, uint8_t duration)
{
    int32_t d;
    if (duration <= 1) return b;
    d = (int32_t)b - (int32_t)a;
    return (uint16_t)((int32_t)a + (d * (int32_t)frame) / (int32_t)(duration - 1u));
}

static uint8_t lerp_u8(uint8_t a, uint8_t b, uint8_t frame, uint8_t duration)
{
    int d;
    if (duration <= 1) return b;
    d = (int)b - (int)a;
    return (uint8_t)((int)a + (d * (int)frame) / (int)(duration - 1u));
}

static void psg_channel_off(uint8_t ch)
{
    if (ch >= WAIFU_PCFX_PSG_CHANNELS) return;
    eris_low_psg_set_channel(ch);
    eris_low_psg_set_noise(0, 0);
    eris_low_psg_set_freq(0);
    eris_low_psg_set_balance(0, 0);
    eris_low_psg_set_volume(0, 0, 0);
    g_psg_off_guard[ch] = 4u;
}

static void psg_load_wave(uint8_t ch, const uint8_t *wave)
{
    int i;
    eris_low_psg_set_channel(ch);
    eris_low_psg_set_volume(0, 0, 0);
    eris_low_psg_set_noise(0, 0);
    for (i = 0; i < 32; ++i) eris_low_psg_waveform_data((uint8_t)(wave[i] & 31u));
}

#define PSG_TONE(w,d,h0,h1,v0,v1,l,r) \
    { (uint8_t)(w), 0, (uint8_t)(d), (uint8_t)(v0), (uint8_t)(v1), (uint8_t)(l), (uint8_t)(r), (uint16_t)(h0), (uint16_t)(h1), 0, 0 }
#define PSG_NOISE(d,n0,n1,v0,v1,l,r) \
    { PSG_WAVE_SQUARE, PSG_STEP_NOISE, (uint8_t)(d), (uint8_t)(v0), (uint8_t)(v1), (uint8_t)(l), (uint8_t)(r), 0, 0, (uint8_t)(n0), (uint8_t)(n1) }
#define PSG_COUNT(a) ((uint8_t)(sizeof(a) / sizeof((a)[0])))

/* Menu and card effects: PSG-only recreations based on envelope/timbre inspection
   of the supplied reference clips.  No PCM is embedded: the tables below are
   short tone/noise scripts using the SoundBox 32x5-bit wave channels. */
static const WaifuPcfxPsgStep g_sfx_select_a[] = {
    PSG_TONE(PSG_WAVE_THIN, 2, 2600, 2200, 18, 9, 13, 15),
    PSG_TONE(PSG_WAVE_THIN, 3, 1800, 1500, 9, 0,  13, 15)
};
static const WaifuPcfxPsgStep g_sfx_select_b[] = {
    PSG_TONE(PSG_WAVE_SOFT, 4, 3900, 3100, 8, 0, 15, 12)
};

/* sfx_037-style title confirm: bright multi-tap transient, short metallic
   body, and a small high tail. */
static const WaifuPcfxPsgStep g_sfx_confirm_a[] = {
    PSG_TONE(PSG_WAVE_THIN,  2, 3150, 2750, 23, 19, 15, 13),
    PSG_TONE(PSG_WAVE_BELL,  5, 2200, 1620, 19, 15, 15, 13),
    PSG_TONE(PSG_WAVE_PLUCK, 7, 1320,  990, 14, 6,  15, 13),
    PSG_TONE(PSG_WAVE_BELL,  8, 2640, 1800, 7,  0,  15, 13)
};
static const WaifuPcfxPsgStep g_sfx_confirm_b[] = {
    PSG_TONE(PSG_WAVE_METAL, 3, 4200, 3180, 13, 9,  11, 15),
    PSG_TONE(PSG_WAVE_SOFT,  7, 1100,  820, 10, 4,  11, 15),
    PSG_TONE(PSG_WAVE_THIN,  8, 3600, 2400, 5,  0,  11, 15)
};

/* sfx_038-style RUN/exit: quick high attack plus low falling body. */
static const WaifuPcfxPsgStep g_sfx_cancel_a[] = {
    PSG_TONE(PSG_WAVE_THIN,     2, 5510, 4300, 22, 15, 13, 13),
    PSG_TONE(PSG_WAVE_TRIANGLE, 7,  390,  250, 17, 11, 13, 13),
    PSG_TONE(PSG_WAVE_SOFT,    10,  250,  165, 11, 0,  13, 13)
};
static const WaifuPcfxPsgStep g_sfx_cancel_b[] = {
    PSG_TONE(PSG_WAVE_PULSE,    3, 2600, 1700, 12, 7,  10, 15),
    PSG_TONE(PSG_WAVE_METAL,    8,  780,  330, 9,  0,  10, 15)
};

static const WaifuPcfxPsgStep g_sfx_card_place_thump[] = {
    PSG_TONE(PSG_WAVE_PLUCK, 1, 740, 420, 29, 24, 15, 15),
    PSG_TONE(PSG_WAVE_PULSE, 3, 360, 190, 24, 9,  15, 15),
    PSG_TONE(PSG_WAVE_SOFT,  4, 190, 120, 9,  0,  15, 15)
};
static const WaifuPcfxPsgStep g_sfx_card_place_air[] = {
    PSG_NOISE(1, 2,  7,  26, 20, 15, 14),
    PSG_NOISE(3, 7, 16,  20, 6,  15, 14),
    PSG_NOISE(3, 16, 25, 6,  0,  15, 14)
};
static const WaifuPcfxPsgStep g_sfx_card_place_spark[] = {
    PSG_TONE(PSG_WAVE_THIN, 1, 2100, 2500, 16, 12, 11, 15),
    PSG_TONE(PSG_WAVE_BELL, 3, 3150, 2400, 12, 5,  11, 15),
    PSG_TONE(PSG_WAVE_BELL, 4, 4200, 3300, 5,  0,  11, 15)
};

/* sfx_039-style card draw: paper scrape/noise attack, high flutter, then a
   short rising card glint.  This is intentionally hot in the mix: the prior
   table was technically present but masked by CD-DA. */
static const WaifuPcfxPsgStep g_sfx_card_draw_noise_a[] = {
    PSG_NOISE(2,  1,  6, 31, 29, 15, 15),
    PSG_NOISE(5,  6, 18, 29, 14, 15, 15),
    PSG_NOISE(5, 18, 29, 14,  0, 15, 15)
};
static const WaifuPcfxPsgStep g_sfx_card_draw_noise_b[] = {
    PSG_NOISE(2,  4, 10, 27, 23, 10, 15),
    PSG_NOISE(4, 10, 24, 23,  7, 10, 15),
    PSG_NOISE(4, 24, 14,  7,  0, 10, 15)
};
static const WaifuPcfxPsgStep g_sfx_card_draw_tone[] = {
    PSG_TONE(PSG_WAVE_THIN,  2, 3400, 4300, 26, 21, 15, 11),
    PSG_TONE(PSG_WAVE_PLUCK, 4, 1800, 2450, 21, 13, 15, 11),
    PSG_TONE(PSG_WAVE_BELL,  7, 2600, 3900, 13,  0, 15, 11)
};
static const WaifuPcfxPsgStep g_sfx_card_draw_tone_b[] = {
    PSG_TONE(PSG_WAVE_METAL, 2, 1180, 1580, 22, 17, 11, 15),
    PSG_TONE(PSG_WAVE_THIN,  4, 2360, 3180, 17,  8, 11, 15),
    PSG_TONE(PSG_WAVE_BELL,  7, 4720, 3600, 8,   0, 11, 15)
};
static const WaifuPcfxPsgStep g_sfx_card_draw_tail[] = {
    PSG_TONE(PSG_WAVE_BELL,  5, 3920, 3300, 20, 10, 10, 15),
    PSG_TONE(PSG_WAVE_SOFT, 10, 1960, 1560, 10,  0, 10, 15)
};

/* Explosion: triggered exactly on the first flame frame. */
static const WaifuPcfxPsgStep g_sfx_card_destroy_noise[] = {
    PSG_NOISE(2,  1,  6,  31, 29, 15, 15),
    PSG_NOISE(5,  6, 18,  29, 19, 15, 15),
    PSG_NOISE(10, 18, 28, 19, 6,  15, 15),
    PSG_NOISE(10, 28, 10, 6,  0,  15, 15)
};
static const WaifuPcfxPsgStep g_sfx_card_destroy_tone[] = {
    PSG_TONE(PSG_WAVE_PULSE,  2, 170, 120, 25, 22, 15, 15),
    PSG_TONE(PSG_WAVE_METAL,  6, 620, 240, 22, 11, 15, 12),
    PSG_TONE(PSG_WAVE_SAW,   12, 240,  86, 11, 0,  15, 12)
};
static const WaifuPcfxPsgStep g_sfx_card_destroy_shard[] = {
    PSG_TONE(PSG_WAVE_BELL,  3, 3400, 2500, 12, 8,  9,  15),
    PSG_TONE(PSG_WAVE_METAL, 7, 2500, 1200, 8,  0,  9,  15)
};

/* Slash/impact: PSG-only sword-style whoosh plus metal hit, replacing the old
   laser-like direct-attack transient. */
static const WaifuPcfxPsgStep g_sfx_laser_main[] = {
    PSG_TONE(PSG_WAVE_METAL, 2, 3200, 2100, 18, 16, 15, 12),
    PSG_TONE(PSG_WAVE_SAW,   5, 1900,  620, 24, 13, 15, 12),
    PSG_TONE(PSG_WAVE_PULSE, 5,  240,  150, 13,  0, 15, 12)
};
static const WaifuPcfxPsgStep g_sfx_laser_side[] = {
    PSG_TONE(PSG_WAVE_THIN,  2, 5200, 3600, 20, 12,  9, 15),
    PSG_TONE(PSG_WAVE_METAL, 4, 2600,  980, 12,  5,  9, 15),
    PSG_TONE(PSG_WAVE_BELL,  6, 1800,  720,  5,  0,  9, 15)
};
static const WaifuPcfxPsgStep g_sfx_laser_noise[] = {
    PSG_NOISE(2,  1, 10,  28, 22, 15, 11),
    PSG_NOISE(5, 10, 27,  22,  0, 15, 11)
};

static const WaifuPcfxPsgStep g_sfx_direct_hit_tone[] = {
    PSG_TONE(PSG_WAVE_METAL, 1, 4200, 2600, 31, 24, 15, 15),
    PSG_TONE(PSG_WAVE_PULSE, 3,  220,  150, 28, 17, 15, 15),
    PSG_TONE(PSG_WAVE_SAW,   6,  760,  210, 17, 0,  15, 15)
};
static const WaifuPcfxPsgStep g_sfx_direct_hit_noise[] = {
    PSG_NOISE(1,  1,  7,  31, 27, 15, 15),
    PSG_NOISE(5,  7, 24,  27, 0,  15, 15)
};
static const WaifuPcfxPsgStep g_sfx_direct_hit_spark[] = {
    PSG_TONE(PSG_WAVE_THIN,  2, 5200, 3100, 14, 7,  10, 15),
    PSG_TONE(PSG_WAVE_BELL,  5, 3100, 1300, 7,  0,  10, 15)
};

/* Turn-pass PSG jingle: compact bright arpeggio with a short CD-DA duck, closer
   to the supplied TurnPassed.wav cadence than the old long droning chord. */
static const WaifuPcfxPsgStep g_sfx_turn_a[] = {
    PSG_TONE(PSG_WAVE_BELL,  6,  784,  988, 28, 22, 15, 15),
    PSG_TONE(PSG_WAVE_BELL,  8, 1175, 1568, 30, 23, 15, 15),
    PSG_TONE(PSG_WAVE_PLUCK, 8, 1568, 1976, 26, 14, 15, 15),
    PSG_TONE(PSG_WAVE_SOFT, 22, 1175,  988, 12,  0, 15, 15)
};
static const WaifuPcfxPsgStep g_sfx_turn_b[] = {
    PSG_TONE(PSG_WAVE_SOFT,  6, 392, 494, 22, 18, 15, 13),
    PSG_TONE(PSG_WAVE_SOFT,  8, 587, 784, 24, 18, 15, 13),
    PSG_TONE(PSG_WAVE_BELL,  8, 784, 988, 18,  8, 15, 13),
    PSG_TONE(PSG_WAVE_SOFT, 22, 587, 494,  8,  0, 15, 13)
};
static const WaifuPcfxPsgStep g_sfx_turn_c[] = {
    PSG_TONE(PSG_WAVE_TRIANGLE, 14, 196, 247, 20, 17, 15, 15),
    PSG_TONE(PSG_WAVE_TRIANGLE, 14, 294, 392, 18, 10, 15, 15),
    PSG_TONE(PSG_WAVE_TRIANGLE, 18, 247, 196, 10,  0, 15, 15)
};
static const WaifuPcfxPsgStep g_sfx_turn_d[] = {
    PSG_TONE(PSG_WAVE_THIN,  3, 3136, 3951, 22, 14, 11, 15),
    PSG_TONE(PSG_WAVE_BELL,  9, 3951, 5274, 16,  6, 11, 15),
    PSG_TONE(PSG_WAVE_SOFT, 34, 2637, 1976,  6,  0, 11, 15)
};
static const WaifuPcfxPsgStep g_sfx_turn_e[] = {
    PSG_TONE(PSG_WAVE_THIN,  4, 2637, 3520, 18, 10, 15, 10),
    PSG_TONE(PSG_WAVE_BELL, 10, 3520, 4699, 14,  5, 15, 10),
    PSG_TONE(PSG_WAVE_SOFT, 32, 2349, 1760,  5,  0, 15, 10)
};
static const WaifuPcfxPsgStep g_sfx_turn_f[] = {
    PSG_TONE(PSG_WAVE_BELL,  8, 1976, 2637, 16,  9, 10, 15),
    PSG_TONE(PSG_WAVE_BELL, 12, 2637, 3951, 12,  4, 10, 15),
    PSG_TONE(PSG_WAVE_SOFT, 26, 1976, 1568,  4,  0, 10, 15)
};

static const WaifuPcfxPsgStep g_sfx_lost_a[] = {
    PSG_TONE(PSG_WAVE_SOFT,  8, 520, 440, 16, 12, 13, 13),
    PSG_TONE(PSG_WAVE_TRIANGLE, 12, 440, 220, 12, 0, 13, 13)
};
static const WaifuPcfxPsgStep g_sfx_lost_b[] = {
    PSG_TONE(PSG_WAVE_SOFT,  10, 390, 330, 9,  5,  11, 15),
    PSG_TONE(PSG_WAVE_TRIANGLE, 10, 330, 165, 5,  0,  11, 15)
};

static void psg_configure_current_step(WaifuPcfxPsgVoice *v)
{
    const WaifuPcfxPsgStep *s;
    if (!v || !v->active || !v->steps || v->step_index >= v->step_count) return;
    s = &v->steps[v->step_index];
    v->frame = 0;
    v->duration = s->duration ? s->duration : 1;
    v->volume0 = s->vol0;
    v->volume1 = s->vol1;
    v->pan_l = s->pan_l;
    v->pan_r = s->pan_r;
    v->noise = (s->flags & PSG_STEP_NOISE) ? 1u : 0u;
    v->noise0 = s->noise0 & 31u;
    v->noise1 = s->noise1 & 31u;
    v->period0 = psg_period_from_hz(s->hz0);
    v->period1 = psg_period_from_hz(s->hz1);
    if (!v->noise && v->loaded_wave != s->wave_id) {
        psg_load_wave(v->channel, psg_wave_ptr(s->wave_id));
        v->loaded_wave = s->wave_id;
    }
}

static uint16_t psg_sequence_max_age(const WaifuPcfxPsgStep *steps, uint8_t step_count)
{
    uint16_t total = 0;
    uint8_t i;
    if (!steps || step_count == 0) return 1;
    for (i = 0; i < step_count; ++i) {
        total = (uint16_t)(total + (steps[i].duration ? steps[i].duration : 1u));
    }
    return (uint16_t)(total + 2u);
}

static void psg_start_sequence(int slot, uint8_t ch,
                               const WaifuPcfxPsgStep *steps, uint8_t step_count)
{
    WaifuPcfxPsgVoice *v;
    if (slot < 0 || slot >= WAIFU_PCFX_PSG_SFX_VOICES) return;
    if (ch >= WAIFU_PCFX_PSG_CHANNELS) return;
    if (!steps || step_count == 0) return;
    v = &g_psg_voices[slot];
    g_psg_off_guard[ch] = 0u;
    v->active = 1;
    v->channel = ch;
    v->step_index = 0;
    v->step_count = step_count;
    v->steps = steps;
    v->loaded_wave = 255u;
    v->age = 0;
    v->max_age = psg_sequence_max_age(steps, step_count);
    psg_channel_off(ch);
    psg_configure_current_step(v);
}

static void waifu_pcfx_psg_stop_all(void)
{
    int i;
    for (i = 0; i < WAIFU_PCFX_PSG_SFX_VOICES; ++i) g_psg_voices[i].active = 0;
    for (i = 0; i < WAIFU_PCFX_PSG_CHANNELS; ++i) psg_channel_off((uint8_t)i);
}

static void waifu_pcfx_sfx_pump_psg(void)
{
    int i;
    for (i = 0; i < WAIFU_PCFX_PSG_SFX_VOICES; ++i) {
        WaifuPcfxPsgVoice *v = &g_psg_voices[i];
        uint8_t vol;
        if (!v->active) continue;
        if (v->age++ >= v->max_age) {
            psg_channel_off(v->channel);
            v->active = 0;
            continue;
        }
        while (v->active && v->frame >= v->duration) {
            ++v->step_index;
            if (v->step_index >= v->step_count) {
                psg_channel_off(v->channel);
                v->active = 0;
            } else {
                psg_configure_current_step(v);
            }
        }
        if (!v->active) continue;
        vol = lerp_u8(v->volume0, v->volume1, v->frame, v->duration);
        eris_low_psg_set_channel(v->channel);
        eris_low_psg_set_balance(v->pan_l, v->pan_r);
        if (v->noise) {
            eris_low_psg_set_freq(0);
            eris_low_psg_set_noise(lerp_u8(v->noise0, v->noise1, v->frame, v->duration), 1);
        } else {
            eris_low_psg_set_noise(0, 0);
            eris_low_psg_set_freq(lerp_u16(v->period0, v->period1, v->frame, v->duration));
        }
        eris_low_psg_set_volume(vol, vol ? 1 : 0, 0);
        ++v->frame;
    }
    for (i = 0; i < WAIFU_PCFX_PSG_CHANNELS; ++i) {
        if (g_psg_off_guard[i]) {
            eris_low_psg_set_channel((uint8_t)i);
            eris_low_psg_set_noise(0, 0);
            eris_low_psg_set_freq(0);
            eris_low_psg_set_balance(0, 0);
            eris_low_psg_set_volume(0, 0, 0);
            --g_psg_off_guard[i];
        }
    }
}

static inline void king_reg_h(uint16_t reg, uint16_t value)
{
#if defined(__v810__)
    __asm__ volatile (
        "out.h %[reg],0x600[r0]\n"
        "out.h %[val],0x604[r0]\n"
        :: [reg] "r" (reg), [val] "r" (value) : "memory");
#else
    (void)reg; (void)value;
#endif
}

static inline void king_reg_w(uint16_t reg, uint32_t value)
{
#if defined(__v810__)
    __asm__ volatile (
        "out.h %[reg],0x600[r0]\n"
        "out.w %[val],0x604[r0]\n"
        :: [reg] "r" (reg), [val] "r" (value) : "memory");
#else
    (void)reg; (void)value;
#endif
}

static void waifu_pcfx_adpcm_stop_hw(void)
{
    king_reg_h(0x50u, 0u);
    king_reg_h(0x51u, 0u); /* ch0: sequential, no interrupts */
    king_reg_h(0x52u, 0u); /* ch1: sequential, no interrupts */
    king_reg_h(0x58u, 0u);
    king_reg_w(0x59u, 0u);
    king_reg_h(0x5Cu, 0u);
    king_reg_w(0x5Du, 0u);
}

int waifu_pcfx_adpcm_samples_load(void)
{
    if (g_adpcm_loaded) return 1;
    eris_low_adpcm_set_control(ADPCM_RATE_16000, 1, 1, 1, 1);
    eris_low_adpcm_set_control(ADPCM_RATE_16000, 1, 1, 0, 0);
    eris_low_adpcm_set_volume(0, 63, 63);
    eris_low_adpcm_set_volume(1, 63, 63);
    waifu_pcfx_adpcm_stop_hw();

    if (waifu_pcfx_cdrom_read_sfx_adpcm_to_kram(WAIFU_PCFX_SFX_ADPCM_KRAM_BASE_WORD,
                                                WAIFU_PCFX_SFX_ADPCM_BANK_BYTES)) {
        g_adpcm_loaded = 1;
    }
    return g_adpcm_loaded;
}

void waifu_pcfx_adpcm_sample_play(int effect)
{
    const WaifuPcfxSfxAdpcmMeta *m;
    uint32_t start;
    uint32_t end;
    uint16_t play;
    uint8_t volume;

    if (!waifu_pcfx_adpcm_samples_load()) return;
    if (effect < 0) return;
    if ((unsigned)effect >= (sizeof(waifu_pcfx_sfx_adpcm_meta) / sizeof(waifu_pcfx_sfx_adpcm_meta[0]))) return;
    m = &waifu_pcfx_sfx_adpcm_meta[effect];
    if (m->word_count == 0) return;

    start = WAIFU_PCFX_SFX_ADPCM_KRAM_BASE_WORD + m->start_word;
    end = start + m->word_count - 1u;
    volume = m->volume ? m->volume : 63u;

    eris_low_adpcm_set_control(ADPCM_RATE_16000, 1, 1, 1, 0);
    eris_low_adpcm_set_control(ADPCM_RATE_16000, 1, 1, 0, 0);
    eris_low_adpcm_set_volume(0, volume, volume);

    king_reg_h(0x50u, 0u);
    king_reg_h(0x51u, 0u);
    king_reg_h(0x58u, (uint16_t)(start >> 8));
    king_reg_w(0x59u, end);
    play = (uint16_t)(1u | 4u); /* ch0 + 16 kHz rate bits */
    king_reg_h(0x50u, play);
}

static void waifu_pcfx_sfx_init(void)
{
    int i;
    g_adpcm_loaded = 0;
    eris_low_psg_set_main_volume(15, 15);
    eris_low_psg_set_lfo_control(0, 0);
    eris_low_psg_set_lfo_freq(0);
    for (i = 0; i < WAIFU_PCFX_PSG_CHANNELS; ++i) {
        psg_load_wave((uint8_t)i, g_psg_wave_soft);
        psg_channel_off((uint8_t)i);
    }
    waifu_pcfx_adpcm_stop_hw();
}

void waifu_pcfx_sfx_play(int effect)
{
    if (effect < 0 || effect >= WAIFU_SOUND_EFFECT_COUNT) return;

    switch ((WaifuSoundEffect)effect) {
    case WAIFU_SOUND_SELECT:
        psg_start_sequence(0, 0, g_sfx_select_a, PSG_COUNT(g_sfx_select_a));
        psg_start_sequence(1, 1, g_sfx_select_b, PSG_COUNT(g_sfx_select_b));
        break;
    case WAIFU_SOUND_CONFIRM:
        psg_start_sequence(0, 0, g_sfx_confirm_a, PSG_COUNT(g_sfx_confirm_a));
        psg_start_sequence(1, 1, g_sfx_confirm_b, PSG_COUNT(g_sfx_confirm_b));
        break;
    case WAIFU_SOUND_CONFIRM_ALT:
        psg_start_sequence(0, 0, g_sfx_cancel_a, PSG_COUNT(g_sfx_cancel_a));
        psg_start_sequence(1, 1, g_sfx_cancel_b, PSG_COUNT(g_sfx_cancel_b));
        break;
    case WAIFU_SOUND_CARD_PLACED:
        psg_start_sequence(0, 0, g_sfx_card_place_thump, PSG_COUNT(g_sfx_card_place_thump));
        psg_start_sequence(2, 2, g_sfx_card_place_spark, PSG_COUNT(g_sfx_card_place_spark));
        psg_start_sequence(4, 4, g_sfx_card_place_air, PSG_COUNT(g_sfx_card_place_air));
        break;
    case WAIFU_SOUND_CARD_DESTROYED:
        waifu_pcfx_cdda_request_duck(WAIFU_PCFX_CDDA_DUCK_SHORT);
        psg_start_sequence(0, 0, g_sfx_card_destroy_tone, PSG_COUNT(g_sfx_card_destroy_tone));
        psg_start_sequence(2, 2, g_sfx_card_destroy_shard, PSG_COUNT(g_sfx_card_destroy_shard));
        psg_start_sequence(5, 5, g_sfx_card_destroy_noise, PSG_COUNT(g_sfx_card_destroy_noise));
        break;
    case WAIFU_SOUND_TURN_PASSED:
        waifu_pcfx_cdda_request_duck(WAIFU_PCFX_CDDA_DUCK_LONG);
        g_turn_jingle_guard_frames = WAIFU_PCFX_CDDA_DUCK_LONG;
        psg_start_sequence(0, 0, g_sfx_turn_a, PSG_COUNT(g_sfx_turn_a));
        psg_start_sequence(1, 1, g_sfx_turn_b, PSG_COUNT(g_sfx_turn_b));
        psg_start_sequence(2, 2, g_sfx_turn_c, PSG_COUNT(g_sfx_turn_c));
        psg_start_sequence(3, 3, g_sfx_turn_d, PSG_COUNT(g_sfx_turn_d));
        psg_start_sequence(4, 4, g_sfx_turn_e, PSG_COUNT(g_sfx_turn_e));
        psg_start_sequence(5, 5, g_sfx_turn_f, PSG_COUNT(g_sfx_turn_f));
        break;
    case WAIFU_SOUND_LASER_SHOOT:
        waifu_pcfx_cdda_request_duck(WAIFU_PCFX_CDDA_DUCK_SHORT);
        psg_start_sequence(0, 0, g_sfx_laser_main, PSG_COUNT(g_sfx_laser_main));
        psg_start_sequence(1, 1, g_sfx_laser_side, PSG_COUNT(g_sfx_laser_side));
        psg_start_sequence(5, 5, g_sfx_laser_noise, PSG_COUNT(g_sfx_laser_noise));
        break;
    case WAIFU_SOUND_DIRECT_HIT:
        waifu_pcfx_cdda_request_duck(WAIFU_PCFX_CDDA_DUCK_SHORT);
        psg_start_sequence(0, 0, g_sfx_direct_hit_tone, PSG_COUNT(g_sfx_direct_hit_tone));
        psg_start_sequence(2, 2, g_sfx_direct_hit_spark, PSG_COUNT(g_sfx_direct_hit_spark));
        psg_start_sequence(5, 5, g_sfx_direct_hit_noise, PSG_COUNT(g_sfx_direct_hit_noise));
        break;
    case WAIFU_SOUND_CARD_DRAWN:
        waifu_pcfx_cdda_request_duck(WAIFU_PCFX_CDDA_DUCK_SHORT);
        if (g_turn_jingle_guard_frames) {
            /* During turn handoff the jingle owns channels 0..3.  Keep it intact
               and put the draw scrape on the two noise-capable channels. */
            psg_start_sequence(4, 4, g_sfx_card_draw_noise_b, PSG_COUNT(g_sfx_card_draw_noise_b));
            psg_start_sequence(5, 5, g_sfx_card_draw_noise_a, PSG_COUNT(g_sfx_card_draw_noise_a));
        } else {
            psg_start_sequence(0, 0, g_sfx_card_draw_tone, PSG_COUNT(g_sfx_card_draw_tone));
            psg_start_sequence(1, 1, g_sfx_card_draw_tone_b, PSG_COUNT(g_sfx_card_draw_tone_b));
            psg_start_sequence(2, 2, g_sfx_card_draw_tail, PSG_COUNT(g_sfx_card_draw_tail));
            psg_start_sequence(4, 4, g_sfx_card_draw_noise_b, PSG_COUNT(g_sfx_card_draw_noise_b));
            psg_start_sequence(5, 5, g_sfx_card_draw_noise_a, PSG_COUNT(g_sfx_card_draw_noise_a));
        }
        break;
    case WAIFU_SOUND_YOU_LOST:
        psg_start_sequence(0, 0, g_sfx_lost_a, PSG_COUNT(g_sfx_lost_a));
        psg_start_sequence(1, 1, g_sfx_lost_b, PSG_COUNT(g_sfx_lost_b));
        break;
    default:
        break;
    }
}

/* Returns the CD track number for a music enum value, or 0 for silence.
   Track numbers match the alphabetical sort of WAV files in Music/ as
   emitted by pcfx-cdlink into cdda_tracks.h. */
static uint8_t music_to_cdda_track(WaifuFmMusicTrack track)
{
    switch (track) {
    case WAIFU_FM_MUSIC_TITLE:        return CDDA_TRACK_TITLESCREEN_MOONLITCIPHER;
    case WAIFU_FM_MUSIC_OPENING_DREAM:return CDDA_TRACK_OVERWORLD;
    case WAIFU_FM_MUSIC_DECK_EDITOR:  return CDDA_TRACK_OVERWORLD;
    case WAIFU_FM_MUSIC_BOSS:         return CDDA_TRACK_BOSS;
    case WAIFU_FM_MUSIC_FINAL_BOSS:   return CDDA_TRACK_FINALBOSS;
    case WAIFU_FM_MUSIC_RANDOM_BATTLE:return CDDA_TRACK_BATTLE;
    case WAIFU_FM_MUSIC_RESULTS:      return CDDA_TRACK_VICTORY;
    case WAIFU_FM_MUSIC_LOST:         return CDDA_TRACK_YOULOST;
    default:                          return 0;
    }
}

static uint8_t music_to_cdda_loop(WaifuFmMusicTrack track)
{
    switch (track) {
    case WAIFU_FM_MUSIC_RESULTS:
    case WAIFU_FM_MUSIC_LOST:
        return WAIFU_CDDA_NORMAL; /* victory/loss jingle: play once */
    default:
        return WAIFU_CDDA_LOOP;
    }
}

WaifuPcfxAudio *waifu_pcfx_audio_create(void)
{
    g_audio.current_music = WAIFU_FM_MUSIC_NONE;
    g_audio.desired_track = 0;
    g_audio.desired_loop = WAIFU_CDDA_LOOP;
    g_audio.active_track = 0;
    g_audio.active_loop = WAIFU_CDDA_LOOP;
    g_audio.active_seq = 0;
    g_audio.last_read_seq = waifu_pcfx_cd_read_seq();
    g_cdda_duck_frames = 0;
    g_turn_jingle_guard_frames = 0;
    g_cdda_mix_volume = 255u;
    waifu_pcfx_cdda_apply_mix_volume(WAIFU_PCFX_CDDA_BASE_VOLUME);
    waifu_pcfx_sfx_init();
    g_audio.last_read_seq = waifu_pcfx_cd_read_seq();
    return &g_audio;
}

void waifu_pcfx_audio_destroy(WaifuPcfxAudio *audio)
{
    (void)audio;
}

void waifu_pcfx_audio_set_music(WaifuPcfxAudio *audio, WaifuFmMusicTrack track)
{
    if (!audio) return;
    if (audio->current_music == track) return;
    audio->current_music = track;
    /* Record intent only.  The actual SCSI play is issued from the pump once
       any in-flight CD data load has settled, because a data read would stop
       CD-DA again immediately.  This also handles re-arming after a load. */
    audio->desired_track = music_to_cdda_track(track);
    audio->desired_loop = music_to_cdda_loop(track);
    if (audio->desired_track == 0) audio->silence_stop_frames = 10u;
}

/* Issue/refresh CD-DA playback to match desired_track, but only when CD reads
   have settled for a frame.  A data read stops the drive's audio engine, so we
   restart the loop whenever a read has happened since we last started it. */
void waifu_pcfx_audio_pump(WaifuPcfxAudio *audio)
{
    uint32_t seq;
    if (!audio) return;

    seq = waifu_pcfx_cd_read_seq();
    waifu_pcfx_sfx_pump_psg();
    waifu_pcfx_cdda_pump_mix_volume();

    /* Silence requested (e.g. loading screen): force-stop CD-DA and PSG
       immediately, without deferring behind in-flight reads.  The short forced
       STOP burst also covers emulator/state cases where the drive is playing
       but active_track is not in sync yet. */
    if (audio->desired_track == 0) {
        waifu_pcfx_psg_stop_all();
        if (audio->active_track != 0 || audio->silence_stop_frames) {
            waifu_pcfx_cdda_stop();
            audio->active_track = 0;
            if (audio->silence_stop_frames) --audio->silence_stop_frames;
        }
        audio->last_read_seq = seq;
        return;
    }

    if (seq != audio->last_read_seq) {
        /* A CD data load happened during this frame; it has stopped any CD-DA.
           Wait until a frame passes with no further reads before (re)starting,
           so we don't fight an in-progress multi-sector load. */
        audio->last_read_seq = seq;
        return;
    }

    /* Start when the track changed, or when a read has interrupted playback
       since we last issued it (active_seq lags the current read seq).

       PC-FX D9 uses an exclusive end position.  For one music item, play from
       the desired track to the following track/leadout.  Passing start=end is
       an empty range; passing mode 0 is silent. */
    if (audio->desired_track != audio->active_track ||
        audio->desired_loop != audio->active_loop ||
        seq != audio->active_seq) {
        waifu_pcfx_cdda_play(audio->desired_track, (uint8_t)(audio->desired_track + 1u), audio->desired_loop);
        audio->active_track = audio->desired_track;
        audio->active_loop = audio->desired_loop;
        audio->active_seq = seq;
    }
}

void waifu_pcfx_audio_stop_all(WaifuPcfxAudio *audio)
{
    if (!audio) return;
    audio->current_music = WAIFU_FM_MUSIC_NONE;
    audio->desired_track = 0;
    audio->desired_loop = WAIFU_CDDA_LOOP;
    audio->active_track = 0;
    audio->active_loop = WAIFU_CDDA_LOOP;
    audio->silence_stop_frames = 10u;
    g_cdda_duck_frames = 0;
    g_turn_jingle_guard_frames = 0;
    waifu_pcfx_cdda_apply_mix_volume(WAIFU_PCFX_CDDA_BASE_VOLUME);
    waifu_pcfx_cdda_stop();
    waifu_pcfx_psg_stop_all();
    waifu_pcfx_adpcm_stop_hw();
}
