#!/usr/bin/env python3
import os
import wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'sounds')
if not os.path.exists(os.path.join(SRC, 'Select.wav')):
    SRC = os.path.join(ROOT, 'sounds')
OUT_H = os.path.join(ROOT, 'src', 'generated', 'cd32x_sfx_pcm.h')
OUT_BIN = os.path.join(ROOT, 'assets', 'generated', 'cd32x_sfx_pcm.bin')
RATE = 8000
LOOP_SILENCE_BYTES = 16
# RF5C164 frequency delta for RATE.  BlastEm models Sega CD PCM at
# 50 MHz / (4 * 384), with cur_ptr advancing by delta / 2048 per output sample.
SCD_MASTER_CLOCK = 50000000
RF5C164_DIVIDER = 4
RF5C164_FRAC_SCALE = 1 << 11
FREQ_DELTA = (RATE * RF5C164_FRAC_SCALE * RF5C164_DIVIDER * 384 + SCD_MASTER_CLOCK // 2) // SCD_MASTER_CLOCK
SOUNDS = [
    ('SELECT', 'Select.wav'),
    ('CONFIRM', 'Confirm.wav'),
    ('CONFIRM_ALT', 'ConfirmAlt.wav'),
    ('CARD_PLACED', 'CardPlaced.wav'),
    ('CARD_DESTROYED', 'CardDestroyed.wav'),
    ('TURN_PASSED', 'TurnPassed.wav'),
    ('YOU_LOST', None),
    ('LASER_SHOOT', 'SlashAttack.wav'),
    ('DIRECT_HIT', 'SlashAttack.wav'),
    ('CARD_DRAWN', 'CardDrawn.wav'),
]

def read_wav_u8_mono_44100(path):
    with wave.open(path, 'rb') as w:
        if w.getnchannels() != 1 or w.getsampwidth() != 1 or w.getframerate() != 44100:
            raise SystemExit(f'{path}: expected unsigned 8-bit mono 44100 Hz WAV')
        return w.readframes(w.getnframes())

def resample_u8_to_s8(data, src_rate=44100, dst_rate=RATE):
    if not data:
        return bytearray()
    out_len = max(1, (len(data) * dst_rate + src_rate // 2) // src_rate)
    out = bytearray()
    for i in range(out_len):
        a = (i * src_rate) // dst_rate
        b = ((i + 1) * src_rate) // dst_rate
        if b <= a: b = a + 1
        if b > len(data): b = len(data)
        if a >= len(data):
            a = len(data) - 1
            b = len(data)
        avg = sum(data[a:b]) // (b - a)
        s = avg - 128
        if s < -127: s = -127
        elif s > 126: s = 126
        out.append(s & 0xFF)
    out.extend([0] * LOOP_SILENCE_BYTES)
    return out

def main():
    os.makedirs(os.path.dirname(OUT_H), exist_ok=True)
    os.makedirs(os.path.dirname(OUT_BIN), exist_ok=True)
    emitted = {}
    entries = []
    blob = bytearray()
    next_block = 0
    for name, filename in SOUNDS:
        if filename is None:
            entries.append((0, 0, 0, 0))
            continue
        if filename in emitted:
            entries.append(emitted[filename])
            continue
        pcm = resample_u8_to_s8(read_wav_u8_mono_44100(os.path.join(SRC, filename)))
        # Align the binary blob to 2 bytes for the M68K loader/copy code.
        if len(blob) & 1:
            blob.append(0)
        offset = len(blob)
        blob.extend(pcm)
        start = next_block
        blocks = (len(pcm) + 32 + 255) >> 8
        next_block += blocks
        volume = 0xD8 if name in ('CARD_DESTROYED', 'TURN_PASSED', 'LASER_SHOOT', 'DIRECT_HIT') else 0xE8
        ent = (offset, len(pcm), start, volume)
        emitted[filename] = ent
        entries.append(ent)
    if next_block > 255:
        raise SystemExit(f'PCM wave RAM bank too large: needs {next_block} blocks')
    with open(OUT_BIN, 'wb') as f:
        f.write(blob)
    with open(OUT_H, 'w') as f:
        f.write('/* Generated by tools/gen_cd32x_sfx_pcm.py. */\n')
        f.write('#ifndef WAIFU_CD32X_SFX_PCM_H\n#define WAIFU_CD32X_SFX_PCM_H\n\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'#define WAIFU_CD32X_SFX_PCM_RATE {RATE}u\n')
        f.write('#define WAIFU_CD32X_SFX_PCM_META_COUNT 10u\n')
        f.write(f'#define WAIFU_CD32X_SFX_PCM_FREQ_DELTA 0x{FREQ_DELTA:04X}u\n')
        f.write(f'#define WAIFU_CD32X_SFX_PCM_LOOP_SILENCE_BYTES {LOOP_SILENCE_BYTES}u\n')
        f.write(f'#define WAIFU_CD32X_SFX_PCM_USED_BLOCKS {next_block}u\n')
        f.write(f'#define WAIFU_CD32X_SFX_PCM_BANK_BYTES {len(blob)}u\n')
        f.write('typedef struct WaifuCd32xSfxPcmMeta {\n')
        f.write('    uint32_t offset;\n')
        f.write('    uint16_t length;\n')
        f.write('    uint8_t start_block;\n')
        f.write('    uint8_t volume;\n')
        f.write('} WaifuCd32xSfxPcmMeta;\n\n')
        f.write('static const WaifuCd32xSfxPcmMeta waifu_cd32x_sfx_pcm_meta[] = {\n')
        for offset, length, start, volume in entries:
            if length <= 0:
                f.write('    { 0, 0, 0, 0 },\n')
            else:
                f.write(f'    {{ {offset}u, {length}u, {start}u, {volume}u }},\n')
        f.write('};\n\n')
        f.write('#endif /* WAIFU_CD32X_SFX_PCM_H */\n')
    print(f'wrote {OUT_BIN}: {len(blob)} bytes; {next_block} PCM blocks')
    print(f'wrote {OUT_H}')

if __name__ == '__main__':
    main()
