#!/usr/bin/env python3
"""Compile the SDL3 frontend's GLSL shaders to SPIR-V and embed them in a
generated header, following the repo's checked-in-generated-file convention:
the header is committed so building the SDL3 target needs no shader tools;
re-run this script (which needs glslc from shaderc) after editing any
shader under src/platform/sdl3/shaders/.

Usage: python3 tools/gen_sdl3_shaders.py
"""

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADER_DIR = os.path.join(ROOT, "src", "platform", "sdl3", "shaders")
OUT_PATH = os.path.join(ROOT, "src", "generated", "sdl3_shaders.h")

GLSLC = os.environ.get("GLSLC", "glslc")


def compile_spirv(src_path):
    """glslc infers the stage from the .vert/.frag extension."""
    result = subprocess.run(
        [GLSLC, "-O", src_path, "-o", "-"],
        capture_output=True,
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr.decode())
        raise SystemExit(f"glslc failed for {src_path}")
    return result.stdout


def c_array_name(filename):
    # palette.vert -> waifu_sdl3_palette_vert_spv
    base = filename.replace(".", "_").replace("-", "_")
    return f"waifu_sdl3_{base}_spv"


def emit_bytes(data):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + " ".join(f"0x{b:02x}," for b in chunk))
    return "\n".join(lines)


def main():
    sources = sorted(
        f for f in os.listdir(SHADER_DIR)
        if f.endswith(".vert") or f.endswith(".frag")
    )
    if not sources:
        raise SystemExit(f"no shaders found in {SHADER_DIR}")

    parts = [
        "/* Auto-generated by tools/gen_sdl3_shaders.py — do not edit.\n"
        " * SPIR-V binaries for the SDL3 GPU frontend, compiled from\n"
        " * src/platform/sdl3/shaders/. */\n"
        "#ifndef WAIFU_SDL3_SHADERS_H\n"
        "#define WAIFU_SDL3_SHADERS_H\n"
    ]
    for src in sources:
        spirv = compile_spirv(os.path.join(SHADER_DIR, src))
        name = c_array_name(src)
        parts.append(
            f"\n/* {src} ({len(spirv)} bytes) */\n"
            f"static const unsigned char {name}[] = {{\n"
            f"{emit_bytes(spirv)}\n"
            f"}};\n"
        )
        print(f"  {src}: {len(spirv)} bytes -> {name}")
    parts.append("\n#endif /* WAIFU_SDL3_SHADERS_H */\n")

    with open(OUT_PATH, "w") as fh:
        fh.write("".join(parts))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
