#!/usr/bin/env python3
import os, wave, textwrap
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'assets', 'sounds')
if not os.path.exists(os.path.join(SRC, 'Select.wav')):
    SRC = os.path.join(ROOT, 'sounds')
OUT = os.path.join(ROOT, 'src', 'generated', 'sound_assets.h')
SOUNDS = [
    ('SELECT', 'Select.wav'),
    ('CONFIRM', 'Confirm.wav'),
    ('CONFIRM_ALT', 'ConfirmAlt.wav'),
    ('CARD_PLACED', 'CardPlaced.wav'),
    ('CARD_DESTROYED', 'CardDestroyed.wav'),
    ('TURN_PASSED', 'TurnPassed.wav'),
    # Youlost is PC-FX CD-DA now; keep enum slot silent in PCM table.
    ('YOU_LOST', None),
    ('LASER_SHOOT', 'laserShoot.wav'),
]

def ident(name):
    return 'waifu_sound_' + name.lower()

def read_wav(path):
    with wave.open(path, 'rb') as w:
        if w.getnchannels() != 1 or w.getsampwidth() != 1 or w.getframerate() != 44100:
            raise SystemExit(f'{path}: expected unsigned 8-bit mono 44100 Hz WAV')
        return w.readframes(w.getnframes())

def emit_array(f, name, data):
    f.write(f'static const unsigned char {ident(name)}_pcm[{len(data)}] = {{\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ', '.join(str(b) for b in chunk))
        if i + 16 < len(data):
            f.write(',')
        f.write('\n')
    f.write('};\n\n')

def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/gen_sound_assets.py. */\n')
        f.write('#ifndef WAIFU_FM_SOUND_ASSETS_H\n#define WAIFU_FM_SOUND_ASSETS_H\n\n')
        f.write('#define WAIFU_SOUND_ASSET_RATE 44100\n\n')
        lengths = []
        for name, filename in SOUNDS:
            if filename is None:
                lengths.append((name, 0))
                continue
            data = read_wav(os.path.join(SRC, filename))
            lengths.append((name, len(data)))
            emit_array(f, name, data)
        f.write('typedef struct WaifuSoundAsset {\n')
        f.write('    const unsigned char *pcm_u8;\n')
        f.write('    int frame_count;\n')
        f.write('} WaifuSoundAsset;\n\n')
        f.write('static const WaifuSoundAsset waifu_sound_assets[] = {\n')
        for name, length in lengths:
            if length <= 0:
                f.write('    { 0, 0 },\n')
            else:
                f.write(f'    {{ {ident(name)}_pcm, {length} }},\n')
        f.write('};\n\n')
        f.write('#endif /* WAIFU_FM_SOUND_ASSETS_H */\n')

if __name__ == '__main__':
    main()
