#!/usr/bin/env python3
"""Generate a C header listing the high-resolution SOURCE image path for every
card, plus the widescreen title/ending art, for the SDL3 GPU frontend.

The SDL3 target can load the original full-resolution artwork at runtime instead
of the tiny quantized 38x54 / 112x112 blobs baked into waifu_assets.h.  This tool
resolves each card's source image (by asset_id, trying several extensions) and
emits repo-root-relative paths in card_id order, so the C frontend can index the
array by card id.  The header is committed following the repo's
checked-in-generated-file convention.

Usage: python3 tools/gen_sdl3_hires_paths.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CARD_DIR = ROOT / 'assets/source/cards'
CARD_DATA = CARD_DIR / 'card_data.txt'
PORTRAIT_DIR = ROOT / 'assets/source/story_portraits'
# Story portraits, in waifu_assets.h portrait-id order (see gen_assets.py's
# STORY_PORTRAITS). The PC build prefers a high-resolution variant of the same
# artwork; the suffixes are inconsistent in the source tree, so try them all and
# fall back to the small file the console assets were built from.
PORTRAIT_BASES = ['serena', 'opponent_0', 'opponent_1', 'opponent_2',
                  'opponent_3', 'opponent_4']
PORTRAIT_SUFFIXES = ['_hires', '_highres', '']
TITLE_SRC = ROOT / 'assets/source/title/title_16by9.png'
ENDING_SRC = ROOT / 'assets/source/ending/ending_16by9.png'
OUT = ROOT / 'src/generated/sdl3_card_paths.h'

CARD_EXTS = ['.png', '.webp', '.jpg', '.jpeg']


def parse_card_data(path: Path):
    """Parse card_data.txt exactly like tools/gen_assets.py: each non-empty,
    non-'#' line is split on '|'; 'card' rows carry 8 pipe-fields.  The card_id
    is the 0-based index of 'card' rows in file order; return their asset_ids."""
    if not path.exists():
        raise FileNotFoundError(path)
    asset_ids = []
    for lineno, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        parts = [p.strip() for p in line.split('|')]
        if parts[0] == 'card':
            if len(parts) != 8:
                raise SystemExit(f'{path}:{lineno}: card rows need 8 fields')
            asset_ids.append(parts[1])
    return asset_ids


def resolve_card_src(asset_id: str):
    """First existing source image for asset_id, as a repo-root-relative
    forward-slash path, or '' if none exists."""
    for ext in CARD_EXTS:
        p = CARD_DIR / (asset_id + ext)
        if p.exists():
            return p.relative_to(ROOT).as_posix()
    return ''


def resolve_portrait_src(base: str):
    """Highest-resolution source for one story portrait. '.png.png' is a real
    filename in the tree, so every suffix is tried with both endings."""
    for suffix in PORTRAIT_SUFFIXES:
        for ext in ('.png', '.png.png', '.webp', '.jpg'):
            p = PORTRAIT_DIR / (base + suffix + ext)
            if p.exists():
                return p.relative_to(ROOT).as_posix()
    return ''


def resolve_fullscreen_src(path: Path):
    return path.relative_to(ROOT).as_posix() if path.exists() else ''


def c_string(s: str):
    return s.replace('\\', '\\\\').replace('"', '\\"')


def main():
    asset_ids = parse_card_data(CARD_DATA)
    card_src = [resolve_card_src(a) for a in asset_ids]
    portrait_src = [resolve_portrait_src(b) for b in PORTRAIT_BASES]
    title_src = resolve_fullscreen_src(TITLE_SRC)
    ending_src = resolve_fullscreen_src(ENDING_SRC)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open('w', newline='\n') as f:
        f.write('/* Auto-generated by tools/gen_sdl3_hires_paths.py — do not edit. */\n')
        f.write('#ifndef WAIFU_SDL3_CARD_PATHS_H\n')
        f.write('#define WAIFU_SDL3_CARD_PATHS_H\n\n')
        f.write(f'#define WAIFU_SDL3_CARD_SRC_COUNT {len(card_src)}\n\n')
        f.write('static const char *const waifu_sdl3_card_src[WAIFU_SDL3_CARD_SRC_COUNT] = {\n')
        for src in card_src:
            f.write(f'    "{c_string(src)}",\n')
        f.write('};\n\n')
        f.write(f'#define WAIFU_SDL3_PORTRAIT_SRC_COUNT {len(portrait_src)}\n\n')
        f.write('static const char *const waifu_sdl3_portrait_src'
                '[WAIFU_SDL3_PORTRAIT_SRC_COUNT] = {\n')
        for src in portrait_src:
            f.write(f'    "{c_string(src)}",\n')
        f.write('};\n\n')
        f.write(f'static const char *const waifu_sdl3_title_src = "{c_string(title_src)}";\n')
        f.write(f'static const char *const waifu_sdl3_ending_src = "{c_string(ending_src)}";\n\n')
        f.write('#endif /* WAIFU_SDL3_CARD_PATHS_H */\n')

    resolved = sum(1 for s in card_src if s)
    print(f'wrote {OUT}: {len(card_src)} cards, {resolved} resolved, '
          f'{len(card_src) - resolved} empty')


if __name__ == '__main__':
    main()
