#!/usr/bin/env python3
import os
import struct
import wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'src', 'generated', 'sound_assets.h')

# Order MUST match the WaifuSoundEffect enum in src/game/sounds.h.  The PC
# build can afford the supplied stereo/16-bit clips, so keep a small rotating
# pool for effects that occur often.  The generator converts them to the
# existing compact unsigned-8-bit mono mixer format; the source WAVs remain
# the authoritative assets.
SOUND_VARIANTS = [
    ('SELECT', [
        'sounds/new/random-ui.wav',
        'sounds/new/random-ui(3).wav',
    ]),
    ('CONFIRM', ['sounds/new/random-ui(1).wav']),
    ('CONFIRM_ALT', ['sounds/new/random-ui(2).wav']),
    ('CARD_PLACED', [
        'sounds/new/mech-stomp.wav',
        'sounds/new/mech-stomp(1).wav',
    ]),
    ('CARD_DESTROYED', [
        'sounds/new/explosion(1).wav',
        'sounds/new/explosion(2).wav',
    ]),
    ('TURN_PASSED', ['sounds/new/random-magic.wav']),
    # Youlost is music on the PC-FX/CD32X/FM TOWNS ports; keep this enum slot
    # silent in the portable PCM table.
    ('YOU_LOST', []),
    ('LASER_SHOOT', [
        'sounds/new/random-impact.wav',
        'sounds/new/random-impact(1).wav',
        'sounds/new/random-impact(2).wav',
        'sounds/new/random-impact(3).wav',
    ]),
    ('DIRECT_HIT', [
        'sounds/new/multi-hit-rush-3-overkill.wav',
        'sounds/new/rush-explosion-finisher.wav',
    ]),
    ('CARD_DRAWN', ['sounds/new/coin-pickup.wav']),
]


def ident(name, variant):
    return 'waifu_sound_%s_%d' % (name.lower(), variant)


def read_wav(path):
    """Read a 44.1 kHz PCM WAV and downmix it to unsigned 8-bit mono."""
    with wave.open(path, 'rb') as w:
        channels = w.getnchannels()
        width = w.getsampwidth()
        rate = w.getframerate()
        if w.getcomptype() != 'NONE' or channels < 1 or rate != 44100 or width not in (1, 2):
            raise SystemExit(
                f'{path}: expected uncompressed 8/16-bit PCM WAV at 44100 Hz')
        raw = w.readframes(w.getnframes())

    if width == 1:
        # WAV 8-bit PCM is unsigned.  Average each frame without changing its
        # midpoint, retaining the old generator's byte-for-byte convention.
        out = bytearray()
        frame_bytes = channels
        for offset in range(0, len(raw), frame_bytes):
            frame = raw[offset:offset + frame_bytes]
            if len(frame) != frame_bytes:
                break
            out.append(sum(frame) // channels)
        return bytes(out)

    # WAV 16-bit PCM is signed little-endian.  Average channels before mapping
    # [-32768,32767] to the mixer byte range [0,255].
    out = bytearray()
    frame_bytes = channels * 2
    for offset in range(0, len(raw), frame_bytes):
        frame = raw[offset:offset + frame_bytes]
        if len(frame) != frame_bytes:
            break
        samples = struct.unpack('<%dh' % channels, frame)
        mono = sum(samples) // channels
        out.append(max(0, min(255, (mono + 32768) >> 8)))
    return bytes(out)

def emit_array(f, name, data):
    f.write(f'static const unsigned char {name}_pcm[{len(data)}] = {{\n')
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        f.write('    ' + ', '.join(str(b) for b in chunk))
        if i + 16 < len(data):
            f.write(',')
        f.write('\n')
    f.write('};\n\n')

def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/gen_sound_assets.py. */\n')
        f.write('#ifndef WAIFU_FM_SOUND_ASSETS_H\n#define WAIFU_FM_SOUND_ASSETS_H\n\n')
        f.write('#define WAIFU_SOUND_ASSET_RATE 44100\n\n')
        entries = []          # [(first_variant, variant_count), ...]
        emitted = {}          # path -> (array ident, length), so aliases share data
        variants = []         # (array ident, length) in flattened table order
        for name, filenames in SOUND_VARIANTS:
            first = len(variants)
            for filename in filenames:
                if filename in emitted:
                    arr, length = emitted[filename]
                else:
                    data = read_wav(os.path.join(ROOT, filename))
                    arr = ident(name, len(variants))
                    emit_array(f, arr, data)
                    length = len(data)
                    emitted[filename] = (arr, length)
                variants.append((arr, length))
            entries.append((first, len(filenames)))
        f.write('typedef struct WaifuSoundAsset {\n')
        f.write('    const unsigned char *pcm_u8;\n')
        f.write('    int frame_count;\n')
        f.write('} WaifuSoundAsset;\n\n')
        f.write('static const WaifuSoundAsset waifu_sound_asset_variants[] = {\n')
        for arr, length in variants:
            f.write(f'    {{ {arr}_pcm, {length} }},\n')
        f.write('};\n\n')
        f.write('typedef struct WaifuSoundAssetSet {\n')
        f.write('    unsigned short first_variant;\n')
        f.write('    unsigned char variant_count;\n')
        f.write('} WaifuSoundAssetSet;\n\n')
        f.write('#define WAIFU_SOUND_ASSET_EFFECT_COUNT %d\n\n' % len(entries))
        f.write('static const WaifuSoundAssetSet waifu_sound_assets[] = {\n')
        for first, count in entries:
            f.write(f'    {{ {first}, {count} }},\n')
        f.write('};\n\n')
        f.write('#endif /* WAIFU_FM_SOUND_ASSETS_H */\n')

if __name__ == '__main__':
    main()
