#!/usr/bin/env python3
"""Generate RF5C164 PCM music clips for the CD32X in-duel / deck-editor themes.

The full CD-DA themes are minutes long, but on CD32X the deck-editor and battle
screens stream card data off the disc, so their music is served by the Sega-CD
RF5C164 PCM chip instead of CD-DA (which would force a stop/resume around every
read).  Each theme is resampled to a short, looping 11.025 kHz 8-bit clip stored
as RF5C164 sign/magnitude bytes (so the supervisor refill is a plain copy) plus a
trailing 0xFF loop-end marker.  The supervisor loads one clip at a time into
Sub-CPU PRG RAM and refills the PCM wave-RAM ring from it; Word RAM is left
entirely to the resident card atlas.

Output: assets/generated/<NAME>_PCM.BIN per theme + src/generated/cd32x_music_pcm.h
with the per-theme byte lengths and the shared sample rate / freq delta.
"""
import os
import wave
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, 'assets', 'generated')
OUT_H = os.path.join(ROOT, 'src', 'generated', 'cd32x_music_pcm.h')

RATE = 11025
# Keep each clip small enough to load fast (~1x CD) and fit Sub-CPU PRG RAM
# alongside the supervisor; a multi-second loop is plenty for these themes.
CLIP_SECONDS = 12.0
# RF5C164 frequency delta for RATE.  BlastEm models Sega CD PCM at
# 50 MHz / (4 * 384), with cur_ptr advancing by delta / 2048 per output sample.
SCD_MASTER_CLOCK = 50000000
RF5C164_DIVIDER = 4
RF5C164_FRAC_SCALE = 1 << 11
FREQ_DELTA = (RATE * RF5C164_FRAC_SCALE * RF5C164_DIVIDER * 384 + SCD_MASTER_CLOCK // 2) // SCD_MASTER_CLOCK

# (macro name, CD filename stem, source wav, loop-start seconds)
THEMES = [
    ('DECK_EDITOR', 'DECK', 'Music/Overworld.wav', 0.0),
    ('BATTLE',      'BATTLE', 'Music/Battle.wav', 0.0),
    ('BOSS',        'BOSS', 'Music/Boss.wav', 0.0),
    ('FINAL_BOSS',  'FINALBOSS', 'Music/FinalBoss.wav', 0.0),
]


def read_wav(path):
    with wave.open(path, 'rb') as w:
        ch = w.getnchannels()
        width = w.getsampwidth()
        rate = w.getframerate()
        raw = w.readframes(w.getnframes())
    return ch, width, rate, raw


def to_mono_s16(ch, width, raw):
    """Return a list of 16-bit signed mono samples."""
    out = []
    if width == 2:
        n = len(raw) // 2
        vals = struct.unpack('<%dh' % n, raw[:n * 2])
        if ch == 2:
            for i in range(0, n - 1, 2):
                out.append((vals[i] + vals[i + 1]) // 2)
        else:
            out = list(vals)
    elif width == 1:
        # unsigned 8-bit
        if ch == 2:
            for i in range(0, len(raw) - 1, 2):
                a = raw[i] - 128
                b = raw[i + 1] - 128
                out.append(((a + b) // 2) << 8)
        else:
            out = [(b - 128) << 8 for b in raw]
    else:
        raise SystemExit('unsupported sample width %d' % width)
    return out


def resample(samples, src_rate, dst_rate, count):
    """Nearest-neighbour resample to dst_rate, exactly `count` output samples."""
    out = [0] * count
    n = len(samples)
    if n == 0:
        return out
    for i in range(count):
        src = (i * src_rate) // dst_rate
        if src >= n:
            src = n - 1
        out[i] = samples[src]
    return out


def to_rf5c164(samples):
    """s16 -> RF5C164 sign/magnitude bytes (bit7 = sign, 0=negative)."""
    out = bytearray(len(samples))
    for i, s in enumerate(samples):
        v = s >> 8  # to 8-bit signed
        if v < 0:
            m = -v
            if m > 127:
                m = 127
            out[i] = m & 0x7F           # sign bit 0 => negative magnitude
        else:
            if v > 126:
                v = 126
            out[i] = 0x80 | v           # sign bit 1 => positive magnitude
        if out[i] == 0xFF:
            out[i] = 0xFE               # never emit the loop-end marker as data
    return out


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    count = int(RATE * CLIP_SECONDS)
    entries = []
    for macro, stem, wav, loop_s in THEMES:
        path = os.path.join(ROOT, wav)
        ch, width, rate, raw = read_wav(path)
        mono = to_mono_s16(ch, width, raw)
        clip = resample(mono, rate, RATE, count)
        pcm = to_rf5c164(clip)
        pcm.append(0xFF)                # loop-end marker
        out_bin = os.path.join(OUT_DIR, '%s_PCM.BIN' % stem)
        with open(out_bin, 'wb') as f:
            f.write(pcm)
        entries.append((macro, stem, len(pcm)))
        print('%-20s %-12s %6d bytes (%.1fs)' % (macro, stem + '_PCM.BIN', len(pcm), CLIP_SECONDS))

    with open(OUT_H, 'w') as f:
        f.write('/* Generated by tools/gen_cd32x_music_pcm.py - do not edit. */\n')
        f.write('#ifndef WAIFU_CD32X_MUSIC_PCM_H\n#define WAIFU_CD32X_MUSIC_PCM_H\n\n')
        f.write('#define WAIFU_CD32X_MUSIC_PCM_RATE %u\n' % RATE)
        f.write('#define WAIFU_CD32X_MUSIC_PCM_FREQ_DELTA 0x%04Xu\n' % FREQ_DELTA)
        f.write('#define WAIFU_CD32X_MUSIC_PCM_MAX_BYTES %u\n\n' % (count + 1))
        for i, (macro, stem, n) in enumerate(entries):
            f.write('#define WAIFU_CD32X_MUSIC_%s_ID %d\n' % (macro, i))
            f.write('#define WAIFU_CD32X_MUSIC_%s_FILE "%s_PCM.BIN"\n' % (macro, stem))
            f.write('#define WAIFU_CD32X_MUSIC_%s_BYTES %u\n' % (macro, n))
        f.write('#define WAIFU_CD32X_MUSIC_COUNT %d\n' % len(entries))
        f.write('\n#endif\n')
    print('wrote', OUT_H)


if __name__ == '__main__':
    main()
