#!/usr/bin/env python3
"""Generate PC-FX CD asset CRCs and independently placed recovery copies.

The PC-FX loader checks CRC-32 per physical 2048-byte sector.  The recovery
files deliberately have distinct ISO paths, so cdlink places a second physical
copy on the disc instead of treating this as a cache alias of the primary file.
"""
from __future__ import annotations

import argparse
import zlib
from pathlib import Path


SECTOR_BYTES = 2048
ASSETS = (
    ("TITLE_PCFX_IMG", "title_screen_pcfx_img.bin"),
    ("TITLE_YUV422", "title_screen_pcfx_yuv422.bin"),
    ("RAINBOW_DESERT", "rainbow_desert.bin"),
    ("RAINBOW_STONE", "rainbow_stone.bin"),
    ("RAINBOW_EMBER", "rainbow_ember.bin"),
    ("RAINBOW_SKY", "rainbow_sky.bin"),
    ("STORY_PORTRAITS", "story_portraits.bin"),
    ("STORY_PORTRAIT_MASK", "story_portrait_mask.bin"),
    ("CARD_FACES", "card_faces.bin"),
    ("CARD_BIG_ART", "card_big_art.bin"),
    ("CARD_BACK", "card_back.bin"),
    ("SUPPORT_FACE", "support_face.bin"),
    ("SUPPORT_BIG_ART", "support_big_art.bin"),
    ("SFX_ADPCM", "sfx_adpcm.bin"),
    ("ENDING_YUV422", "ending_screen_pcfx_yuv422.bin"),
)


def sectors(data: bytes) -> list[bytes]:
    pad = (-len(data)) % SECTOR_BYTES
    if pad:
        data += b"\0" * pad
    return [data[i:i + SECTOR_BYTES] for i in range(0, len(data), SECTOR_BYTES)]


def write_header(path: Path, records: list[tuple[str, int, list[int]]]) -> None:
    offsets: list[int] = []
    values: list[int] = []
    for _, _, crcs in records:
        offsets.append(len(values))
        values.extend(crcs)
    offsets.append(len(values))
    with path.open("w", newline="\n") as out:
        out.write("/* Generated by tools/gen_pcfx_cd_checksums.py. Do not edit. */\n")
        out.write("#ifndef WAIFU_PCFX_CD_CHECKSUMS_H\n#define WAIFU_PCFX_CD_CHECKSUMS_H\n\n")
        out.write("#include <stdint.h>\n\n")
        out.write("typedef enum WaifuPcfxCdChecksumAsset {\n")
        for index, (name, _, _) in enumerate(records):
            out.write(f"    WAIFU_PCFX_CD_CHECKSUM_{name} = {index},\n")
        out.write("    WAIFU_PCFX_CD_CHECKSUM_ASSET_COUNT\n")
        out.write("} WaifuPcfxCdChecksumAsset;\n\n")
        out.write("typedef struct WaifuPcfxCdChecksumRecord {\n")
        out.write("    uint32_t bytes;\n    uint16_t sectors;\n    uint16_t crc_offset;\n")
        out.write("} WaifuPcfxCdChecksumRecord;\n\n")
        out.write("static const WaifuPcfxCdChecksumRecord waifu_pcfx_cd_checksum_records[] = {\n")
        for index, (_, size, crcs) in enumerate(records):
            out.write(f"    {{{size}u, {len(crcs)}u, {offsets[index]}u}},\n")
        out.write("};\n\nstatic const uint32_t waifu_pcfx_cd_sector_crc32[] = {\n")
        for index, crc in enumerate(values):
            if index % 6 == 0:
                out.write("    ")
            out.write(f"0x{crc:08X}u")
            out.write(",\n" if index % 6 == 5 or index + 1 == len(values) else ", ")
        out.write("};\n\n#endif /* WAIFU_PCFX_CD_CHECKSUMS_H */\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--assets", type=Path, default=Path("assets/generated"))
    parser.add_argument("--header", type=Path, default=Path("src/generated/pcfx_cd_checksums.h"))
    args = parser.parse_args()
    recovery = args.assets / "recovery"
    recovery.mkdir(parents=True, exist_ok=True)
    args.header.parent.mkdir(parents=True, exist_ok=True)
    records = []
    for name, filename in ASSETS:
        data = (args.assets / filename).read_bytes()
        # A byte-for-byte recovery copy is intentionally separate in the image.
        (recovery / filename).write_bytes(data)
        records.append((name, len(data), [zlib.crc32(s) & 0xFFFFFFFF for s in sectors(data)]))
    write_header(args.header, records)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
