// Generated by tools/msx2/gen_msx_floor.py; do not edit.
#pragma once
#define MSX2_FLOOR_TEXTURE_SEG 228
#define MSX2_FLOOR_SPAN_SEG 229
#define MSX2_FLOOR_POSES 23
#define MSX2_FLOOR_ROW_BYTES 96
#define MSX2_FLOOR_TEX_BYTES 2560
#define MSX2_FLOOR_MIP_BASE 0
#define MSX2_FLOOR_FINE_BASE 512
#define MSX2_FLOOR_MAX_RECTS 24
#define MSX2_FLOOR_STRIDE_AT 327
#define MSX2_FLOOR_ROW0_AT 328
#define MSX2_FLOOR_ROW1_AT 329
#define MSX2_FLOOR_SPLIT_AT 330
static const unsigned char g_floor_segments[] = {0,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,4,5,5,5,5,6,6};
static const unsigned short g_floor_offsets[] = {0,3224,6440,10602,0,4136,8283,0,4409,8979,0,4751,9458,0,4655,8730,12644,0,3224,6448,11776,0,5432};
