#!/usr/bin/env python3
"""Reciprocal and trigonometric tables for the SNES renderer.

The 65816 has no divide, and 816-tcc's 32-bit one (tcc__divl) is several
hundred cycles a call.  The perspective divide is therefore a ROM lookup
followed by one hardware multiply: a FastROM read is six master cycles, so the
table IS the divider.

  snes_recip_row[n] = 65536 / n      the plane equation's 1/rows_below
  snes_recip_row2[n] = 131072 / n    the same for rows counted in PIXELS on
                                     the 1:1 board, where a pixel row is
                                     half a unit row (saturated for n < 3,
                                     which is inside the far edge anyway)
  snes_sin[a]                        Q8.8 sine over a 256-step turn

The ranges are asserted here rather than clamped at runtime.  That is the point
of generating them: the Atari ST port's fxdiv shipped an overflow that read as
a broken texture mapper, and a table whose domain is checked at build time
cannot reproduce it.
"""

import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "src", "snes", "snes_tables.asm")

RECIP_ROWS = 256


def main():
    recip = []
    for n in range(RECIP_ROWS):
        if n == 0:
            # Row zero is the horizon itself: the floor mapper never asks for
            # it (a row at or above the horizon has no board on it), and
            # 65536/0 has no representable answer, so it is poisoned with the
            # largest depth instead of silently reading as 1/65536.
            recip.append(0xFFFF)
        else:
            recip.append(min(0xFFFF, 65536 // n))
    # The nearest scanline the board can occupy is one row below the horizon,
    # and the entry for it must still be the biggest depth in the table.
    assert recip[1] == 0xFFFF and recip[2] < recip[1]

    recip2 = []
    for n in range(RECIP_ROWS):
        recip2.append(0xFFFF if n == 0 else min(0xFFFF, 131072 // n))

    sin = []
    for a in range(256):
        v = int(round(math.sin(a * math.pi / 128.0) * 256.0))
        v = max(-32768, min(32767, v))
        sin.append(v & 0xFFFF)
    assert sin[0] == 0 and sin[64] == 256

    lines = [
        "; Generated by tools/snes/gen_snes_tables.py; do not edit.",
        '.include "hdr.asm"',
        "",
        "; The tables live in their own bank so a section that outgrows it is a",
        "; build error rather than a silent shove of the card textures into the",
        "; next bank.  See SNES_PORT_PLAN.md section 5.",
        '.BASE $C0',
        '.SECTION "snes_tables" BANK 2 SLOT 0 SEMIFREE',
        "",
        "snes_recip_row:",
    ]

    def emit(values, per_line=8):
        for i in range(0, len(values), per_line):
            lines.append("    .dw " + ", ".join("$%04X" % v for v in values[i:i + per_line]))

    emit(recip)
    lines += ["", "snes_recip_row2:"]
    emit(recip2)
    lines += ["", "snes_sin:"]
    emit(sin)
    lines += ["", "snes_recip_plane:"]
    emit([min(32767, 65536 // max(1, n)) for n in range(1024)])
    lines += ["", ".ENDS", ""]

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print("%s: %d reciprocal entries, %d sine entries, %d bytes"
          % (os.path.relpath(OUT, ROOT), len(recip), len(sin),
             2 * (len(recip) + len(sin))))


if __name__ == "__main__":
    main()
