#!/usr/bin/env python3
"""The Mode 3 Direct Colour board's ROM tables (SNES_MODE3_PLAN.md).

The duel board is a BG1 8bpp Direct Colour tile field: the texel byte is the
colour (BBGGGRRR, the same cube every SNES asset here is quantised into), and
the software renderer's chunky frame has to be transposed into the PPU's
planar tile format before it can be shown.  That transpose is a table lookup,
and this file generates the table and the pictures it starts from:

  * the PAIR LUT -- 4 plane pairs x 2 halves x 64 KB = 512 KB.  Two chunky
    texels (t1 << 8 | t0) index one word per plane pair whose bytes carry
    t0's bit in column 0 and t1's in column 1 (bits 7 and 6); the converter
    (tools/snes/gen_snes_conv.py) shifts the pair into columns 2p, 2p+1 with
    2p `lsr`s, which cannot carry between the bytes because the low six bits
    of each are zero.  The 17-bit word offset is split on its top bit into
    two 64 KB halves, which is what the converter's `asl / bcs` does.
  * the TEXEL LUT -- 8 pixel positions x 4 plane pairs x 256 words = 16 KB,
    one texel to one pixel: the same transpose a texel at a time, kept for
    the harness's reference encoder.
  * the ROM floors -- the resting slab rendered for both camera poses (yaw 0
    and yaw 128) at 256x144, both as the chunky picture the cards are drawn
    over and as the same picture's 576 planar tiles, which the converter
    DMAs straight to VRAM for any resting cell no card, marker or held card
    touches; plus the occupied columns of each 8-row band, the resting
    frame's cell span.

The 128x72 motion path's doubled-pair LUT is gone: the board is 1:1 in every
pose now.

Everything is emitted one .asm per bank so a blob that outgrows its bank is a
link error rather than a silent overlap.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np  # noqa: E402
from PIL import Image  # noqa: E402
import snes_dc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ASSETS = os.path.join(ROOT, "src", "snes", "assets")

# ── Banks ────────────────────────────────────────────────────────────────────
# Free at the time of writing (SNES_MODE3_PLAN.md 4): $03-$05, $10-$12,
# $33-$3F.  The texel LUT sits above the upper 32x32 card sheet.
PAIRLUT_BANKS = list(range(51, 59))       # $33-$3A
TEXLUT_BANK = 60                          # $3C
TEXLUT_ORG = 0x4000
FLOOR_BANKS = {("chunky", 0): 61, ("chunky", 1): 62,
               ("planar", 0): 63, ("planar", 1): 16}

# ── The board and the resting camera ─────────────────────────────────────────
# Mirrors src/snes/snes_board3d.c / snes_duel.c exactly; the generated header
# hands the numbers back to C so the two cannot drift.
BOARD_W, BOARD_H = 256, 144
FOCAL = 128.0            # half the viewport width: what makes du a shift
HORIZON = BOARD_H >> 5   # 4: the same proportion the 128x72 motion frame uses
CAM_HEIGHT = 2.75
# 144/256 is a narrower vertical field than the old 80/128, so the camera
# stands further back than the Mode 7 board's 2.75-in-front-of-the-near-edge.
CAM_Z = -5.0
TEXELS_PER_UNIT = 32
HALF_X = 2.5             # the slab: five columns, four rows
Z_NEAR, Z_FAR = -2.0, 2.0
WALL_DEPTH = 0.25        # the slab's front wall, in world units
WALL_COLOUR = (3) | (2 << 3) | (0 << 6)    # SNES_SLAB_WALL, sandstone in shadow


def emit_bank(name, bank, blobs, org=0):
    """One .asm per bank.  `blobs` is [(label, bytes)]."""
    total = sum(len(b) for _, b in blobs)
    assert org + total <= 0x10000, "%s: %d bytes, past one bank" % (name, total)
    lines = [
        "; Generated by tools/snes/gen_snes_planar.py; do not edit.",
        '.include "hdr.asm"',
        ".BASE $C0",
        '.SECTION "%s" BANK %d SLOT 0 ORG $%04X FORCE' % (name, bank, org),
        "",
    ]
    for label, blob in blobs:
        with open(os.path.join(ASSETS, label + ".bin"), "wb") as fh:
            fh.write(blob)
        lines += ["%s:" % label, '    .INCBIN "%s.bin"' % label, ""]
    lines += [".ENDS", ""]
    with open(os.path.join(ASSETS, name + ".asm"), "w") as fh:
        fh.write("\n".join(lines))
    print("%s: bank $%02X, %d bytes" % (name, 0xC0 + bank, total))


# ── The pair LUT ─────────────────────────────────────────────────────────────

def pair_lut(plane_pair, half):
    """32768 words: index = (t1 << 8 | t0) & 0x7FFF for this half.

    Low byte = plane 2k, high byte = plane 2k+1.  t0's bit lands in column 0
    (bit 7), t1's in column 1 (bit 6); the six low bits are zero."""
    idx = np.arange(32768, dtype=np.uint32) | (half << 15)
    t0 = idx & 0xFF
    t1 = (idx >> 8) & 0xFF
    k = plane_pair
    lo = (((t0 >> (2 * k)) & 1) * 0x80) | (((t1 >> (2 * k)) & 1) * 0x40)
    hi = (((t0 >> (2 * k + 1)) & 1) * 0x80) | (((t1 >> (2 * k + 1)) & 1) * 0x40)
    words = (lo | (hi << 8)).astype("<u2")
    return words.tobytes()


def emit_pair_luts():
    i = 0
    for k in range(4):
        for h in range(2):
            label = "snes_pairlut_p%d_h%d" % (k, h)
            emit_bank(label, PAIRLUT_BANKS[i], [(label, pair_lut(k, h))])
            i += 1


# ── The rest texel LUT ───────────────────────────────────────────────────────

def texel_lut():
    """[pos 0..7][plane pair 0..3][texel 0..255] words: the texel's two bits
    at pixel column `pos` (0 = the tile row's leftmost pixel, bit 7)."""
    out = bytearray()
    t = np.arange(256, dtype=np.uint32)
    for pos in range(8):
        for k in range(4):
            lo = ((t >> (2 * k)) & 1) << (7 - pos)
            hi = ((t >> (2 * k + 1)) & 1) << (7 - pos)
            out += (lo | (hi << 8)).astype("<u2").tobytes()
    assert len(out) == 16384
    return bytes(out)


# ── The floors ───────────────────────────────────────────────────────────────

def floor_texture():
    with open(os.path.join(ASSETS, "snes_floor_tex.bin"), "rb") as fh:
        tex = np.frombuffer(fh.read(), dtype=np.uint8)
    return tex.reshape(64, 256)


def render_floor(yaw128):
    """The resting slab at 256x144 for one pose, as chunky direct colour.

    A plane through the camera has depth = height*focal/(row - horizon) on
    every row, so the floor is a row loop with a constant-v texture walk --
    the same model snes_board3d.c's card renderer uses at 1:1, which is what
    keeps the cards it draws sitting on the tiles drawn here."""
    tex = floor_texture()
    img = np.zeros((BOARD_H, BOARD_W), dtype=np.uint8)
    hf = CAM_HEIGHT * FOCAL
    d_near = Z_NEAR - CAM_Z
    d_far = Z_FAR - CAM_Z
    corners = {}
    for y in range(BOARD_H):
        rows_below = y - HORIZON
        if rows_below <= 0:
            continue
        depth = hf / rows_below
        if depth > d_far:
            continue
        if depth < d_near:
            # The front wall: its bottom edge is the near edge projected from
            # WALL_DEPTH below the board plane.
            wall_bottom = HORIZON + (CAM_HEIGHT + WALL_DEPTH) * FOCAL / d_near
            if y > wall_bottom:
                break
            x0 = BOARD_W / 2 + (-HALF_X) * FOCAL / d_near
            x1 = BOARD_W / 2 + (HALF_X) * FOCAL / d_near
            img[y, max(0, int(round(x0))):min(BOARD_W, int(round(x1)))] = WALL_COLOUR
            continue
        x0 = BOARD_W / 2 + (-HALF_X) * FOCAL / depth
        x1 = BOARD_W / 2 + (HALF_X) * FOCAL / depth
        ix0 = max(0, int(round(x0)))
        ix1 = min(BOARD_W, int(round(x1)))
        if ix1 <= ix0:
            continue
        xs = np.arange(ix0, ix1, dtype=np.float64)
        # Camera space -> world space.  Yaw 128 turns the board round: world
        # (x, z) = -(camera x, camera z).
        cx = (xs + 0.5 - BOARD_W / 2) * depth / FOCAL
        cz = CAM_Z + depth
        if yaw128:
            wx, wz = -cx, -cz
        else:
            wx, wz = cx, cz
        # The half-cell shift puts a cell boundary on every x.5 (see
        # snesDrawFloor's u_camera), and v's period is the 64-row checker.
        u = (np.floor(wx * TEXELS_PER_UNIT + TEXELS_PER_UNIT / 2).astype(np.int64)) & 255
        v = int(np.floor(wz * TEXELS_PER_UNIT)) & 63
        img[y, ix0:ix1] = tex[v, u]
        corners.setdefault("first", (y, ix0, ix1))
        corners["last"] = (y, ix0, ix1)
    return img, corners


def planar_tiles(img):
    """256x144 chunky -> 576 8bpp planar tiles (64 bytes each), row-major."""
    h, w = img.shape
    out = bytearray()
    for ty in range(h // 8):
        for tx in range(w // 8):
            cell = img[ty * 8:ty * 8 + 8, tx * 8:tx * 8 + 8]
            tile = bytearray(64)
            for k in range(4):
                for r in range(8):
                    lo = hi = 0
                    for c in range(8):
                        t = int(cell[r, c])
                        lo |= ((t >> (2 * k)) & 1) << (7 - c)
                        hi |= ((t >> (2 * k + 1)) & 1) << (7 - c)
                    tile[k * 16 + r * 2] = lo
                    tile[k * 16 + r * 2 + 1] = hi
            out += tile
    return bytes(out)


def floor_rowspan(img):
    """Per 8-row band, the first and last column that is not backdrop (0);
    255/0 for a band the slab does not reach.  This is the converter's row
    span for the resting frame."""
    h, w = img.shape
    out = []
    for ty in range(h // 8):
        band = img[ty * 8:ty * 8 + 8]
        cols = np.nonzero(band.any(axis=0))[0]
        if len(cols) == 0:
            out += [255, 0]
        else:
            out += [int(cols[0]), int(cols[-1])]
    return out


def emit_floors():
    spans = {}
    for pose in (0, 1):
        img, corners = render_floor(pose)
        chunky = img.tobytes()
        assert len(chunky) == BOARD_W * BOARD_H
        print("floor pose %d: slab rows %s .. %s" % (pose, corners.get("first"),
                                                     corners.get("last")))
        emit_bank("snes_floor_chunky_%d" % pose, FLOOR_BANKS[("chunky", pose)],
                  [("snes_floor_chunky_%d" % pose, chunky)])
        emit_bank("snes_floor_planar_%d" % pose, FLOOR_BANKS[("planar", pose)],
                  [("snes_floor_planar_%d" % pose, planar_tiles(img))])
        snes_dc.write_preview(os.path.join(ASSETS, "floor_rest_%d_preview.png" % pose),
                              chunky, (BOARD_W, BOARD_H))
        spans[pose] = floor_rowspan(img)
        cells = sum(s[1] // 8 - s[0] // 8 + 1 for s in zip(spans[pose][0::2], spans[pose][1::2])
                    if s[0] != 255)
        assert cells <= 351, "floor pose %d occupies %d cells, past the sparse budget" % (pose, cells)
        print("floor pose %d: %d occupied cells" % (pose, cells))
    return spans


def slot_boxes():
    """Conservative screen-cell bounds for all twenty slots, both seats."""
    out = []
    for mirror in (False, True):
        for row in range(4):
            for col in range(5):
                cx, cz = col - 2, 1.5 - row
                if mirror:
                    cx, cz = -cx, -cz
                corners = [(BOARD_W/2 + (cx+dx)*FOCAL/(cz+dz-CAM_Z),
                            HORIZON + CAM_HEIGHT*FOCAL/(cz+dz-CAM_Z))
                           for dx in (-0.5,0.5) for dz in (-0.5,0.5)]
                xs, ys = zip(*corners)
                out += [max(0,int(min(xs))-1)//8, max(0,int(min(ys))-1)//8,
                        min(BOARD_W-1,int(max(xs))+1)//8,
                        min(BOARD_H-1,int(max(ys))+1)//8]
    return out


def emit_header(spans):
    path = os.path.join(ROOT, "src", "snes", "snes_planar_data.h")
    with open(path, "w") as fh:
        fh.write("""/* Generated by tools/snes/gen_snes_planar.py; do not edit. */
#ifndef WAIFU_SNES_PLANAR_DATA_H
#define WAIFU_SNES_PLANAR_DATA_H

#include "snes_types.h"

/* The resting camera the ROM floors were rendered with, in Q8.8 where the
 * renderer wants Q8.8.  snes_duel.c MUST use these for the resting board, or
 * the cards it draws will not sit on the tiles the floor shows. */
#define SNES_REST_CAM_Z       ((s16)%d)
#define SNES_REST_CAM_HEIGHT  ((s16)%d)
#define SNES_REST_HORIZON_PX  %d
#define SNES_REST_W           %d
#define SNES_REST_H           %d

/* Both poses: chunky 256x144 (the base the cards are drawn over) and the
 * same picture as 576 planar tiles, DMA'd straight to VRAM where no card
 * lies. */
extern const u8 snes_floor_chunky_0[];
extern const u8 snes_floor_chunky_1[];
extern const u8 snes_floor_planar_0[];
extern const u8 snes_floor_planar_1[];
#define SNES_FLOOR_CHUNKY_BANK_0  0x%02X
#define SNES_FLOOR_CHUNKY_BANK_1  0x%02X
#define SNES_FLOOR_PLANAR_BANK_0  0x%02X
#define SNES_FLOOR_PLANAR_BANK_1  0x%02X

/* Per 8-row cell band of each floor: {first, last} occupied pixel column,
 * 255/0 where the slab does not reach.  The resting frame's row span. */
static const u8 snes_floor_rowspan_0[36] = { %s };
static const u8 snes_floor_rowspan_1[36] = { %s };

#endif
""" % (int(round(CAM_Z * 256)), int(round(CAM_HEIGHT * 256)), HORIZON,
       BOARD_W, BOARD_H,
       0xC0 + FLOOR_BANKS[("chunky", 0)], 0xC0 + FLOOR_BANKS[("chunky", 1)],
       0xC0 + FLOOR_BANKS[("planar", 0)], 0xC0 + FLOOR_BANKS[("planar", 1)],
       ", ".join(str(v) for v in spans[0]), ", ".join(str(v) for v in spans[1])))
    # Keep the generated bounds beside the camera constants that define them.
    text = open(path).read()
    bounds = slot_boxes()
    declaration = "static const u8 snes_rest_slot_boxes[160] = {\n"
    declaration += "\n".join("    " + ", ".join(str(v) for v in bounds[i:i+20]) + ","
                             for i in range(0,160,20))
    declaration += "\n};\n\n"
    with open(path,"w") as fh:
        fh.write(text.replace("#endif",declaration+"#endif"))
    print("%s written" % os.path.relpath(path, ROOT))


def main():
    os.makedirs(ASSETS, exist_ok=True)
    emit_pair_luts()
    emit_bank("snes_texlut", TEXLUT_BANK, [("snes_texlut", texel_lut())],
              org=TEXLUT_ORG)
    spans = emit_floors()
    emit_header(spans)



if __name__ == "__main__":
    main()
