#!/usr/bin/env python3
"""The 8x8 chunky font, out of the shared 1bpp table every port draws with.

src/engine/font_menudata.h is the same 128-glyph table the PC, CD32X and Atari
ST builds use, so the SNES HUD says things in the same letters they do; it is
copied into ROM here rather than re-drawn, and nothing about it is generated
procedurally.

It stays ONE BIT PER PIXEL in ROM.  The text blitter in snes_raster.asm shifts
a row byte and stores the ink colour on a set bit, so a glyph costs eight bytes
rather than sixty-four, and the colour is the caller's -- which is what lets the
same glyph be drawn twice, once offset as its own shadow, to stay legible over
the arena's sandstone.
"""

import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "src", "engine", "font_menudata.h")
ASSETS = os.path.join(ROOT, "src", "snes", "assets")
BANK = 9                     # $C9; the card sheet is $C8


def font_bytes():
    text = open(SRC).read()
    body = text[text.index("n2DLib_font[128 * 8] ="):]
    values = [int(v, 16) for v in re.findall(r"0x([0-9A-Fa-f]{2})", body)]
    assert len(values) >= 128 * 8, "font table is %d bytes" % len(values)
    return bytes(values[:128 * 8])


def main():
    os.makedirs(ASSETS, exist_ok=True)
    blob = font_bytes()
    with open(os.path.join(ASSETS, "snes_font.bin"), "wb") as fh:
        fh.write(blob)
    with open(os.path.join(ASSETS, "snes_font.asm"), "w") as fh:
        fh.write("\n".join([
            "; Generated by tools/snes/gen_snes_font.py; do not edit.",
            '.include "hdr.asm"',
            ".BASE $C0",
            '.SECTION "snes_font" BANK %d SLOT 0 ORG $0000 FORCE' % BANK,
            "",
            "snes_font:",
            '    .INCBIN "snes_font.bin"',
            "",
            ".ENDS",
            "",
        ]))
    print("src/snes/assets/snes_font.asm: bank $%02X, %d bytes"
          % (0xC0 + BANK, len(blob)))


if __name__ == "__main__":
    main()
