#!/usr/bin/env python3
"""The arena floor texture, in Mode 7 direct colour.

Everything the slab does not cover is BLACK -- there is no backdrop picture and
no horizon band.  The board is the only textured object on the screen, which is
what the other ports' duel views look like and what a two-bit blue channel can
actually hold.

Everything here is converted from assets/source/; nothing is drawn
procedurally beyond the groove that separates one board tile from the next,
which is a property of the board rather than a picture.

**The floor texture is 256 texels wide, and that width is the rasteriser's**
The span walker keeps the texture's u coordinate in one byte, so u wraps at
256 for free -- no mask, no branch, one instruction saved on every texel of
every floor pixel in the game.  Eight 32-texel board tiles fit across that
width, an even number, so the checkerboard still alternates across the wrap.

The span walker's texture index is (v << 8) | u with v held in the hidden half
of the accumulator, so u wraps inside its own row and never disturbs v.  That
is what lets the texture be only 64 rows tall -- two board rows, the vertical
period of the checker -- for 16 KB rather than 64.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from PIL import Image  # noqa: E402
import snes_dc  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, "assets", "source")
ASSETS = os.path.join(ROOT, "src", "snes", "assets")

# One world unit -- one slot pitch -- is 32 texels, so the 256-wide texture
# spans eight units and the board's five never see the repeat.
TEXELS_PER_UNIT = 32
TEX_W = 256
TEX_H = 64
PATTERN_H = 64          # two board rows; the vertical period of the checker

# The groove between tiles.  Two texels at the tile edge, darkened rather than
# recoloured, so the board reads as cut stone instead of as a grid drawn on a
# rug.
GROOVE_TEXELS = 2
GROOVE_SCALE = 0.45


def tile(path, size):
    with Image.open(path) as im:
        return im.convert("RGB").resize((size, size), Image.LANCZOS)


def build_floor():
    a = tile(os.path.join(SRC, "textures", "sandstone_1.png"), TEXELS_PER_UNIT)
    b = tile(os.path.join(SRC, "textures", "sandstone_2.png"), TEXELS_PER_UNIT)
    pattern = Image.new("RGB", (TEX_W, PATTERN_H))
    for ty in range(PATTERN_H // TEXELS_PER_UNIT):
        for tx in range(TEX_W // TEXELS_PER_UNIT):
            pattern.paste(b if (tx + ty) & 1 else a,
                          (tx * TEXELS_PER_UNIT, ty * TEXELS_PER_UNIT))

    px = pattern.load()
    for y in range(PATTERN_H):
        for x in range(TEX_W):
            on_edge = (x % TEXELS_PER_UNIT) < GROOVE_TEXELS or \
                      (y % TEXELS_PER_UNIT) < GROOVE_TEXELS
            if on_edge:
                r, g, bl = px[x, y]
                px[x, y] = (int(r * GROOVE_SCALE), int(g * GROOVE_SCALE),
                            int(bl * GROOVE_SCALE))

    full = Image.new("RGB", (TEX_W, TEX_H))
    for y in range(0, TEX_H, PATTERN_H):
        full.paste(pattern, (0, y))
    return full


def emit(name, bank, blobs):
    """One .asm per bank, so a section that outgrows its 64 KB is a link
    error rather than a silent wrap into the next bank's contents."""
    path = os.path.join(ASSETS, name + ".asm")
    total = sum(len(b[1]) for b in blobs)
    assert total <= 0x10000, "%s is %d bytes, past one bank" % (name, total)
    lines = [
        "; Generated by tools/snes/gen_snes_textures.py; do not edit.",
        '.include "hdr.asm"',
        ".BASE $C0",
        '.SECTION "%s" BANK %d SLOT 0 ORG $0000 FORCE' % (name, bank),
        "",
    ]
    for label, blob in blobs:
        binname = label + ".bin"
        with open(os.path.join(ASSETS, binname), "wb") as fh:
            fh.write(blob)
        lines += ["%s:" % label, '    .INCBIN "%s"' % binname, ""]
    lines += [".ENDS", ""]
    with open(path, "w") as fh:
        fh.write("\n".join(lines))
    print("%s: bank $%02X, %d bytes" % (os.path.relpath(path, ROOT), 0xC0 + bank, total))


def main():
    os.makedirs(ASSETS, exist_ok=True)
    floor = build_floor()
    floor_bytes = snes_dc.quantize(floor, (TEX_W, TEX_H))
    assert len(floor_bytes) == TEX_W * TEX_H

    # A preview, because a texture that is wrong in the cube is not visible in
    # a hex dump and is very visible on the board.
    snes_dc.write_preview(os.path.join(ASSETS, "floor_preview.png"),
                          floor_bytes, (TEX_W, TEX_H))

    emit("snes_floor", 6, [("snes_floor_tex", floor_bytes)])

    header = os.path.join(ROOT, "src", "snes", "snes_textures.h")
    with open(header, "w") as fh:
        fh.write("""/* Generated by tools/snes/gen_snes_textures.py; do not edit. */
#ifndef WAIFU_SNES_TEXTURES_H
#define WAIFU_SNES_TEXTURES_H

#include "snes_types.h"

/* One world unit -- one slot pitch -- in texels. */
#define SNES_FLOOR_TEXELS_PER_UNIT %d
#define SNES_FLOOR_W %d
#define SNES_FLOOR_H %d
#define SNES_FLOOR_PATTERN_H %d

/* 256 bytes a row, so the span walker's u wraps in one byte with no mask. */
extern const u8 snes_floor_tex[];

#endif
""" % (TEXELS_PER_UNIT, TEX_W, TEX_H, PATTERN_H))
    print("%s written" % os.path.relpath(header, ROOT))


if __name__ == "__main__":
    main()
