#!/usr/bin/env python3
"""Extract the canonical story prose from src/main.c for the SNES fork."""
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src" / "main.c"
OUTPUT = ROOT / "src" / "snes" / "snes_dialogue_data.h"

def main():
    text = SOURCE.read_text(encoding="utf-8")
    duels, speakers = [], []
    for duel in range(5):
        m = re.search(r"g_story_duel%d_dialogue\[\].*?=\s*\{(.*?)\n\};" % duel, text, re.S)
        if not m: raise SystemExit("missing canonical dialogue table %d" % duel)
        entries = re.findall(r"\{STORY_SPK_(SERENA|OPPONENT),\s*(\"(?:\\.|[^\"\\])*\")\}", m.group(1))
        if not entries: raise SystemExit("empty canonical dialogue table %d" % duel)
        duels.append([ast.literal_eval(s).upper() for _, s in entries])
        speakers.append([0 if who == "SERENA" else 1 for who, _ in entries])
    m = re.search(r"story_ending_lines\[\]\s*=\s*\{(.*?)\n\};", text, re.S)
    if not m: raise SystemExit("missing canonical ending table")
    ending = [ast.literal_eval(s).upper() for s in re.findall(r'"(?:\\.|[^"\\])*"', m.group(1))]
    if any(len(x) < 9 for x in duels) or len(ending) != 4: raise SystemExit("unexpected story table sizes")
    q = lambda s: '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'
    out = ["/* Generated by tools/snes/gen_snes_dialogue.py. */", "#ifndef WAIFU_SNES_DIALOGUE_DATA_H", "#define WAIFU_SNES_DIALOGUE_DATA_H", "", '#include "snes_types.h"', "", "#define SNES_STORY_MAX_LINES %d" % max(map(len, duels)), "#define SNES_ENDING_LINE_COUNT 4", "", "static const char *const snes_story_lines[5][SNES_STORY_MAX_LINES] = {"]
    out += ["    {" + ", ".join(q(s) for s in lines) + "}," for lines in duels]
    out += ["};", "static const u8 snes_story_line_count[5] = {" + ", ".join(str(len(x)) for x in duels) + "};", "static const u8 snes_story_speaker[5][SNES_STORY_MAX_LINES] = {"]
    out += ["    {" + ", ".join(map(str, row)) + "}," for row in speakers]
    out += ["};", "static const char *const snes_ending_lines[SNES_ENDING_LINE_COUNT] = {", "    " + ", ".join(q(s) for s in ending), "};", "", "#endif"]
    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8")

if __name__ == "__main__": main()
